export const RACES = [
  'Humano',
  'Anão',
  'Dahllan',
  'Elfo',
  'Goblin',
  'Lefou',
  'Minotauro',
  'Qareen',
  'Suraggel',
  'Sílfide',
  'Sereia/Tritão',
  'Osteon',
  'Medusa',
  'Kiiren',
  'Hynne',
  'Golem',
  'Trog',
] as const;
export type Race = (typeof RACES)[number];

export const CLASSES = [
  'Arcanista',
  'Bárbaro',
  'Bardo',
  'Bucaneiro',
  'Caçador',
  'Cavaleiro',
  'Clérigo',
  'Druida',
  'Guerreiro',
  'Inventor',
  'Ladino',
  'Lutador',
  'Nobre',
  'Paladino',
] as const;
export type ClassName = (typeof CLASSES)[number];

export const ORIGINS = [
  'Acólito',
  'Amigo dos Animais',
  'Amnésico',
  'Aristocrata',
  'Artesão',
  'Artista',
  'Assistente de Laboratório',
  'Batedor',
  'Capanga',
  'Charlatão',
  'Circense',
  'Criminoso',
  'Curandeiro',
  'Eremita',
  'Escravo',
  'Estudioso',
  'Fazendeiro',
  'Forasteiro',
  'Gladiador',
  'Guarda',
  'Herdeiro',
  'Herói Camponês',
  'Marujo',
  'Mateiro',
  'Membro de Guilda',
  'Mercador',
  'Minerador',
  'Nômade',
  'Pivete',
  'Refugiado',
  'Seguidor',
  'Selvagem',
  'Soldado',
  'Taverneiro',
  'Trabalhador',
] as const;
export type Origin = (typeof ORIGINS)[number];

export const GODS = [
  'Tauron',
  'Aharadak',
  'Allihanna',
  'Arsenal',
  'Azgher',
  'Hyninn',
  'Kallyadranoch',
  'Khalmyr',
  'Lena',
  'Lin-Wu',
  'Marah',
  'Megalokk',
  'Nimb',
  'Oceano',
  'Sszzaas',
  'Tanna-Toh',
  'Tenebra',
  'Thwor',
  'Thyatis',
  'Valkaria',
  'Wynna',
] as const;
export type God = (typeof GODS)[number];

export {
  ATTRIBUTE_KEYS,
  ATTRIBUTE_ABBR,
  type AttributeKey,
  EXPERTISES,
  EXPERTISE_NAMES,
  type ExpertiseDef,
  type ExpertiseName,
  trainingBonusForLevel,
  SIZES,
  type Size,
  DEFAULT_SIZE,
  DEFAULT_DISPLACEMENT,
} from '@tormenta20/t20-data';
