package main

import (
	"database/sql"
	"fmt"
	"strconv"
	"strings"
)

// seedTimestamp normalizes every `*At` column so regenerating the dump is
// deterministic (only real data changes show up in the diff, not the wall clock).
const seedTimestamp = "2026-01-01T00:00:00.000Z"

// devPasswordHash is a fixed bcrypt hash of the dev password (seed-data.json's
// `password` = "mestre123456"), embedded so the dump is deterministic — bcrypt's
// random salt would otherwise churn `passwordHash` on every regeneration. Not a
// secret (dev-only *@t20.local accounts); login still verifies, since any valid
// hash of the password works.
const devPasswordHash = "$2a$12$Ku./e3OJK1zttNtfwZukYOaz2xi.wDk5dP86tn7dfkC.6Hevh1Gn."

// dumpTables — the data tables in FK (parent→child) order for INSERT; the reset
// DELETEs run in reverse. goose_db_version is intentionally excluded (schema
// versioning belongs to the migrated target, not the seed).
var dumpTables = []string{
	"users",
	"campaigns",
	"characters",
	"character_classes",
	"character_races",
	"character_expertises",
	"character_items",
	"character_spells",
	"campaign_members",
	"sessions",
	"active_effects",
}

// dump renders the seeded DB as an idempotent SQL script: reset the data tables
// (FK off, so order is free) then re-insert with explicit ids so the dataset is
// byte-for-byte reproducible.
func dump(database *sql.DB) (string, error) {
	var b strings.Builder
	b.WriteString("-- Generated by `go run ./cmd/seed` (ALE-57). Do NOT edit by hand.\n")
	b.WriteString("-- Dev dataset: 3 accounts (*@t20.local — see cmd/seed/seed-data.json),\n")
	b.WriteString("-- the diverse test roster and demo chronicles. Apply from engine-go:\n")
	b.WriteString("--   sqlite3 t20-go.db < seed.sql\n\n")
	b.WriteString("PRAGMA foreign_keys = OFF;\nBEGIN TRANSACTION;\n\n")
	b.WriteString("DELETE FROM sqlite_sequence;\n")
	for i := len(dumpTables) - 1; i >= 0; i-- {
		fmt.Fprintf(&b, "DELETE FROM %s;\n", dumpTables[i])
	}
	b.WriteString("\n")
	for _, table := range dumpTables {
		if err := dumpTable(&b, database, table); err != nil {
			return "", err
		}
	}
	b.WriteString("COMMIT;\nPRAGMA foreign_keys = ON;\n")
	return b.String(), nil
}

func dumpTable(b *strings.Builder, database *sql.DB, table string) error {
	// table comes only from the fixed dumpTables allowlist above.
	rows, err := database.Query(fmt.Sprintf("SELECT * FROM %s ORDER BY rowid", table))
	if err != nil {
		return fmt.Errorf("select %s: %w", table, err)
	}
	defer func() { _ = rows.Close() }()
	cols, err := rows.Columns()
	if err != nil {
		return err
	}
	quoted := make([]string, len(cols))
	for i, c := range cols {
		quoted[i] = `"` + c + `"`
	}
	colList := strings.Join(quoted, ", ")
	rowN := 0
	for rows.Next() {
		vals := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range vals {
			ptrs[i] = &vals[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			return err
		}
		lits := make([]string, len(vals))
		for i, v := range vals {
			switch {
			case cols[i] == "passwordHash":
				lits[i] = quote(devPasswordHash)
			case v != nil && strings.HasSuffix(cols[i], "At"):
				lits[i] = quote(seedTimestamp)
			default:
				lits[i] = sqlLiteral(v)
			}
		}
		fmt.Fprintf(b, "INSERT INTO %s (%s) VALUES (%s);\n", table, colList, strings.Join(lits, ", "))
		rowN++
	}
	if err := rows.Err(); err != nil {
		return err
	}
	if rowN > 0 {
		b.WriteString("\n")
	}
	return nil
}

// sqlLiteral renders a scanned SQLite value as a SQL literal. The modernc driver
// returns int64 / float64 / bool / string / []byte / nil.
func sqlLiteral(v any) string {
	switch x := v.(type) {
	case nil:
		return "NULL"
	case int64:
		return strconv.FormatInt(x, 10)
	case float64:
		return strconv.FormatFloat(x, 'g', -1, 64)
	case bool:
		if x {
			return "1"
		}
		return "0"
	case []byte:
		return quote(string(x))
	case string:
		return quote(x)
	default:
		return quote(fmt.Sprintf("%v", x))
	}
}

func quote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}
