/**
 * Bestiário — PDF Cap 7 (Ameaças), livro p282-323.
 *
 * Núcleo original: 20 monstros cobrindo NDs 1/4 → 20 selecionados para
 * representar cada tipo (humanoide, animal, monstro, morto-vivo,
 * construto) e tamanho (pequeno → colossal).
 *
 * Expansão #1 (livro p286-298): +31 monstros dos grupos Masmorras,
 * Ermos, Puristas e Reino dos Mortos.
 * Expansão #2 (livro p300-316): +29 monstros dos grupos Duyshidakk,
 * Sszzaazitas, Trolls Nobres, Dragões complementares, Tormenta.
 * Total atual: 80.
 *
 * `treasureXp` segue a regra de PDF Cap 8 (Recompensas, p326):
 * `XP = ND × 1.000` (clamp dos ND fracionados em 250/500).
 */

export type MonsterTipo =
  | 'humanoide'
  | 'animal'
  | 'monstro'
  | 'morto-vivo'
  | 'construto'
  | 'espirito'
  | 'planar'

export type MonsterSize =
  | 'minusculo'
  | 'pequeno'
  | 'medio'
  | 'grande'
  | 'enorme'
  | 'colossal'

export type MonsterAttack = {
  name: string
  attackBonus: number
  damage: string
  special?: string
}

export type Monster = {
  id: string
  name: string
  nd: number
  tipo: MonsterTipo
  size: MonsterSize
  hp: number
  defesa: number
  forca: number
  destreza: number
  constituicao: number
  inteligencia: number
  sabedoria: number
  carisma: number
  fortitude: number
  reflexos: number
  vontade: number
  deslocamento: string
  attacks: readonly MonsterAttack[]
  specialAbilities: readonly string[]
  treasureXp: number
  bookPage: number
}

/** XP de tesouro derivado do ND (PDF Cap 8 p326). */
export function xpForNd(nd: number): number {
  return Math.round(nd * 1000)
}

export const BESTIARY: readonly Monster[] = Object.freeze([
  {
    id: 'goblin-salteador',
    name: 'Goblin Salteador',
    nd: 0.25,
    tipo: 'humanoide',
    size: 'pequeno',
    hp: 4,
    defesa: 13,
    forca: 0, destreza: 3, constituicao: 0,
    inteligencia: 0, sabedoria: -1, carisma: -1,
    fortitude: 2, reflexos: 3, vontade: -1,
    deslocamento: '9m, escalada 9m',
    attacks: [{ name: 'Duas adagas', attackBonus: 7, damage: '1d4', special: 'crítico 19' }],
    specialAbilities: [
      'Frenesi: +2 em ataque e dano por cada outro goblin salteador adjacente ao alvo.',
      'Visão no escuro.',
    ],
    treasureXp: 250,
    bookPage: 300,
  },
  {
    id: 'zumbi',
    name: 'Zumbi',
    nd: 0.25,
    tipo: 'morto-vivo',
    size: 'medio',
    hp: 20,
    defesa: 11,
    forca: 3, destreza: -1, constituicao: 2,
    inteligencia: 0, sabedoria: -1, carisma: 0,
    fortitude: 3, reflexos: -1, vontade: -1,
    deslocamento: '6m',
    attacks: [{ name: 'Mordida', attackBonus: 7, damage: '1d6+6' }],
    specialAbilities: [
      'Fraqueza Zumbi: dobro de dano em críticos ou ataques contra cérebro (Defesa 21).',
      'Visão no escuro; imunidades de morto-vivo (cansaço/metabólicos/trevas/veneno).',
    ],
    treasureXp: 250,
    bookPage: 297,
  },
  {
    id: 'orc-combatente',
    name: 'Orc Combatente',
    nd: 0.5,
    tipo: 'humanoide',
    size: 'medio',
    hp: 8,
    defesa: 14,
    forca: 4, destreza: 1, constituicao: 2,
    inteligencia: -1, sabedoria: -1, carisma: -1,
    fortitude: 5, reflexos: 3, vontade: 0,
    deslocamento: '9m',
    attacks: [{ name: 'Maça', attackBonus: 9, damage: '1d8+7' }],
    specialAbilities: ['Sensibilidade a Luz: ofuscado sob luz solar.', 'Visão no escuro.'],
    treasureXp: 500,
    bookPage: 286,
  },
  {
    id: 'lobo',
    name: 'Lobo',
    nd: 0.5,
    tipo: 'animal',
    size: 'medio',
    hp: 14,
    defesa: 14,
    forca: 3, destreza: 3, constituicao: 3,
    inteligencia: -4, sabedoria: 2, carisma: -2,
    fortitude: 6, reflexos: 3, vontade: 1,
    deslocamento: '15m',
    attacks: [
      { name: 'Mordida', attackBonus: 7, damage: '1d6+5', special: 'derrubar (teste +7) em acerto' },
    ],
    specialAbilities: [
      'Táticas de Alcateia: +2 ataque/+2 dano ao flanquear (total +4/+2).',
      'Faro, visão na penumbra.',
    ],
    treasureXp: 500,
    bookPage: 289,
  },
  {
    id: 'esqueleto',
    name: 'Esqueleto',
    nd: 2,
    tipo: 'morto-vivo',
    size: 'medio',
    hp: 14,
    defesa: 19,
    forca: 5, destreza: 3, constituicao: 0,
    inteligencia: 0, sabedoria: 0, carisma: -5,
    fortitude: 3, reflexos: 7, vontade: 12,
    deslocamento: '9m',
    attacks: [{ name: 'Espada longa', attackBonus: 14, damage: '2d8+12', special: 'crítico 19' }],
    specialAbilities: [
      'Redução de corte, frio e perfuração 5.',
      'Visão no escuro; imunidades de morto-vivo.',
      'Sem inteligência: segue ordens do criador.',
    ],
    treasureXp: 2000,
    bookPage: 297,
  },
  {
    id: 'aranha-gigante',
    name: 'Aranha Gigante',
    nd: 2,
    tipo: 'monstro',
    size: 'grande',
    hp: 77,
    defesa: 19,
    forca: 5, destreza: 4, constituicao: 1,
    inteligencia: -5, sabedoria: 0, carisma: -4,
    fortitude: 8, reflexos: 11, vontade: 3,
    deslocamento: '12m, escalar 12m',
    attacks: [
      {
        name: 'Mordida',
        attackBonus: 12,
        damage: '2d6+8 mais veneno',
        special: 'Veneno: fraco (Fort CD 18 evita)',
      },
    ],
    specialAbilities: [
      'Teia (padrão): teia em quadrado 3m a curto, enredando (Ref CD 18 evita). Soltar = ação completa + Força/Acrobacia CD 20.',
      'Visão no escuro.',
    ],
    treasureXp: 2000,
    bookPage: 286,
  },
  {
    id: 'gargula',
    name: 'Gárgula',
    nd: 2,
    tipo: 'construto',
    size: 'medio',
    hp: 65,
    defesa: 19,
    forca: 6, destreza: 2, constituicao: 4,
    inteligencia: -2, sabedoria: 1, carisma: -2,
    fortitude: 13, reflexos: 7, vontade: 2,
    deslocamento: '12m, voo 18m',
    attacks: [{ name: 'Duas garras', attackBonus: 12, damage: '1d6+6' }],
    specialAbilities: [
      'Imobilidade: estática parece estátua (Percepção CD 35).',
      'Redução de dano 5; imune a condição petrificado.',
      'Visão no escuro; imunidades de construto.',
    ],
    treasureXp: 2000,
    bookPage: 286,
  },
  {
    id: 'dragao-filhote',
    name: 'Dragão Filhote',
    nd: 3,
    tipo: 'monstro',
    size: 'medio',
    hp: 140,
    defesa: 22,
    forca: 4, destreza: 3, constituicao: 3,
    inteligencia: 0, sabedoria: 0, carisma: 0,
    fortitude: 15, reflexos: 3, vontade: 9,
    deslocamento: '12m, voo 18m',
    attacks: [
      { name: 'Mordida', attackBonus: 15, damage: '2d6+5' },
      { name: 'Duas garras', attackBonus: 15, damage: '1d6+5' },
    ],
    specialAbilities: [
      'Sopro (padrão, recarga mov): cone 6m, 2d12 fogo + em chamas (Ref CD 18 reduz à metade e evita).',
      'Imune a fogo; vulnerável a frio; resistência a magia +1.',
      'Visão no escuro, percepção às cegas.',
    ],
    treasureXp: 3000,
    bookPage: 310,
  },
  {
    id: 'grifo',
    name: 'Grifo',
    nd: 3,
    tipo: 'monstro',
    size: 'grande',
    hp: 110,
    defesa: 19,
    forca: 5, destreza: 4, constituicao: 3,
    inteligencia: -4, sabedoria: 2, carisma: -1,
    fortitude: 9, reflexos: 15, vontade: 4,
    deslocamento: '12m, voo 24m',
    attacks: [
      { name: 'Mordida', attackBonus: 14, damage: '2d6+5' },
      { name: 'Duas garras', attackBonus: 14, damage: '1d6+5' },
    ],
    specialAbilities: [
      'Bote (completa): investida + mordida + duas garras contra mesmo alvo (+2 da investida).',
      'Imune a medo; visão no escuro.',
    ],
    treasureXp: 3000,
    bookPage: 292,
  },
  {
    id: 'basilisco',
    name: 'Basilisco',
    nd: 4,
    tipo: 'monstro',
    size: 'medio',
    hp: 145,
    defesa: 23,
    forca: 4, destreza: 2, constituicao: 4,
    inteligencia: -4, sabedoria: 1, carisma: 0,
    fortitude: 10, reflexos: 9, vontade: 9,
    deslocamento: '9m, natação 9m',
    attacks: [
      {
        name: 'Mordida',
        attackBonus: 16,
        damage: '2d8+12 mais veneno',
        special: 'Peçonha Concentrada (1d12 PV/rod por 3 rod; Fort CD 18 reduz para 1 rod).',
      },
    ],
    specialAbilities: [
      'Olhar Petrificante: criaturas em curto fazem Ref CD 18; falha = lento; já lento = petrificado permanente. Fechar olhos como reação imuniza por uma rodada (mas cego nessa rodada).',
      'Redução de dano 5; visão no escuro.',
    ],
    treasureXp: 4000,
    bookPage: 293,
  },
  {
    id: 'ogro',
    name: 'Ogro',
    nd: 4,
    tipo: 'humanoide',
    size: 'grande',
    hp: 130,
    defesa: 23,
    forca: 7, destreza: 0, constituicao: 4,
    inteligencia: -3, sabedoria: -2, carisma: -2,
    fortitude: 16, reflexos: 10, vontade: 0,
    deslocamento: '9m',
    attacks: [{ name: 'Tacape', attackBonus: 16, damage: '1d12+18' }],
    specialAbilities: [
      'Burro Demais...: -5 em Intuição e Vontade (já contabilizado).',
      '...Para Morrer!: dano de corte, impacto e perfuração reduzido à metade.',
      'Visão na penumbra.',
    ],
    treasureXp: 4000,
    bookPage: 293,
  },
  {
    id: 'urso-coruja',
    name: 'Urso-Coruja',
    nd: 4,
    tipo: 'monstro',
    size: 'grande',
    hp: 145,
    defesa: 23,
    forca: 7, destreza: 3, constituicao: 5,
    inteligencia: -4, sabedoria: 1, carisma: -2,
    fortitude: 16, reflexos: 10, vontade: 5,
    deslocamento: '12m',
    attacks: [
      { name: 'Mordida', attackBonus: 16, damage: '1d8+5' },
      { name: 'Duas garras', attackBonus: 15, damage: '1d6+5' },
    ],
    specialAbilities: [
      'Agarrar Aprimorado (livre): em acerto de garra, manobra agarrar (teste +18).',
      'Faro, visão no escuro.',
    ],
    treasureXp: 4000,
    bookPage: 293,
  },
  {
    id: 'troll',
    name: 'Troll',
    nd: 5,
    tipo: 'monstro',
    size: 'grande',
    hp: 165,
    defesa: 23,
    forca: 6, destreza: 2, constituicao: 6,
    inteligencia: -2, sabedoria: -1, carisma: -2,
    fortitude: 14, reflexos: 10, vontade: 6,
    deslocamento: '9m',
    attacks: [
      { name: 'Mordida', attackBonus: 17, damage: '1d8+6' },
      { name: 'Duas garras', attackBonus: 17, damage: '1d6+6' },
    ],
    specialAbilities: [
      'Cura acelerada 15 (anulada por ácido ou fogo).',
      'Dilacerar: duas garras no mesmo alvo na mesma rodada = +2d6+6 de dano.',
      'Visão no escuro.',
    ],
    treasureXp: 5000,
    bookPage: 309,
  },
  {
    id: 'manticora',
    name: 'Mantícora',
    nd: 6,
    tipo: 'monstro',
    size: 'grande',
    hp: 240,
    defesa: 26,
    forca: 7, destreza: 2, constituicao: 5,
    inteligencia: -2, sabedoria: 1, carisma: -1,
    fortitude: 18, reflexos: 7, vontade: 12,
    deslocamento: '9m, voo 15m',
    attacks: [
      { name: 'Mordida', attackBonus: 18, damage: '1d10+12' },
      { name: 'Duas garras', attackBonus: 18, damage: '1d8+12' },
    ],
    specialAbilities: [
      'Espinhos (movimento, recarga mov): 1d4 espinhos a médio, cada 1d8+7 perfuração (Ref CD 22 reduz à metade).',
      'Faro, visão no escuro.',
    ],
    treasureXp: 6000,
    bookPage: 287,
  },
  {
    id: 'dragao-jovem',
    name: 'Dragão Jovem',
    nd: 7,
    tipo: 'monstro',
    size: 'grande',
    hp: 320,
    defesa: 32,
    forca: 7, destreza: 2, constituicao: 6,
    inteligencia: 2, sabedoria: 2, carisma: 2,
    fortitude: 20, reflexos: 9, vontade: 12,
    deslocamento: '12m, voo 18m',
    attacks: [
      { name: 'Mordida', attackBonus: 25, damage: '2d6+14', special: 'crítico 19' },
      { name: 'Duas garras', attackBonus: 25, damage: '1d8+14', special: 'crítico 19' },
    ],
    specialAbilities: [
      'Sopro (padrão, recarga mov): cone 9m, 6d12 fogo + em chamas (Ref CD 25 reduz à metade e evita).',
      'Varrer (livre): 1×/rod, reduzir alvo a 0 PV concede ataque adicional contra adjacente.',
      'Redução de dano 5; imune fogo; vulnerável frio; resistência a magia +2.',
      'Metamorfose Dracônica; percepção às cegas.',
    ],
    treasureXp: 7000,
    bookPage: 311,
  },
  {
    id: 'golem-de-ferro',
    name: 'Golem de Ferro',
    nd: 10,
    tipo: 'construto',
    size: 'grande',
    hp: 400,
    defesa: 36,
    forca: 12, destreza: -1, constituicao: 10,
    inteligencia: 0, sabedoria: 0, carisma: -5,
    fortitude: 24, reflexos: 14, vontade: 11,
    deslocamento: '9m',
    attacks: [{ name: 'Duas pancadas', attackBonus: 30, damage: '2d10+25' }],
    specialAbilities: [
      'Imunidade a Magia (exceções: eletricidade deixa lento 1d6 rod; fogo remove lento e cura 1 PV por 3 de dano).',
      'Sopro (movimento, recarga, veneno): cubo 3m, 6d12 PV + enjoado (Fort CD 30 reduz à metade e evita).',
      'Redução de dano 10; imunidades de construto.',
    ],
    treasureXp: 10000,
    bookPage: 288,
  },
  {
    id: 'dragao-adulto',
    name: 'Dragão Adulto',
    nd: 11,
    tipo: 'monstro',
    size: 'enorme',
    hp: 600,
    defesa: 42,
    forca: 11, destreza: 1, constituicao: 8,
    inteligencia: 4, sabedoria: 4, carisma: 4,
    fortitude: 24, reflexos: 11, vontade: 18,
    deslocamento: '12m, voo 24m',
    attacks: [
      { name: 'Mordida', attackBonus: 35, damage: '4d10+25', special: 'crítico 18' },
      { name: 'Duas garras', attackBonus: 35, damage: '3d10+25', special: 'crítico 18' },
    ],
    specialAbilities: [
      'Sopro (padrão, recarga mov): cone 12m, 12d12 fogo + em chamas (Ref CD 32 reduz à metade e evita).',
      'Aura Aterradora (raio 90m, Von CD 31).',
      'Magia arcano 11º (CD 32): Campo de Força, Curar Ferimentos, Dissipar Magia, Enfeitiçar, Globo de Invulnerabilidade, Velocidade.',
      'Varrer, Metamorfose Dracônica, percepção às cegas, RD 10, imune fogo, vulnerável frio, resistência a magia +3.',
    ],
    treasureXp: 11000,
    bookPage: 311,
  },
  {
    id: 'hidra',
    name: 'Hidra',
    nd: 11,
    tipo: 'monstro',
    size: 'enorme',
    hp: 550,
    defesa: 35,
    forca: 10, destreza: 2, constituicao: 8,
    inteligencia: -4, sabedoria: 1, carisma: -2,
    fortitude: 24, reflexos: 18, vontade: 9,
    deslocamento: '9m, natação 9m',
    attacks: [{ name: 'Cinco mordidas', attackBonus: 34, damage: '3d6+16' }],
    specialAbilities: [
      'Cura acelerada 100.',
      'Cortar Cabeças: corte que cause dano à hidra (CD 24) nasce duas cabeças no lugar.',
      'Faro, visão no escuro.',
    ],
    treasureXp: 11000,
    bookPage: 306,
  },
  {
    id: 'vampiro',
    name: 'Vampiro',
    nd: 12,
    tipo: 'morto-vivo',
    size: 'medio',
    hp: 550,
    defesa: 45,
    forca: 6, destreza: 5, constituicao: 5,
    inteligencia: 3, sabedoria: 3, carisma: 6,
    fortitude: 12, reflexos: 26, vontade: 20,
    deslocamento: '18m, escalar 18m',
    attacks: [
      {
        name: 'Espada longa x2',
        attackBonus: 36,
        damage: '2d8+25 mais 2d10 trevas',
        special: 'crítico 17',
      },
      { name: 'Garra', attackBonus: 36, damage: '2d6+25 mais 2d10 trevas' },
    ],
    specialAbilities: [
      'Dominação Vampírica (padrão): humanoide a curto fica confuso/enfeitiçado/fascinado ou perde memórias (Von CD 29 evita); 1×/cena por alvo.',
      'Drenar Sangue: criatura agarrada perde 6d6 perfuração; vampiro cura igual.',
      'Forma de Morcego; Presença Majestosa (Von CD 29).',
      'Cura acelerada 10; RD 10/luz; sensibilidade ao sol (ofuscado, perde 6d6 PV/rod sob luz solar).',
    ],
    treasureXp: 12000,
    bookPage: 299,
  },
  {
    id: 'dragao-rei',
    name: 'Dragão-Rei',
    nd: 20,
    tipo: 'monstro',
    size: 'colossal',
    hp: 1400,
    defesa: 62,
    forca: 15, destreza: 1, constituicao: 12,
    inteligencia: 8, sabedoria: 8, carisma: 8,
    fortitude: 34, reflexos: 20, vontade: 28,
    deslocamento: '12m, voo 36m',
    attacks: [
      { name: 'Mordida', attackBonus: 55, damage: '6d20+50', special: 'crítico 16' },
      { name: 'Duas garras', attackBonus: 50, damage: '6d20+50', special: 'crítico 16' },
    ],
    specialAbilities: [
      'Sopro (padrão, recarga mov): cone 18m, 20d12 fogo + em chamas (Ref CD 50 reduz à metade e evita).',
      'Escamas Supremas: dano de fontes mundanas reduzido à metade.',
      'Aura Aterradora (Von CD 50).',
      'Magia arcano 20º (CD 50): Campo de Força, Controlar a Gravidade, Controlar o Tempo, Dissipar Magia, Enfeitiçar, Globo de Invulnerabilidade, Segunda Chance, Velocidade.',
      'Magia Acelerada, Fluxo de Mana, percepção às cegas, RD 20, imune fogo, vulnerável frio, resistência a magia +5.',
    ],
    treasureXp: 20000,
    bookPage: 312,
  },

  // Bestiário expansão #1 (livro p286-298) — grupos Masmorras / Ermos /
  // Bandidos-Guardas-Centauros-Gnolls / Puristas / Reino dos Mortos.

  // ── Masmorras ────────────────────────────────────────────────
  {
    id: 'glop',
    name: 'Glop',
    nd: 0.25,
    tipo: 'monstro',
    size: 'pequeno',
    hp: 10,
    defesa: 10,
    forca: 0, destreza: 0, constituicao: 0,
    inteligencia: -5, sabedoria: -5, carisma: -5,
    fortitude: 0, reflexos: 2, vontade: -5,
    deslocamento: '9m (6q)',
    attacks: [
      { name: 'Pancada', attackBonus: 7, damage: '1d4 mais 1d4 ácido' },
    ],
    specialAbilities: [
      'Percepção às cegas.',
      'Imunidade a ácido.',
    ],
    treasureXp: 250,
    bookPage: 286,
  },
  {
    id: 'rato-gigante',
    name: 'Rato Gigante',
    nd: 0.25,
    tipo: 'animal',
    size: 'pequeno',
    hp: 3,
    defesa: 12,
    forca: 0, destreza: 2, constituicao: 1,
    inteligencia: -4, sabedoria: 1, carisma: -3,
    fortitude: 0, reflexos: 3, vontade: -2,
    deslocamento: '12m (8q), escalar 6m (4q)',
    attacks: [
      { name: 'Mordida', attackBonus: 7, damage: '1d4+3 mais doença' },
    ],
    specialAbilities: [
      'Faro; visão na penumbra.',
      'Doença (mordida): infecção do esgoto — Fortitude para evitar (p318).',
    ],
    treasureXp: 250,
    bookPage: 286,
  },
  {
    id: 'orc-chefe',
    name: 'Orc Chefe',
    nd: 2,
    tipo: 'humanoide',
    size: 'medio',
    hp: 66,
    defesa: 19,
    forca: 5, destreza: 1, constituicao: 4,
    inteligencia: 0, sabedoria: 0, carisma: 0,
    fortitude: 13, reflexos: 7, vontade: 2,
    deslocamento: '9m (6q)',
    attacks: [
      { name: 'Machado de batalha', attackBonus: 11, damage: '1d8+12', special: 'crítico x3' },
    ],
    specialAbilities: [
      'Urro Selvagem (movimento): +2 em ataques e dano até o fim da cena; incompatível com concentração.',
      'Sensibilidade à luz: ofuscado sob luz solar.',
      'Perícias: Intimidação +4, Sobrevivência +5 (+7 em subterrâneos).',
    ],
    treasureXp: 2000,
    bookPage: 286,
  },
  {
    id: 'orc-mutante',
    name: 'Orc Mutante',
    nd: 5,
    tipo: 'humanoide',
    size: 'medio',
    hp: 55,
    defesa: 22,
    forca: 6, destreza: 2, constituicao: 4,
    inteligencia: -2, sabedoria: -2, carisma: -2,
    fortitude: 15, reflexos: 11, vontade: 7,
    deslocamento: '9m (6q)',
    attacks: [
      { name: 'Machado de guerra', attackBonus: 20, damage: '1d12+18', special: 'x3' },
      { name: 'Mordida', attackBonus: 20, damage: '1d6+18' },
    ],
    specialAbilities: [
      'Terceiro Braço (livre): se acertar machado + mordida no mesmo alvo em uma rodada, causa 1d6+9 corte extra.',
      'Sensibilidade à luz: ofuscado sob luz solar.',
    ],
    treasureXp: 5000,
    bookPage: 286,
  },
  {
    id: 'guerreiro-chifres',
    name: 'Guerreiro de Chifres',
    nd: 3,
    tipo: 'espirito',
    size: 'medio',
    hp: 100,
    defesa: 21,
    forca: 5, destreza: 3, constituicao: 4,
    inteligencia: -2, sabedoria: 1, carisma: -1,
    fortitude: 13, reflexos: 11, vontade: 9,
    deslocamento: '9m (6q)',
    attacks: [
      { name: 'Machado de guerra', attackBonus: 14, damage: '1d12+16', special: 'x3' },
      { name: 'Chifres', attackBonus: 14, damage: '2d6+10 impacto' },
    ],
    specialAbilities: [
      'Marrada (completa): investida com machado + chifres, ambos com +2 no mesmo alvo.',
      'Imunidade a ácido e veneno; redução de dano 5; redução de fogo e frio 10.',
      'Perícias: Atletismo +8, Intimidação +4.',
    ],
    treasureXp: 3000,
    bookPage: 287,
  },
  {
    id: 'centopeia-dragao',
    name: 'Centopeia-Dragão',
    nd: 7,
    tipo: 'monstro',
    size: 'enorme',
    hp: 275,
    defesa: 27,
    forca: 11, destreza: 3, constituicao: 9,
    inteligencia: -4, sabedoria: 1, carisma: 0,
    fortitude: 20, reflexos: 14, vontade: 9,
    deslocamento: '15m (10q), escavar 6m (4q)',
    attacks: [
      { name: 'Mordida', attackBonus: 24, damage: '2d8+18 mais 2d6 fogo' },
    ],
    specialAbilities: [
      'Agarrar Aprimorado (livre): após mordida, agarrar +29.',
      'Aura de Calor (enfurecida): 4d6+9 fogo em raio 9m no início do turno.',
      'Engolir (padrão): agarrada Média ou menor → 2d6+18 impacto + 4d6+9 fogo/rodada dentro.',
      'Imunidade a condição caído; redução de fogo 10.',
    ],
    treasureXp: 7000,
    bookPage: 287,
  },

  // ── Ermos ─────────────────────────────────────────────────────
  {
    id: 'bandido',
    name: 'Bandido',
    nd: 0.25,
    tipo: 'humanoide',
    size: 'medio',
    hp: 6,
    defesa: 13,
    forca: 1, destreza: 2, constituicao: 1,
    inteligencia: 0, sabedoria: -1, carisma: 0,
    fortitude: 1, reflexos: 3, vontade: -1,
    deslocamento: '9m (6q)',
    attacks: [
      { name: 'Clava', attackBonus: 7, damage: '1d6+3' },
    ],
    specialAbilities: [
      'Perícias: Furtividade +5.',
    ],
    treasureXp: 250,
    bookPage: 289,
  },
  {
    id: 'chefe-bandido',
    name: 'Chefe Bandido',
    nd: 1,
    tipo: 'humanoide',
    size: 'medio',
    hp: 30,
    defesa: 16,
    forca: 3, destreza: 2, constituicao: 3,
    inteligencia: 0, sabedoria: 0, carisma: 1,
    fortitude: 5, reflexos: 8, vontade: 3,
    deslocamento: '9m',
    attacks: [
      { name: 'Espada curta', attackBonus: 9, damage: '1d6+5', special: '19' },
      { name: 'Adaga (à distância)', attackBonus: 7, damage: '1d4+3', special: '19' },
    ],
    specialAbilities: [
      'Ataque Furtivo: +2d6 dano 1×/rodada contra desprevenidos ou flanqueados (curto ou corpo a corpo).',
      'Perícias: Furtividade +7, Intimidação +6.',
    ],
    treasureXp: 1000,
    bookPage: 289,
  },
  {
    id: 'guarda-cidade',
    name: 'Guarda de Cidade',
    nd: 0.5,
    tipo: 'humanoide',
    size: 'medio',
    hp: 8,
    defesa: 15,
    forca: 2, destreza: 1, constituicao: 2,
    inteligencia: 0, sabedoria: 0, carisma: 0,
    fortitude: 5, reflexos: 2, vontade: 1,
    deslocamento: '9m (6q)',
    attacks: [
      { name: 'Maça', attackBonus: 7, damage: '1d8+5' },
    ],
    specialAbilities: [
      'Perícias: Atletismo +5.',
    ],
    treasureXp: 500,
    bookPage: 289,
  },
  {
    id: 'sargento-guarda',
    name: 'Sargento da Guarda',
    nd: 1,
    tipo: 'humanoide',
    size: 'medio',
    hp: 28,
    defesa: 17,
    forca: 3, destreza: 1, constituicao: 2,
    inteligencia: 0, sabedoria: 0, carisma: 1,
    fortitude: 9, reflexos: 4, vontade: 3,
    deslocamento: '6m (4q)',
    attacks: [
      { name: 'Maça', attackBonus: 10, damage: '1d8+10' },
      { name: 'Besta leve (à distância)', attackBonus: 9, damage: '1d8+5', special: '19' },
    ],
    specialAbilities: [
      'Ordens (movimento): aliados em curto ganham +2 em perícias até o fim da cena.',
      'Perícias: Atletismo +7, Intuição +4.',
    ],
    treasureXp: 1000,
    bookPage: 289,
  },
  {
    id: 'centauro-combatente',
    name: 'Centauro Combatente',
    nd: 1,
    tipo: 'humanoide',
    size: 'grande',
    hp: 35,
    defesa: 16,
    forca: 5, destreza: 3, constituicao: 3,
    inteligencia: -2, sabedoria: 1, carisma: -2,
    fortitude: 9, reflexos: 2, vontade: 5,
    deslocamento: '12m (8q)',
    attacks: [
      { name: 'Tacape', attackBonus: 9, damage: '1d12+5' },
      { name: 'Cascos', attackBonus: 9, damage: '1d8+5' },
      { name: 'Arco longo (à distância)', attackBonus: 7, damage: '1d10+5', special: 'x3' },
    ],
    specialAbilities: [
      'Investida Poderosa: +1d12 dano na investida com tacape.',
      'Medo de Altura: abalado se adjacente a queda de 3m+.',
      'Perícias: Sobrevivência +5.',
    ],
    treasureXp: 1000,
    bookPage: 290,
  },
  {
    id: 'centauro-xama',
    name: 'Centauro Xamã',
    nd: 3,
    tipo: 'humanoide',
    size: 'grande',
    hp: 35,
    defesa: 21,
    forca: 4, destreza: 1, constituicao: 3,
    inteligencia: -1, sabedoria: 4, carisma: 0,
    fortitude: 9, reflexos: 4, vontade: 15,
    deslocamento: '12m (8q)',
    attacks: [
      { name: 'Bordão', attackBonus: 11, damage: '1d8+4' },
      { name: 'Cascos', attackBonus: 11, damage: '1d8+4' },
    ],
    specialAbilities: [
      'Magias (clérigo 3º de Allihanna, CD 17): Armamento da Natureza, Controlar Plantas, Curar Ferimentos.',
      'Voz Divina sempre ativa (falar com animais).',
      'PM 20; Medo de Altura.',
      'Perícias: Religião +8, Sobrevivência +10.',
    ],
    treasureXp: 3000,
    bookPage: 290,
  },
  {
    id: 'gnoll-saqueador',
    name: 'Gnoll Saqueador',
    nd: 1,
    tipo: 'humanoide',
    size: 'medio',
    hp: 15,
    defesa: 15,
    forca: 3, destreza: 2, constituicao: 3,
    inteligencia: -2, sabedoria: 1, carisma: -1,
    fortitude: 7, reflexos: 7, vontade: 1,
    deslocamento: '9m (6q)',
    attacks: [
      { name: 'Lança', attackBonus: 10, damage: '1d6+4' },
      { name: 'Mordida', attackBonus: 10, damage: '1d6+4' },
      { name: 'Arco curto (à distância)', attackBonus: 9, damage: '1d6+3', special: 'x3' },
    ],
    specialAbilities: [
      'Faro.',
    ],
    treasureXp: 1000,
    bookPage: 290,
  },
  {
    id: 'gnoll-filibusteiro',
    name: 'Gnoll Filibusteiro',
    nd: 2,
    tipo: 'humanoide',
    size: 'medio',
    hp: 60,
    defesa: 19,
    forca: 3, destreza: 4, constituicao: 3,
    inteligencia: -1, sabedoria: 2, carisma: -1,
    fortitude: 7, reflexos: 11, vontade: 4,
    deslocamento: '9m (6q)',
    attacks: [
      { name: 'Espada curta', attackBonus: 11, damage: '1d6+4', special: '19' },
      { name: 'Mordida', attackBonus: 11, damage: '1d6+4' },
      { name: 'Mosquete (à distância)', attackBonus: 12, damage: '2d8+9', special: '19/x3' },
    ],
    specialAbilities: [
      'Recarga Rápida: mosquete recarrega como movimento.',
      'Faro.',
    ],
    treasureXp: 2000,
    bookPage: 291,
  },
  {
    id: 'gorlogg',
    name: 'Gorlogg',
    nd: 1,
    tipo: 'animal',
    size: 'grande',
    hp: 36,
    defesa: 16,
    forca: 5, destreza: 2, constituicao: 5,
    inteligencia: -4, sabedoria: 2, carisma: -4,
    fortitude: 8, reflexos: 5, vontade: 3,
    deslocamento: '12m (8q)',
    attacks: [
      { name: 'Mordida', attackBonus: 9, damage: '2d6+8', special: 'x3' },
    ],
    specialAbilities: [
      'Agarrar Aprimorado (livre): após mordida, agarrar +13.',
      'Perícias: Atletismo +9.',
    ],
    treasureXp: 1000,
    bookPage: 291,
  },
  {
    id: 'trog',
    name: 'Trog',
    nd: 1,
    tipo: 'humanoide',
    size: 'medio',
    hp: 11,
    defesa: 16,
    forca: 3, destreza: 1, constituicao: 3,
    inteligencia: -2, sabedoria: 0, carisma: -1,
    fortitude: 10, reflexos: 5, vontade: 1,
    deslocamento: '9m (6q)',
    attacks: [
      { name: 'Lança', attackBonus: 11, damage: '1d6+5' },
      { name: 'Mordida', attackBonus: 11, damage: '1d6+5' },
      { name: 'Azagaia (à distância)', attackBonus: 9, damage: '1d6+5' },
    ],
    specialAbilities: [
      'Mau Cheiro (padrão): enjoados por 1d6 rodadas em curto (Fort CD 15). Veneno.',
      'Sangue Frio: +1 dano por dado de frio recebido.',
      'Perícias: Furtividade +7 (camaleônico).',
    ],
    treasureXp: 1000,
    bookPage: 292,
  },
  {
    id: 'lobo-das-cavernas',
    name: 'Lobo-das-Cavernas',
    nd: 2,
    tipo: 'animal',
    size: 'grande',
    hp: 73,
    defesa: 19,
    forca: 6, destreza: 2, constituicao: 5,
    inteligencia: -4, sabedoria: 2, carisma: -2,
    fortitude: 11, reflexos: 7, vontade: 6,
    deslocamento: '15m (10q)',
    attacks: [
      { name: 'Mordida', attackBonus: 13, damage: '2d6+10' },
    ],
    specialAbilities: [
      'Derrubar (livre) após mordida bem-sucedida (teste +15).',
      'Táticas de Alcateia: +2 no ataque e dano ao flanquear.',
      'Faro; visão na penumbra.',
      'Perícias: Sobrevivência +11.',
    ],
    treasureXp: 2000,
    bookPage: 292,
  },
  {
    id: 'cao-do-inferno',
    name: 'Cão do Inferno',
    nd: 3,
    tipo: 'espirito',
    size: 'grande',
    hp: 95,
    defesa: 21,
    forca: 5, destreza: 3, constituicao: 4,
    inteligencia: -2, sabedoria: 1, carisma: -2,
    fortitude: 11, reflexos: 9, vontade: 7,
    deslocamento: '12m (8q)',
    attacks: [
      { name: 'Mordida', attackBonus: 14, damage: '2d6+6 mais 2d6 fogo' },
    ],
    specialAbilities: [
      'Sopro (padrão): cone 6m, 4d6+4 fogo (Ref CD 17 metade). Recarga movimento.',
      'Imunidade a fogo; redução de dano 10/mágico; vulnerabilidade a frio.',
      'Perícias: Atletismo +9.',
    ],
    treasureXp: 3000,
    bookPage: 292,
  },
  {
    id: 'serpe',
    name: 'Serpe',
    nd: 5,
    tipo: 'monstro',
    size: 'grande',
    hp: 200,
    defesa: 24,
    forca: 6, destreza: 1, constituicao: 6,
    inteligencia: -2, sabedoria: 1, carisma: -1,
    fortitude: 16, reflexos: 10, vontade: 7,
    deslocamento: '9m (6q), voo 18m (12q)',
    attacks: [
      { name: 'Mordida', attackBonus: 17, damage: '2d6+12' },
      { name: 'Ferrão', attackBonus: 17, damage: '1d8+12 mais veneno' },
    ],
    specialAbilities: [
      'Agarrar Aprimorado (livre): após mordida, agarrar +19.',
      'Veneno (ferrão): 1d12 PV/rodada por 3 rodadas (Fort CD 20 reduz a 1 rodada).',
      'Imunidade a paralisia.',
    ],
    treasureXp: 5000,
    bookPage: 293,
  },

  // ── Puristas ─────────────────────────────────────────────────
  {
    id: 'recruta-purista',
    name: 'Recruta Purista',
    nd: 0.5,
    tipo: 'humanoide',
    size: 'medio',
    hp: 10,
    defesa: 16,
    forca: 2, destreza: 1, constituicao: 2,
    inteligencia: -1, sabedoria: -1, carisma: 0,
    fortitude: 6, reflexos: 2, vontade: 0,
    deslocamento: '6m (4q)',
    attacks: [
      { name: 'Alabarda', attackBonus: 8, damage: '1d10+5', special: 'x3' },
    ],
    specialAbilities: [
      'Lutar em Formação: +2 em ataque e Defesa se adjacente a aliado com o mesmo poder.',
      'Ódio Puro: +5 Vontade sob ordens de superior, +2 dano contra humanoides não humanos.',
    ],
    treasureXp: 500,
    bookPage: 294,
  },
  {
    id: 'soldado-purista',
    name: 'Soldado Purista',
    nd: 1,
    tipo: 'humanoide',
    size: 'medio',
    hp: 20,
    defesa: 20,
    forca: 3, destreza: 1, constituicao: 3,
    inteligencia: 0, sabedoria: -1, carisma: 0,
    fortitude: 10, reflexos: 4, vontade: 1,
    deslocamento: '6m (4q)',
    attacks: [
      { name: 'Espada bastarda', attackBonus: 9, damage: '1d10+9', special: '19' },
      { name: 'Besta pesada (à distância)', attackBonus: 7, damage: '1d12+4', special: '19' },
    ],
    specialAbilities: [
      'Lutar em Formação: +2 em ataque e Defesa se adjacente a aliado com o mesmo poder.',
      'Ódio Puro: +5 Vontade sob ordens de superior, +2 dano contra humanoides não humanos.',
    ],
    treasureXp: 1000,
    bookPage: 294,
  },
  {
    id: 'sargento-mor',
    name: 'Sargento-Mor',
    nd: 3,
    tipo: 'humanoide',
    size: 'medio',
    hp: 105,
    defesa: 24,
    forca: 4, destreza: 1, constituicao: 4,
    inteligencia: 0, sabedoria: 0, carisma: 0,
    fortitude: 14, reflexos: 9, vontade: 5,
    deslocamento: '6m (4q)',
    attacks: [
      { name: 'Espada bastarda', attackBonus: 14, damage: '1d12+15', special: '19' },
      { name: 'Besta pesada (à distância)', attackBonus: 12, damage: '1d12+10', special: '19' },
    ],
    specialAbilities: [
      'Lutar em Formação: +2 em ataque e Defesa se adjacente a aliado com o mesmo poder.',
      'Varrer (livre): ao reduzir alvo corpo a corpo a 0 PV, ataque adicional em outra criatura adjacente.',
      'Ódio Puro: +5 Vontade sob ordens de superior.',
    ],
    treasureXp: 3000,
    bookPage: 294,
  },
  {
    id: 'capelao-guerra',
    name: 'Capelão de Guerra',
    nd: 4,
    tipo: 'humanoide',
    size: 'medio',
    hp: 105,
    defesa: 21,
    forca: 4, destreza: 1, constituicao: 4,
    inteligencia: 0, sabedoria: 3, carisma: -1,
    fortitude: 10, reflexos: 4, vontade: 16,
    deslocamento: '6m (4q)',
    attacks: [
      { name: 'Martelo de guerra', attackBonus: 14, damage: '1d8+15', special: 'x3' },
    ],
    specialAbilities: [
      'PM 25.',
      'Magias (clérigo 5º, CD 18): Arma Mágica, Bênção, Curar Ferimentos, Soco de Arsenal.',
      'Imunidade a medo (via cânticos); Ódio Puro.',
      'Perícias: Misticismo +5, Religião +7.',
    ],
    treasureXp: 4000,
    bookPage: 295,
  },
  {
    id: 'capitao-baluarte',
    name: 'Capitão-Baluarte',
    nd: 5,
    tipo: 'humanoide',
    size: 'medio',
    hp: 115,
    defesa: 33,
    forca: 5, destreza: 0, constituicao: 4,
    inteligencia: 1, sabedoria: 3, carisma: 4,
    fortitude: 15, reflexos: 4, vontade: 13,
    deslocamento: '6m (4q)',
    attacks: [
      { name: 'Espada longa', attackBonus: 17, damage: '1d8+8', special: '19' },
    ],
    specialAbilities: [
      'Comandar (padrão): aliados em curto +4 em ataque e dano por 1 rodada.',
      'Formação Invencível: aliados em curto +2 Defesa.',
      'Ódio Puro.',
      'Perícias: Cavalgar +4, Guerra +7, Nobreza +7.',
    ],
    treasureXp: 5000,
    bookPage: 295,
  },
  {
    id: 'cavaleiro-leopardo-sangrento',
    name: 'Cavaleiro do Leopardo Sangrento',
    nd: 9,
    tipo: 'humanoide',
    size: 'medio',
    hp: 270,
    defesa: 36,
    forca: 5, destreza: 2, constituicao: 5,
    inteligencia: 3, sabedoria: 0, carisma: 2,
    fortitude: 21, reflexos: 11, vontade: 17,
    deslocamento: '9m (6q)',
    attacks: [
      { name: 'Espada bastarda', attackBonus: 28, damage: '3d6+15', special: '19' },
    ],
    specialAbilities: [
      'PM 58; Imunidade a medo.',
      'Cavaleiro Místico (mago 9º, CD 28): pode conjurar de armadura sem teste; 1×/rodada, magia livre após ataque corpo a corpo.',
      'Magias: Concentração de Combate, Dissipar Magia, Pele de Pedra, Toque Chocante, Velocidade.',
      'Ódio Puro.',
      'Perícias: Furtividade +8, Intimidação +17, Misticismo +19.',
    ],
    treasureXp: 9000,
    bookPage: 295,
  },
  {
    id: 'colosso-supremo',
    name: 'Colosso Supremo',
    nd: 14,
    tipo: 'construto',
    size: 'colossal',
    hp: 675,
    defesa: 46,
    forca: 15, destreza: -1, constituicao: 10,
    inteligencia: -5, sabedoria: -5, carisma: -5,
    fortitude: 31, reflexos: 19, vontade: 20,
    deslocamento: '12m (8q)',
    attacks: [
      { name: 'Espada titânica', attackBonus: 39, damage: '4d12+30', special: '19' },
    ],
    specialAbilities: [
      'Balistas (livre): dois canhões (+39, 6d8 perfuração, crítico 19, alcance médio).',
      'Fumos Tóxicos: 4d6 PV + enjoado em curto (Fort CD 38). Veneno.',
      'Jato de Chamas (movimento): cone 12m, 8d8+10 fogo (Ref CD 38 metade).',
      'Passar por Cima (completa): atropela criaturas Grandes ou menores por 6d8+15 impacto (Ref CD 38 metade).',
      'Varrer (livre); Cura acelerada 20; RD 10; resistência a magia +5.',
      'Goblins Consertadores: fonte da cura acelerada; imunes a dano, afetáveis por efeitos mentais (Von +3).',
    ],
    treasureXp: 14000,
    bookPage: 296,
  },

  // ── Reino dos Mortos ─────────────────────────────────────────
  {
    id: 'turba-zumbi',
    name: 'Turba Zumbi',
    nd: 2,
    tipo: 'morto-vivo',
    size: 'grande',
    hp: 100,
    defesa: 11,
    forca: 3, destreza: -1, constituicao: 3,
    inteligencia: -5, sabedoria: -1, carisma: 0,
    fortitude: 5, reflexos: 1, vontade: 1,
    deslocamento: '6m (4q)',
    attacks: [
      { name: 'Mordida (bando)', attackBonus: 17, damage: '2d6+12' },
    ],
    specialAbilities: [
      'Bando: dano dobrado ao superar Defesa em 10+; metade em erro. Imune a manobras e efeitos monoalvo; sofre 50% a mais de área.',
      'Fraqueza Zumbi: dobro em críticos ou ataques ao cérebro (Defesa 21).',
      'Visão no escuro; traços de morto-vivo.',
    ],
    treasureXp: 2000,
    bookPage: 297,
  },
  {
    id: 'esqueleto-elite',
    name: 'Esqueleto de Elite',
    nd: 4,
    tipo: 'morto-vivo',
    size: 'medio',
    hp: 60,
    defesa: 25,
    forca: 6, destreza: 4, constituicao: 2,
    inteligencia: 0, sabedoria: 0, carisma: -5,
    fortitude: 4, reflexos: 10, vontade: 16,
    deslocamento: '6m (4q)',
    attacks: [
      { name: 'Espada longa', attackBonus: 18, damage: '2d8+15 mais 2d8 trevas', special: '19' },
    ],
    specialAbilities: [
      'Redução de corte, frio e perfuração 5.',
      'Traços de morto-vivo (imunidade a cansaço/metabólicos/veneno).',
    ],
    treasureXp: 4000,
    bookPage: 297,
  },
  {
    id: 'aparicao',
    name: 'Aparição',
    nd: 5,
    tipo: 'morto-vivo',
    size: 'medio',
    hp: 110,
    defesa: 23,
    forca: 0, destreza: 6, constituicao: 0,
    inteligencia: 0, sabedoria: 5, carisma: 2,
    fortitude: 5, reflexos: 17, vontade: 11,
    deslocamento: 'voo 18m (12q)',
    attacks: [
      { name: 'Toque drenante', attackBonus: 18, damage: '3d8+6 trevas' },
    ],
    specialAbilities: [
      'Incorpórea.',
      'Toque Drenante: alvo vivo faz Fort CD 21 ou fica fraca (cumulativo) e aparição ganha 20 PV temporários.',
      'Vulnerabilidade à Luz do Dia: enfraquecida sob luz solar.',
      'Perícias: Furtividade +15.',
    ],
    treasureXp: 5000,
    bookPage: 298,
  },
  {
    id: 'necromante',
    name: 'Necromante',
    nd: 7,
    tipo: 'humanoide',
    size: 'medio',
    hp: 180,
    defesa: 23,
    forca: 0, destreza: 2, constituicao: 1,
    inteligencia: 5, sabedoria: 0, carisma: 0,
    fortitude: 7, reflexos: 14, vontade: 20,
    deslocamento: '12m (8q)',
    attacks: [
      { name: 'Adaga', attackBonus: 22, damage: '1d4 mais 1d8 trevas', special: '19' },
    ],
    specialAbilities: [
      'PM 55.',
      'Erguer-se! (completa, 5 PM): 6 mortos-vivos servos com deslocamento 9m; padrão para 2d8 trevas em criatura adjacente.',
      'Sacrificar Servo (reação): 1×/rodada, redirecionar dano para servo.',
      'Magias (mago 7º, CD 26; 28 necromancia): Amedrontar, Armadura Arcana, Crânio Voador, Toque Vampírico.',
      'Perícias: Conhecimento +14, Misticismo +16.',
    ],
    treasureXp: 7000,
    bookPage: 298,
  },
  {
    id: 'falange',
    name: 'Falange',
    nd: 8,
    tipo: 'morto-vivo',
    size: 'grande',
    hp: 300,
    defesa: 25,
    forca: 6, destreza: 4, constituicao: 2,
    inteligencia: -5, sabedoria: 0, carisma: -5,
    fortitude: 6, reflexos: 12, vontade: 18,
    deslocamento: '6m',
    attacks: [
      { name: 'Espada longa (bando)', attackBonus: 28, damage: '4d8+30 mais 4d8 trevas', special: '19' },
    ],
    specialAbilities: [
      'Bando: dano dobrado ao superar Defesa em 10+; metade em erro. Imune a manobras e efeitos monoalvo; sofre 50% a mais de área.',
      'Redução de corte, frio e perfuração 5.',
      'Traços de morto-vivo.',
    ],
    treasureXp: 8000,
    bookPage: 298,
  },

  // Bestiário expansão #2 (livro p300-316) — Duyshidakk, Sszzaazitas,
  // Trolls Nobres, Dragões complementares, Tormenta.

  // ── Duyshidakk ───────────────────────────────────────────────
  {
    id: 'hobgoblin-soldado',
    name: 'Hobgoblin Soldado',
    nd: 2,
    tipo: 'humanoide',
    size: 'medio',
    hp: 18,
    defesa: 19,
    forca: 4, destreza: 2, constituicao: 2,
    inteligencia: 1, sabedoria: 0, carisma: -1,
    fortitude: 12, reflexos: 7, vontade: 3,
    deslocamento: '6m (4q)',
    attacks: [
      { name: 'Espada longa', attackBonus: 15, damage: '1d8+15', special: '19' },
      { name: 'Arco longo (à distância)', attackBonus: 11, damage: '1d8+6', special: 'x3' },
    ],
    specialAbilities: [
      'Perícias: Ofício (armeiro) +2.',
    ],
    treasureXp: 2000,
    bookPage: 300,
  },
  {
    id: 'goblin-engenhoqueiro',
    name: 'Goblin Engenhoqueiro',
    nd: 3,
    tipo: 'humanoide',
    size: 'pequeno',
    hp: 74,
    defesa: 19,
    forca: 0, destreza: 2, constituicao: 2,
    inteligencia: 3, sabedoria: -1, carisma: 0,
    fortitude: 7, reflexos: 15, vontade: 9,
    deslocamento: '9m (6q), escalada 9m (6q)',
    attacks: [
      { name: 'Adaga', attackBonus: 8, damage: '1d4+3', special: '19' },
      { name: 'Besta leve (à distância)', attackBonus: 9, damage: '1d8+3', special: '19' },
    ],
    specialAbilities: [
      'Engenhocas (padrão): teste Ofício (engenhoqueiro) CD 15 ativa uma engenhoca; CD +5 por reativação. Falha entala a engenhoca.',
      'Asa de Bambu (voo 12m até fim da cena).',
      'Cospe-Chamas (padrão): cone 9m, 6d6 fogo + em chamas (Ref CD 19 metade).',
      'Gritador: aliados em curto obrigam inimigos a −2 em ataques e dano até fim da cena.',
      'Perícias: Furtividade +7, Ofício (engenhoqueiro) +10.',
    ],
    treasureXp: 3000,
    bookPage: 300,
  },
  {
    id: 'arauto-de-thwor',
    name: 'Arauto de Thwor',
    nd: 4,
    tipo: 'humanoide',
    size: 'medio',
    hp: 135,
    defesa: 23,
    forca: 3, destreza: 1, constituicao: 3,
    inteligencia: 0, sabedoria: 4, carisma: 0,
    fortitude: 10, reflexos: 4, vontade: 16,
    deslocamento: '6m (4q)',
    attacks: [
      { name: 'Machado de guerra', attackBonus: 16, damage: '3d6+12', special: 'x3' },
    ],
    specialAbilities: [
      'O Mundo como Ele É (reação): repetir ataque errado; 1×/cena por oponente.',
      'PM 26; Magias (clérigo Thwor 4º, CD 18): Amedrontar, Curar Ferimentos, Perdição.',
      'Perícias: Intimidação +9, Religião +8.',
    ],
    treasureXp: 4000,
    bookPage: 301,
  },
  {
    id: 'hobgoblin-mago-batalha',
    name: 'Hobgoblin Mago de Batalha',
    nd: 5,
    tipo: 'humanoide',
    size: 'medio',
    hp: 120,
    defesa: 17,
    forca: 3, destreza: 1, constituicao: 3,
    inteligencia: 4, sabedoria: 0, carisma: -1,
    fortitude: 11, reflexos: 5, vontade: 17,
    deslocamento: '9m (6q)',
    attacks: [
      { name: 'Espada longa', attackBonus: 14, damage: '1d8+3', special: '19' },
    ],
    specialAbilities: [
      'Arcano de Batalha: soma Inteligência (+4) no dano de magias.',
      'PM 35; Magias (mago 5º, CD 22): Amedrontar, Armadura Arcana, Bola de Fogo (8d6+5), Concentração de Combate, Toque Vampírico.',
      'Perícias: Guerra +9, Misticismo +9, Ofício (armeiro) +11.',
    ],
    treasureXp: 5000,
    bookPage: 301,
  },
  {
    id: 'engenho-guerra-goblin',
    name: 'Engenho de Guerra Goblin',
    nd: 6,
    tipo: 'construto',
    size: 'enorme',
    hp: 246,
    defesa: 25,
    forca: 10, destreza: 0, constituicao: 7,
    inteligencia: -5, sabedoria: 0, carisma: -5,
    fortitude: 18, reflexos: 6, vontade: 12,
    deslocamento: '12m (8q)',
    attacks: [
      { name: 'Canhão elétrico (linha média)', attackBonus: 22, damage: '8d8 eletricidade', special: 'Ref CD 22 metade' },
      { name: 'Balestra ácida', attackBonus: 22, damage: '8d6+4d6 ácido' },
    ],
    specialAbilities: [
      'Arsenal de Engenhocas (padrão): rola 1d6 quatro vezes; disparos incluem Canhão elétrico, Balestra ácida, Foles (cone fogo 6d6), Lâmina giratória (+20, 4d6+10 corte), Poça de óleo (Ref CD 22), Reparos (+20 PV).',
      'Tripulação: 1d6 goblins salteadores emergem se destruído.',
      'Redução de dano 10.',
    ],
    treasureXp: 6000,
    bookPage: 302,
  },
  {
    id: 'devorador-de-medos',
    name: 'Devorador de Medos',
    nd: 8,
    tipo: 'humanoide',
    size: 'medio',
    hp: 325,
    defesa: 31,
    forca: 5, destreza: 3, constituicao: 3,
    inteligencia: 0, sabedoria: 1, carisma: 0,
    fortitude: 21, reflexos: 15, vontade: 8,
    deslocamento: '9m (6q)',
    attacks: [
      { name: 'Machado de guerra x2', attackBonus: 26, damage: '1d12+20', special: 'x3' },
    ],
    specialAbilities: [
      'Apavorar (movimento): Intimidação vs Vontade em médio — falha 4 rodadas + abalados a cena.',
      'Artesão do Medo: rola dois dados em Intimidação, usa o melhor.',
      'Medo Inebriante: metade do dano de/para criaturas abaladas/apavoradas; +bônus em rolagens quando alvo tem essas condições; PV temporários iguais à penalidade em acerto.',
      'Imunidade a medo. Faro; visão no escuro.',
      'Perícias: Furtividade +13, Intimidação +14.',
    ],
    treasureXp: 8000,
    bookPage: 303,
  },
  {
    id: 'sombra-de-thwor',
    name: 'Sombra de Thwor',
    nd: 9,
    tipo: 'humanoide',
    size: 'medio',
    hp: 295,
    defesa: 33,
    forca: 5, destreza: 5, constituicao: 5,
    inteligencia: 2, sabedoria: 2, carisma: 0,
    fortitude: 15, reflexos: 21, vontade: 9,
    deslocamento: '9m (6q)',
    attacks: [
      { name: 'Duas machadinhas', attackBonus: 27, damage: '1d6+12 mais veneno', special: 'x3' },
      { name: 'Duas machadinhas (à distância)', attackBonus: 27, damage: '1d6+12 mais veneno', special: 'x3' },
    ],
    specialAbilities: [
      'Assassinar (movimento): próximo Ataque Furtivo → dados de dano dobrados.',
      'Ataque Furtivo: +7d6 1×/rodada contra desprevenidos ou flanqueados (curto).',
      'Evasão Aprimorada; Um com as Sombras (nunca surpreendido/flanqueado; sem penalidade ao mover em Furtividade).',
      'Veneno (peçonha potente): 2d12 PV/rodada × 3 rodadas (Fort CD 26 reduz a 1).',
      'Perícias: Acrobacia +15, Atletismo +13, Furtividade +18, Intimidação +9, Ladinagem +15, Ofício (armeiro) +12.',
    ],
    treasureXp: 9000,
    bookPage: 303,
  },

  // ── Sszzaazitas ──────────────────────────────────────────────
  {
    id: 'cascavel',
    name: 'Cascavel',
    nd: 0.25,
    tipo: 'animal',
    size: 'minusculo',
    hp: 2,
    defesa: 13,
    forca: -2, destreza: 3, constituicao: 0,
    inteligencia: -5, sabedoria: 0, carisma: -4,
    fortitude: 2, reflexos: 5, vontade: -1,
    deslocamento: '6m (4q), escalar 6m (4q), natação 9m (6q)',
    attacks: [
      { name: 'Mordida', attackBonus: 7, damage: '1d4 mais veneno' },
    ],
    specialAbilities: [
      'Veneno: perde 1d12 PV × 3 rodadas (Fort CD 16 evita).',
      'Faro; visão na penumbra.',
      'Perícias: Furtividade +12.',
    ],
    treasureXp: 250,
    bookPage: 304,
  },
  {
    id: 'jiboia',
    name: 'Jiboia',
    nd: 0.5,
    tipo: 'animal',
    size: 'medio',
    hp: 14,
    defesa: 14,
    forca: 2, destreza: 3, constituicao: 1,
    inteligencia: -5, sabedoria: 1, carisma: -4,
    fortitude: 3, reflexos: 5, vontade: 0,
    deslocamento: '6m (4q), escalar 6m (4q), natação 9m (6q)',
    attacks: [
      { name: 'Mordida', attackBonus: 9, damage: '1d6+4' },
    ],
    specialAbilities: [
      'Agarrar Aprimorado (livre) após mordida (teste +9).',
      'Constrição (livre): 2d6+4 impacto no início do turno em alvo agarrado.',
      'Faro; visão na penumbra.',
      'Perícias: Furtividade +7.',
    ],
    treasureXp: 500,
    bookPage: 304,
  },
  {
    id: 'naja',
    name: 'Naja',
    nd: 1,
    tipo: 'animal',
    size: 'pequeno',
    hp: 13,
    defesa: 17,
    forca: -1, destreza: 4, constituicao: 1,
    inteligencia: -5, sabedoria: 0, carisma: -4,
    fortitude: 5, reflexos: 10, vontade: 1,
    deslocamento: '6m (4q), escalar 6m (4q), natação 6m (4q)',
    attacks: [
      { name: 'Mordida', attackBonus: 12, damage: '1d4 mais veneno' },
    ],
    specialAbilities: [
      'Veneno: 1d12 PV × 3 rodadas (Fort CD 18 reduz a 1).',
      'Faro; visão na penumbra.',
      'Perícias: Furtividade +10.',
    ],
    treasureXp: 1000,
    bookPage: 304,
  },
  {
    id: 'sucuri',
    name: 'Sucuri',
    nd: 3,
    tipo: 'animal',
    size: 'grande',
    hp: 88,
    defesa: 19,
    forca: 6, destreza: 2, constituicao: 4,
    inteligencia: -5, sabedoria: 0, carisma: -4,
    fortitude: 8, reflexos: 15, vontade: 3,
    deslocamento: '6m (4q), escalar 9m (6q), natação 9m (6q)',
    attacks: [
      { name: 'Mordida', attackBonus: 18, damage: '2d6+14' },
    ],
    specialAbilities: [
      'Agarrar Aprimorado (livre) após mordida (teste +20).',
      'Constrição (livre): 4d6+14 impacto no início do turno em alvo agarrado.',
      'Faro; visão na penumbra.',
      'Perícias: Furtividade +8.',
    ],
    treasureXp: 3000,
    bookPage: 304,
  },
  {
    id: 'nagah-guardiao',
    name: 'Nagah Guardião',
    nd: 3,
    tipo: 'humanoide',
    size: 'medio',
    hp: 45,
    defesa: 21,
    forca: 4, destreza: 3, constituicao: 2,
    inteligencia: 0, sabedoria: 0, carisma: 0,
    fortitude: 6, reflexos: 11, vontade: 9,
    deslocamento: '9m (6q)',
    attacks: [
      { name: 'Duas cimitarras', attackBonus: 14, damage: '1d6+6', special: '18' },
      { name: 'Cauda', attackBonus: 14, damage: '1d6+6' },
    ],
    specialAbilities: [
      'Fraquezas Ofídias: +1 dano por dado de frio, −5 vs Músicas de Bardo.',
      'Resistência a veneno +5.',
      'Perícias: Enganação +4, Furtividade +6.',
    ],
    treasureXp: 3000,
    bookPage: 305,
  },
  {
    id: 'nagah-mistica',
    name: 'Nagah Mística',
    nd: 6,
    tipo: 'humanoide',
    size: 'medio',
    hp: 160,
    defesa: 20,
    forca: 1, destreza: 3, constituicao: 2,
    inteligencia: 4, sabedoria: 2, carisma: 2,
    fortitude: 6, reflexos: 12, vontade: 18,
    deslocamento: '9m (6q)',
    attacks: [
      { name: 'Adaga', attackBonus: 18, damage: '1d6+6', special: '19' },
      { name: 'Cauda', attackBonus: 18, damage: '1d6+6' },
    ],
    specialAbilities: [
      'PM 35; Magia Acelerada (livre 4 PM): ação completa vira livre 1×/rodada.',
      'Magias (maga 8º, CD 24): Imagem Espelhada (5 cópias +10 Defesa), Relâmpago 8d6, Velocidade.',
      'Fraquezas Ofídias; resistência a veneno +5.',
      'Perícias: Conhecimento +10, Enganação +9, Furtividade +10, Intuição +9, Misticismo +10.',
    ],
    treasureXp: 6000,
    bookPage: 305,
  },
  {
    id: 'cultista-de-sszzaas',
    name: 'Cultista de Sszzaas',
    nd: 7,
    tipo: 'monstro',
    size: 'medio',
    hp: 160,
    defesa: 29,
    forca: 0, destreza: 2, constituicao: 0,
    inteligencia: 4, sabedoria: 4, carisma: 5,
    fortitude: 7, reflexos: 14, vontade: 20,
    deslocamento: '9m (6q)',
    attacks: [
      { name: 'Adaga certeira', attackBonus: 22, damage: '1d4+4 mais veneno', special: '19' },
    ],
    specialAbilities: [
      'Ataque Furtivo: +5d6 1×/rodada contra desprevenidos ou flanqueados (curto).',
      'Olhar Atordoante (movimento): alvo atordoado por 1 rodada (Fort CD 26 evita).',
      'Veneno (adaga): 2d12 PV × 3 rodadas (Fort CD 26 reduz a 1).',
      'PM 40; Magias (clériga 7º de Sszzaas, CD 26): Arma Mágica, Comando, Curar Ferimentos, Escuridão, Enxame de Pestes, Miasma Mefítico.',
      'Resistência a veneno +5.',
      'Perícias: Enganação +20, Intuição +20, Religião +17.',
    ],
    treasureXp: 7000,
    bookPage: 306,
  },
  {
    id: 'lagash',
    name: 'Lagash',
    nd: 13,
    tipo: 'monstro',
    size: 'enorme',
    hp: 660,
    defesa: 41,
    forca: 11, destreza: 4, constituicao: 9,
    inteligencia: -3, sabedoria: 2, carisma: -2,
    fortitude: 26, reflexos: 20, vontade: 13,
    deslocamento: '12m (8q), escalar 12m (8q), natação 12m (8q)',
    attacks: [
      { name: 'Mordida', attackBonus: 37, damage: '4d12+28 mais veneno' },
    ],
    specialAbilities: [
      'Agarrar Aprimorado (livre) após mordida (teste +42).',
      'Constrição (livre): 6d12+28 impacto/turno em alvo agarrado.',
      'Crias de Sszzaas (movimento): cospe 2d6 serpentes que causam 1d6 perfuração adjacente (For −1, Def 0, 1 PV, some ao fim da cena). Recarga movimento.',
      'Cuspe Venenoso (padrão): cone 9m, 6d12 veneno + cego 1d4 rodadas (Fort CD 35 metade + evita cegueira).',
      'Veneno (mordida): 4d12 PV × 5 rodadas (Fort CD 35 reduz a 1).',
      'Imunidade a efeitos de movimento e veneno.',
      'Perícias: Furtividade +17.',
    ],
    treasureXp: 13000,
    bookPage: 306,
  },

  // ── Trolls Nobres ────────────────────────────────────────────
  {
    id: 'finntroll-cacador',
    name: 'Finntroll Caçador',
    nd: 2,
    tipo: 'monstro',
    size: 'medio',
    hp: 65,
    defesa: 19,
    forca: 2, destreza: 3, constituicao: 3,
    inteligencia: 1, sabedoria: 2, carisma: -1,
    fortitude: 6, reflexos: 12, vontade: 4,
    deslocamento: '9m (6q)',
    attacks: [
      { name: 'Duas cimitarras', attackBonus: 12, damage: '1d6+5', special: '18' },
      { name: 'Besta pesada (à distância)', attackBonus: 12, damage: '1d12+4', special: '19' },
    ],
    specialAbilities: [
      'Marca da Presa (movimento): estudar alvo em curto → +1d8 dano até fim da cena (+2d8 se anão/elfo/humano).',
      'Natureza Vegetal: afetado por habilidades e magias contra plantas.',
      'Regeneração Vegetal (movimento): 5 PV; não cura ácido/fogo; anulada sob luz solar.',
      'Imunidade a atordoamento e metamorfose; resistência a magia +2.',
      'Sensibilidade à luz: ofuscado sob luz solar.',
      'Perícias: Furtividade +8, Sobrevivência +7.',
    ],
    treasureXp: 2000,
    bookPage: 307,
  },
  {
    id: 'finntroll-feitor',
    name: 'Finntroll Feitor',
    nd: 6,
    tipo: 'monstro',
    size: 'medio',
    hp: 155,
    defesa: 20,
    forca: 0, destreza: 3, constituicao: 3,
    inteligencia: 4, sabedoria: 0, carisma: 2,
    fortitude: 8, reflexos: 12, vontade: 16,
    deslocamento: '9m (6q)',
    attacks: [
      { name: 'Chicote', attackBonus: 18, damage: '1d3+10', special: '19' },
    ],
    specialAbilities: [
      'Açoitar (padrão): motiva subalterno em médio a +1 movimento e +2 ataques/dano.',
      'PM 35; Magias (mago 7º, CD 26; 28 encantamento): Adaga Mental, Armadura Arcana, Enfeitiçar, Desespero Esmagador, Marca da Obediência, Relâmpago.',
      'Natureza Vegetal; Regeneração Vegetal 5 (movimento).',
      'Imunidade a atordoamento e metamorfose; resistência a magia +2.',
      'Sensibilidade à luz.',
      'Perícias: Intimidação +9, Misticismo +11.',
    ],
    treasureXp: 6000,
    bookPage: 307,
  },
  {
    id: 'ganchador',
    name: 'Ganchador',
    nd: 5,
    tipo: 'monstro',
    size: 'grande',
    hp: 210,
    defesa: 26,
    forca: 6, destreza: 3, constituicao: 5,
    inteligencia: -2, sabedoria: 1, carisma: -2,
    fortitude: 15, reflexos: 11, vontade: 7,
    deslocamento: '9m (6q), escalar 9m (6q)',
    attacks: [
      { name: 'Mordida', attackBonus: 17, damage: '2d6+8' },
      { name: 'Duas garras', attackBonus: 17, damage: '1d8+8', special: '19/x3' },
    ],
    specialAbilities: [
      'Dilacerar: se ambos os ataques de garra acertarem, +2d8+8 dano.',
      'Quebrar Tudo!: +2 em ataques para quebrar (teste +21), +1d8 dano contra objetos.',
      'Percepção às cegas; sensibilidade à luz.',
    ],
    treasureXp: 5000,
    bookPage: 308,
  },
  {
    id: 'troll-das-cavernas',
    name: 'Troll das Cavernas',
    nd: 9,
    tipo: 'monstro',
    size: 'enorme',
    hp: 345,
    defesa: 29,
    forca: 9, destreza: 0, constituicao: 11,
    inteligencia: -2, sabedoria: 1, carisma: -2,
    fortitude: 21, reflexos: 15, vontade: 9,
    deslocamento: '12m (8q), escalar 9m (6q)',
    attacks: [
      { name: 'Tacape', attackBonus: 26, damage: '3d6+27' },
      { name: 'Mordida', attackBonus: 26, damage: '2d6+27' },
    ],
    specialAbilities: [
      'Golpe Avassalador (livre): arremessa alvo 1d6×1,5m; caído + 1d6 impacto por cada 1,5m se atingir obstáculo (Fort CD 28 evita).',
      'Varrer (livre): ao reduzir alvo a 0 PV corpo a corpo, ataque adicional em outra criatura adjacente.',
      'Cura acelerada 20; anulada por ácido ou fogo.',
    ],
    treasureXp: 9000,
    bookPage: 309,
  },

  // ── Dragões complementares ───────────────────────────────────
  {
    id: 'enxame-kobold',
    name: 'Enxame Kobold',
    nd: 2,
    tipo: 'monstro',
    size: 'medio',
    hp: 60,
    defesa: 17,
    forca: 0, destreza: 3, constituicao: 0,
    inteligencia: -1, sabedoria: 0, carisma: -1,
    fortitude: 7, reflexos: 13, vontade: 2,
    deslocamento: '9m (6q)',
    attacks: [
      { name: 'Caixa com Pregos (padrão)', attackBonus: 12, damage: '2d6 perfuração + atordoado 1 rod', special: 'Ref CD 16 metade + evita' },
    ],
    specialAbilities: [
      'Enxame: aglomerado que ocupa mesmo espaço que 1 personagem; 2d6 perfuração automática/turno ao personagem no espaço.',
      'Imune a manobras/efeitos monoalvo; sofre 50% a mais de área. Ataques com armas causam metade do dano.',
      'Estar dentro do enxame conta como condição ruim para lançar magias.',
      'Unidos Venceremos: +10 PV (máx 100), +1 dano por 10 PV atuais no início de cada rodada.',
    ],
    treasureXp: 2000,
    bookPage: 310,
  },
  {
    id: 'dragao-veneravel',
    name: 'Dragão Venerável',
    nd: 15,
    tipo: 'monstro',
    size: 'enorme',
    hp: 800,
    defesa: 52,
    forca: 13, destreza: 1, constituicao: 12,
    inteligencia: 6, sabedoria: 8, carisma: 6,
    fortitude: 28, reflexos: 15, vontade: 22,
    deslocamento: '12m (8q), voo 24m (16q)',
    attacks: [
      { name: 'Mordida', attackBonus: 44, damage: '4d12+40', special: '17' },
      { name: 'Duas garras', attackBonus: 44, damage: '3d12+40', special: '17' },
    ],
    specialAbilities: [
      'Aura Aterradora (Vontade CD 40).',
      'Fluxo de Mana: manter duas magias sustentadas simultaneamente por apenas ação livre.',
      'Magia Acelerada (livre 4 PM): execução completa vira livre 1×/rodada.',
      'Sopro (padrão): cone 15m, 16d12 fogo + em chamas (Ref CD 40 metade). Recarga movimento.',
      'PM 97; Magias (arcano 15º, CD 40): Campo de Força, Controlar a Gravidade, Curar Ferimentos, Enfeitiçar, Globo de Invulnerabilidade, Velocidade.',
      'Imunidade a fogo; redução de dano 15; resistência a magia +4; vulnerabilidade a frio.',
    ],
    treasureXp: 15000,
    bookPage: 311,
  },
  {
    id: 'tirano-do-terceiro',
    name: 'Tirano do Terceiro',
    nd: 10,
    tipo: 'humanoide',
    size: 'medio',
    hp: 370,
    defesa: 37,
    forca: 6, destreza: 0, constituicao: 6,
    inteligencia: 2, sabedoria: 1, carisma: 4,
    fortitude: 22, reflexos: 10, vontade: 16,
    deslocamento: '6m (4q)',
    attacks: [
      { name: 'Machado de batalha x2', attackBonus: 29, damage: '2d8+14', special: 'x3' },
      { name: 'Garra', attackBonus: 29, damage: '1d8+14' },
    ],
    specialAbilities: [
      'Dádiva Draconiana: lança magias arcanas cavalgando/de armadura sem teste de Misticismo.',
      'PM 62; Magias (mago 10º, CD 30): Bola de Fogo 12d6+5, Concentração de Combate, Velocidade.',
      'Imunidade a atordoamento e medo; redução de dano 5; resistência a magia +2.',
      'Perícias: Cavalgar +9, Intimidação +13, Misticismo +11.',
    ],
    treasureXp: 10000,
    bookPage: 313,
  },

  // ── Tormenta ─────────────────────────────────────────────────
  {
    id: 'maniaco-lefou',
    name: 'Maníaco Lefou',
    nd: 2,
    tipo: 'humanoide',
    size: 'medio',
    hp: 25,
    defesa: 18,
    forca: 3, destreza: 1, constituicao: 1,
    inteligencia: -1, sabedoria: -1, carisma: -2,
    fortitude: 12, reflexos: 7, vontade: 3,
    deslocamento: '9m (6q)',
    attacks: [
      { name: 'Machado de guerra', attackBonus: 16, damage: '1d12+15', special: 'x3' },
    ],
    specialAbilities: [
      'Frenesi Insano: ao causar ou sofrer dano, +2 cumulativo em ataques e dano até fim da cena.',
    ],
    treasureXp: 2000,
    bookPage: 314,
  },
  {
    id: 'uktril',
    name: 'Uktril',
    nd: 3,
    tipo: 'monstro',
    size: 'medio',
    hp: 45,
    defesa: 22,
    forca: 4, destreza: 2, constituicao: 2,
    inteligencia: -1, sabedoria: 1, carisma: -4,
    fortitude: 12, reflexos: 11, vontade: 6,
    deslocamento: '9m (6q)',
    attacks: [
      { name: 'Pinça', attackBonus: 16, damage: '2d6+6', special: '19' },
      { name: 'Garra', attackBonus: 16, damage: '1d6+6' },
    ],
    specialAbilities: [
      'Insanidade da Tormenta: alvo em Von perde 1d6 PM (CD 17 evita); habilidades lefou padrão.',
      'Redução de dano 10; imunidades lefou (ácido, cansaço, eletricidade, fogo, frio, luz, paralisia, metabólicos, metamorfose, trevas, veneno).',
    ],
    treasureXp: 3000,
    bookPage: 314,
  },
  {
    id: 'otyugh',
    name: 'Otyugh',
    nd: 5,
    tipo: 'monstro',
    size: 'grande',
    hp: 213,
    defesa: 24,
    forca: 5, destreza: -1, constituicao: 4,
    inteligencia: -2, sabedoria: 1, carisma: -2,
    fortitude: 17, reflexos: 11, vontade: 5,
    deslocamento: '6m (4q)',
    attacks: [
      { name: 'Dois tentáculos', attackBonus: 17, damage: '1d8+9 (alcance 4,5m)' },
      { name: 'Mordida', attackBonus: 17, damage: '1d6+9 mais doença' },
    ],
    specialAbilities: [
      'Agarrar Aprimorado (livre) após tentáculo (teste +19).',
      'Constrição (livre): 1d8+9 impacto/turno em alvo agarrado.',
      'Doença (mordida): infecção do esgoto (p318).',
      'Imunidade a doenças e venenos; redução de dano 5.',
      'Perícias: Furtividade +3 (+13 em seu refúgio).',
    ],
    treasureXp: 5000,
    bookPage: 315,
  },
  {
    id: 'geraktril',
    name: 'Geraktril',
    nd: 6,
    tipo: 'monstro',
    size: 'medio',
    hp: 240,
    defesa: 30,
    forca: 7, destreza: 5, constituicao: 3,
    inteligencia: -1, sabedoria: 3, carisma: -1,
    fortitude: 18, reflexos: 15, vontade: 6,
    deslocamento: '9m (6q)',
    attacks: [
      { name: 'Duas pinças', attackBonus: 23, damage: '3d6+10', special: '19' },
      { name: 'Garra', attackBonus: 23, damage: '1d8+10' },
    ],
    specialAbilities: [
      'Insanidade da Tormenta: alvo em Von perde 2d4 PM (CD 22 evita).',
      'Redução de dano 10; imunidades lefou padrão.',
    ],
    treasureXp: 6000,
    bookPage: 314,
  },
  {
    id: 'reishid',
    name: 'Reishid',
    nd: 8,
    tipo: 'monstro',
    size: 'medio',
    hp: 295,
    defesa: 37,
    forca: 4, destreza: 5, constituicao: 4,
    inteligencia: 1, sabedoria: 4, carisma: 1,
    fortitude: 19, reflexos: 21, vontade: 10,
    deslocamento: '9m (6q), escalar 9m (6q), voo 15m (10q)',
    attacks: [
      { name: 'Adaga da Tormenta', attackBonus: 30, damage: '1d4+18 mais 1d8 trevas', special: '19' },
      { name: 'Garra', attackBonus: 30, damage: '1d6+18' },
      { name: 'Mordida', attackBonus: 30, damage: '1d6+18 mais veneno' },
    ],
    specialAbilities: [
      'Ataque em Movimento: mover antes e depois de agredir sem exceder deslocamento total.',
      'Ataque Reflexo (reação): 1×/rodada, ataque contra alvo desprevenido que se mova para fora do alcance.',
      'Insanidade da Tormenta: alvo em Von perde 2d6 PM (CD 26 evita).',
      'Sombra Rubra: rola 2 dados em Iniciativa/Furtividade, usa o melhor.',
      'Veneno: paralisia 1d6 horas (Fort CD 26 reduz para lento por 1d6 rodadas).',
      'Redução de dano 10; imunidades lefou padrão.',
      'Perícias: Furtividade +20.',
    ],
    treasureXp: 8000,
    bookPage: 314,
  },
  {
    id: 'sacerdote-de-aharadak',
    name: 'Sacerdote de Aharadak',
    nd: 10,
    tipo: 'humanoide',
    size: 'medio',
    hp: 315,
    defesa: 38,
    forca: 4, destreza: 2, constituicao: 4,
    inteligencia: 2, sabedoria: 5, carisma: -1,
    fortitude: 16, reflexos: 10, vontade: 22,
    deslocamento: '9m (6q), voo 15m (10q)',
    attacks: [
      { name: 'Duas correntes de espinhos aberrantes', attackBonus: 30, damage: '4d6+12 mais 1d6 ácido' },
      { name: 'Mordida', attackBonus: 30, damage: '1d6+12' },
    ],
    specialAbilities: [
      'Magia Acelerada (livre 4 PM): execução completa vira livre 1×/rodada.',
      'PM 56; Magias (clérigo Aharadak 10º, CD 30): Curar Ferimentos, Perdição, Potência Divina, Silêncio.',
      'Sangue Ácido: atacante corpo a corpo sofre 10 ácido.',
      'Imunidade a confusão; redução de ácido/eletricidade/fogo/frio/luz/trevas 10.',
      'Resistência a magia divina +5.',
      'Perícias: Intimidação +9, Religião +16.',
    ],
    treasureXp: 10000,
    bookPage: 316,
  },
  {
    id: 'thuwarokk',
    name: 'Thuwarokk',
    nd: 16,
    tipo: 'monstro',
    size: 'colossal',
    hp: 900,
    defesa: 50,
    forca: 17, destreza: -1, constituicao: 10,
    inteligencia: -3, sabedoria: 0, carisma: -4,
    fortitude: 30, reflexos: 24, vontade: 16,
    deslocamento: '12m (8q)',
    attacks: [
      { name: 'Quatro pancadas', attackBonus: 48, damage: '4d12+24' },
    ],
    specialAbilities: [
      'Carapaça: metade do dano de corte/impacto/perfuração; Fortitude CD 42 reflete magia contra alvo.',
      'Insanidade da Tormenta: alvo em Von perde 2d12 PM (CD 42 evita).',
      'Jato de Ácido (movimento): linha 30m, 10d8+20 ácido (Ref CD 42 metade). Recarga movimento.',
      'Passar por Cima (completa): atropela criatura Enorme ou menor por 10d12+50 impacto (Ref CD 42 metade).',
      'Redução de dano 10; imunidades lefou padrão.',
    ],
    treasureXp: 16000,
    bookPage: 315,
  },
])

const byId = new Map(BESTIARY.map((m) => [m.id, m]))

export function monsterById(id: string): Monster | undefined {
  return byId.get(id)
}

export function monstersByTipo(tipo: MonsterTipo): readonly Monster[] {
  return BESTIARY.filter((m) => m.tipo === tipo)
}

export function monstersByNdRange(min: number, max: number): readonly Monster[] {
  return BESTIARY.filter((m) => m.nd >= min && m.nd <= max)
}

export function monstersBySize(size: MonsterSize): readonly Monster[] {
  return BESTIARY.filter((m) => m.size === size)
}
