/**
 * Bestiário — PDF Cap 7 (Ameaças), livro p282-323.
 *
 * Núcleo original: 20 monstros cobrindo NDs 1/4 → 20 selecionados para
 * representar cada tipo (humanoide, animal, monstro, morto-vivo,
 * construto) e tamanho (pequeno → colossal).
 *
 * Expansão #1 (livro p286-298): +31 monstros dos grupos Masmorras,
 * Ermos, Puristas e Reino dos Mortos. Total atual: 51.
 * Ainda pendentes (livro p299-323): Trolls Nobres, Sszzaazitas,
 * Duyshidakk, Dragões idades intermediárias, Tormenta.
 *
 * `treasureXp` segue a regra de PDF Cap 8 (Recompensas, p326):
 * `XP = ND × 1.000` (clamp dos ND fracionados em 250/500).
 */

export type MonsterTipo =
  | 'humanoide'
  | 'animal'
  | 'monstro'
  | 'morto-vivo'
  | 'construto'
  | 'espirito'
  | 'planar'

export type MonsterSize =
  | 'minusculo'
  | 'pequeno'
  | 'medio'
  | 'grande'
  | 'enorme'
  | 'colossal'

export type MonsterAttack = {
  name: string
  attackBonus: number
  damage: string
  special?: string
}

export type Monster = {
  id: string
  name: string
  nd: number
  tipo: MonsterTipo
  size: MonsterSize
  hp: number
  defesa: number
  forca: number
  destreza: number
  constituicao: number
  inteligencia: number
  sabedoria: number
  carisma: number
  fortitude: number
  reflexos: number
  vontade: number
  deslocamento: string
  attacks: readonly MonsterAttack[]
  specialAbilities: readonly string[]
  treasureXp: number
  bookPage: number
}

/** XP de tesouro derivado do ND (PDF Cap 8 p326). */
export function xpForNd(nd: number): number {
  return Math.round(nd * 1000)
}

export const BESTIARY: readonly Monster[] = Object.freeze([
  {
    id: 'goblin-salteador',
    name: 'Goblin Salteador',
    nd: 0.25,
    tipo: 'humanoide',
    size: 'pequeno',
    hp: 4,
    defesa: 13,
    forca: 0, destreza: 3, constituicao: 0,
    inteligencia: 0, sabedoria: -1, carisma: -1,
    fortitude: 2, reflexos: 3, vontade: -1,
    deslocamento: '9m, escalada 9m',
    attacks: [{ name: 'Duas adagas', attackBonus: 7, damage: '1d4', special: 'crítico 19' }],
    specialAbilities: [
      'Frenesi: +2 em ataque e dano por cada outro goblin salteador adjacente ao alvo.',
      'Visão no escuro.',
    ],
    treasureXp: 250,
    bookPage: 300,
  },
  {
    id: 'zumbi',
    name: 'Zumbi',
    nd: 0.25,
    tipo: 'morto-vivo',
    size: 'medio',
    hp: 20,
    defesa: 11,
    forca: 3, destreza: -1, constituicao: 2,
    inteligencia: 0, sabedoria: -1, carisma: 0,
    fortitude: 3, reflexos: -1, vontade: -1,
    deslocamento: '6m',
    attacks: [{ name: 'Mordida', attackBonus: 7, damage: '1d6+6' }],
    specialAbilities: [
      'Fraqueza Zumbi: dobro de dano em críticos ou ataques contra cérebro (Defesa 21).',
      'Visão no escuro; imunidades de morto-vivo (cansaço/metabólicos/trevas/veneno).',
    ],
    treasureXp: 250,
    bookPage: 297,
  },
  {
    id: 'orc-combatente',
    name: 'Orc Combatente',
    nd: 0.5,
    tipo: 'humanoide',
    size: 'medio',
    hp: 8,
    defesa: 14,
    forca: 4, destreza: 1, constituicao: 2,
    inteligencia: -1, sabedoria: -1, carisma: -1,
    fortitude: 5, reflexos: 3, vontade: 0,
    deslocamento: '9m',
    attacks: [{ name: 'Maça', attackBonus: 9, damage: '1d8+7' }],
    specialAbilities: ['Sensibilidade a Luz: ofuscado sob luz solar.', 'Visão no escuro.'],
    treasureXp: 500,
    bookPage: 286,
  },
  {
    id: 'lobo',
    name: 'Lobo',
    nd: 0.5,
    tipo: 'animal',
    size: 'medio',
    hp: 14,
    defesa: 14,
    forca: 3, destreza: 3, constituicao: 3,
    inteligencia: -4, sabedoria: 2, carisma: -2,
    fortitude: 6, reflexos: 3, vontade: 1,
    deslocamento: '15m',
    attacks: [
      { name: 'Mordida', attackBonus: 7, damage: '1d6+5', special: 'derrubar (teste +7) em acerto' },
    ],
    specialAbilities: [
      'Táticas de Alcateia: +2 ataque/+2 dano ao flanquear (total +4/+2).',
      'Faro, visão na penumbra.',
    ],
    treasureXp: 500,
    bookPage: 289,
  },
  {
    id: 'esqueleto',
    name: 'Esqueleto',
    nd: 2,
    tipo: 'morto-vivo',
    size: 'medio',
    hp: 14,
    defesa: 19,
    forca: 5, destreza: 3, constituicao: 0,
    inteligencia: 0, sabedoria: 0, carisma: -5,
    fortitude: 3, reflexos: 7, vontade: 12,
    deslocamento: '9m',
    attacks: [{ name: 'Espada longa', attackBonus: 14, damage: '2d8+12', special: 'crítico 19' }],
    specialAbilities: [
      'Redução de corte, frio e perfuração 5.',
      'Visão no escuro; imunidades de morto-vivo.',
      'Sem inteligência: segue ordens do criador.',
    ],
    treasureXp: 2000,
    bookPage: 297,
  },
  {
    id: 'aranha-gigante',
    name: 'Aranha Gigante',
    nd: 2,
    tipo: 'monstro',
    size: 'grande',
    hp: 77,
    defesa: 19,
    forca: 5, destreza: 4, constituicao: 1,
    inteligencia: -5, sabedoria: 0, carisma: -4,
    fortitude: 8, reflexos: 11, vontade: 3,
    deslocamento: '12m, escalar 12m',
    attacks: [
      {
        name: 'Mordida',
        attackBonus: 12,
        damage: '2d6+8 mais veneno',
        special: 'Veneno: fraco (Fort CD 18 evita)',
      },
    ],
    specialAbilities: [
      'Teia (padrão): teia em quadrado 3m a curto, enredando (Ref CD 18 evita). Soltar = ação completa + Força/Acrobacia CD 20.',
      'Visão no escuro.',
    ],
    treasureXp: 2000,
    bookPage: 286,
  },
  {
    id: 'gargula',
    name: 'Gárgula',
    nd: 2,
    tipo: 'construto',
    size: 'medio',
    hp: 65,
    defesa: 19,
    forca: 6, destreza: 2, constituicao: 4,
    inteligencia: -2, sabedoria: 1, carisma: -2,
    fortitude: 13, reflexos: 7, vontade: 2,
    deslocamento: '12m, voo 18m',
    attacks: [{ name: 'Duas garras', attackBonus: 12, damage: '1d6+6' }],
    specialAbilities: [
      'Imobilidade: estática parece estátua (Percepção CD 35).',
      'Redução de dano 5; imune a condição petrificado.',
      'Visão no escuro; imunidades de construto.',
    ],
    treasureXp: 2000,
    bookPage: 286,
  },
  {
    id: 'dragao-filhote',
    name: 'Dragão Filhote',
    nd: 3,
    tipo: 'monstro',
    size: 'medio',
    hp: 140,
    defesa: 22,
    forca: 4, destreza: 3, constituicao: 3,
    inteligencia: 0, sabedoria: 0, carisma: 0,
    fortitude: 15, reflexos: 3, vontade: 9,
    deslocamento: '12m, voo 18m',
    attacks: [
      { name: 'Mordida', attackBonus: 15, damage: '2d6+5' },
      { name: 'Duas garras', attackBonus: 15, damage: '1d6+5' },
    ],
    specialAbilities: [
      'Sopro (padrão, recarga mov): cone 6m, 2d12 fogo + em chamas (Ref CD 18 reduz à metade e evita).',
      'Imune a fogo; vulnerável a frio; resistência a magia +1.',
      'Visão no escuro, percepção às cegas.',
    ],
    treasureXp: 3000,
    bookPage: 310,
  },
  {
    id: 'grifo',
    name: 'Grifo',
    nd: 3,
    tipo: 'monstro',
    size: 'grande',
    hp: 110,
    defesa: 19,
    forca: 5, destreza: 4, constituicao: 3,
    inteligencia: -4, sabedoria: 2, carisma: -1,
    fortitude: 9, reflexos: 15, vontade: 4,
    deslocamento: '12m, voo 24m',
    attacks: [
      { name: 'Mordida', attackBonus: 14, damage: '2d6+5' },
      { name: 'Duas garras', attackBonus: 14, damage: '1d6+5' },
    ],
    specialAbilities: [
      'Bote (completa): investida + mordida + duas garras contra mesmo alvo (+2 da investida).',
      'Imune a medo; visão no escuro.',
    ],
    treasureXp: 3000,
    bookPage: 292,
  },
  {
    id: 'basilisco',
    name: 'Basilisco',
    nd: 4,
    tipo: 'monstro',
    size: 'medio',
    hp: 145,
    defesa: 23,
    forca: 4, destreza: 2, constituicao: 4,
    inteligencia: -4, sabedoria: 1, carisma: 0,
    fortitude: 10, reflexos: 9, vontade: 9,
    deslocamento: '9m, natação 9m',
    attacks: [
      {
        name: 'Mordida',
        attackBonus: 16,
        damage: '2d8+12 mais veneno',
        special: 'Peçonha Concentrada (1d12 PV/rod por 3 rod; Fort CD 18 reduz para 1 rod).',
      },
    ],
    specialAbilities: [
      'Olhar Petrificante: criaturas em curto fazem Ref CD 18; falha = lento; já lento = petrificado permanente. Fechar olhos como reação imuniza por uma rodada (mas cego nessa rodada).',
      'Redução de dano 5; visão no escuro.',
    ],
    treasureXp: 4000,
    bookPage: 293,
  },
  {
    id: 'ogro',
    name: 'Ogro',
    nd: 4,
    tipo: 'humanoide',
    size: 'grande',
    hp: 130,
    defesa: 23,
    forca: 7, destreza: 0, constituicao: 4,
    inteligencia: -3, sabedoria: -2, carisma: -2,
    fortitude: 16, reflexos: 10, vontade: 0,
    deslocamento: '9m',
    attacks: [{ name: 'Tacape', attackBonus: 16, damage: '1d12+18' }],
    specialAbilities: [
      'Burro Demais...: -5 em Intuição e Vontade (já contabilizado).',
      '...Para Morrer!: dano de corte, impacto e perfuração reduzido à metade.',
      'Visão na penumbra.',
    ],
    treasureXp: 4000,
    bookPage: 293,
  },
  {
    id: 'urso-coruja',
    name: 'Urso-Coruja',
    nd: 4,
    tipo: 'monstro',
    size: 'grande',
    hp: 145,
    defesa: 23,
    forca: 7, destreza: 3, constituicao: 5,
    inteligencia: -4, sabedoria: 1, carisma: -2,
    fortitude: 16, reflexos: 10, vontade: 5,
    deslocamento: '12m',
    attacks: [
      { name: 'Mordida', attackBonus: 16, damage: '1d8+5' },
      { name: 'Duas garras', attackBonus: 15, damage: '1d6+5' },
    ],
    specialAbilities: [
      'Agarrar Aprimorado (livre): em acerto de garra, manobra agarrar (teste +18).',
      'Faro, visão no escuro.',
    ],
    treasureXp: 4000,
    bookPage: 293,
  },
  {
    id: 'troll',
    name: 'Troll',
    nd: 5,
    tipo: 'monstro',
    size: 'grande',
    hp: 165,
    defesa: 23,
    forca: 6, destreza: 2, constituicao: 6,
    inteligencia: -2, sabedoria: -1, carisma: -2,
    fortitude: 14, reflexos: 10, vontade: 6,
    deslocamento: '9m',
    attacks: [
      { name: 'Mordida', attackBonus: 17, damage: '1d8+6' },
      { name: 'Duas garras', attackBonus: 17, damage: '1d6+6' },
    ],
    specialAbilities: [
      'Cura acelerada 15 (anulada por ácido ou fogo).',
      'Dilacerar: duas garras no mesmo alvo na mesma rodada = +2d6+6 de dano.',
      'Visão no escuro.',
    ],
    treasureXp: 5000,
    bookPage: 309,
  },
  {
    id: 'manticora',
    name: 'Mantícora',
    nd: 6,
    tipo: 'monstro',
    size: 'grande',
    hp: 240,
    defesa: 26,
    forca: 7, destreza: 2, constituicao: 5,
    inteligencia: -2, sabedoria: 1, carisma: -1,
    fortitude: 18, reflexos: 7, vontade: 12,
    deslocamento: '9m, voo 15m',
    attacks: [
      { name: 'Mordida', attackBonus: 18, damage: '1d10+12' },
      { name: 'Duas garras', attackBonus: 18, damage: '1d8+12' },
    ],
    specialAbilities: [
      'Espinhos (movimento, recarga mov): 1d4 espinhos a médio, cada 1d8+7 perfuração (Ref CD 22 reduz à metade).',
      'Faro, visão no escuro.',
    ],
    treasureXp: 6000,
    bookPage: 287,
  },
  {
    id: 'dragao-jovem',
    name: 'Dragão Jovem',
    nd: 7,
    tipo: 'monstro',
    size: 'grande',
    hp: 320,
    defesa: 32,
    forca: 7, destreza: 2, constituicao: 6,
    inteligencia: 2, sabedoria: 2, carisma: 2,
    fortitude: 20, reflexos: 9, vontade: 12,
    deslocamento: '12m, voo 18m',
    attacks: [
      { name: 'Mordida', attackBonus: 25, damage: '2d6+14', special: 'crítico 19' },
      { name: 'Duas garras', attackBonus: 25, damage: '1d8+14', special: 'crítico 19' },
    ],
    specialAbilities: [
      'Sopro (padrão, recarga mov): cone 9m, 6d12 fogo + em chamas (Ref CD 25 reduz à metade e evita).',
      'Varrer (livre): 1×/rod, reduzir alvo a 0 PV concede ataque adicional contra adjacente.',
      'Redução de dano 5; imune fogo; vulnerável frio; resistência a magia +2.',
      'Metamorfose Dracônica; percepção às cegas.',
    ],
    treasureXp: 7000,
    bookPage: 311,
  },
  {
    id: 'golem-de-ferro',
    name: 'Golem de Ferro',
    nd: 10,
    tipo: 'construto',
    size: 'grande',
    hp: 400,
    defesa: 36,
    forca: 12, destreza: -1, constituicao: 10,
    inteligencia: 0, sabedoria: 0, carisma: -5,
    fortitude: 24, reflexos: 14, vontade: 11,
    deslocamento: '9m',
    attacks: [{ name: 'Duas pancadas', attackBonus: 30, damage: '2d10+25' }],
    specialAbilities: [
      'Imunidade a Magia (exceções: eletricidade deixa lento 1d6 rod; fogo remove lento e cura 1 PV por 3 de dano).',
      'Sopro (movimento, recarga, veneno): cubo 3m, 6d12 PV + enjoado (Fort CD 30 reduz à metade e evita).',
      'Redução de dano 10; imunidades de construto.',
    ],
    treasureXp: 10000,
    bookPage: 288,
  },
  {
    id: 'dragao-adulto',
    name: 'Dragão Adulto',
    nd: 11,
    tipo: 'monstro',
    size: 'enorme',
    hp: 600,
    defesa: 42,
    forca: 11, destreza: 1, constituicao: 8,
    inteligencia: 4, sabedoria: 4, carisma: 4,
    fortitude: 24, reflexos: 11, vontade: 18,
    deslocamento: '12m, voo 24m',
    attacks: [
      { name: 'Mordida', attackBonus: 35, damage: '4d10+25', special: 'crítico 18' },
      { name: 'Duas garras', attackBonus: 35, damage: '3d10+25', special: 'crítico 18' },
    ],
    specialAbilities: [
      'Sopro (padrão, recarga mov): cone 12m, 12d12 fogo + em chamas (Ref CD 32 reduz à metade e evita).',
      'Aura Aterradora (raio 90m, Von CD 31).',
      'Magia arcano 11º (CD 32): Campo de Força, Curar Ferimentos, Dissipar Magia, Enfeitiçar, Globo de Invulnerabilidade, Velocidade.',
      'Varrer, Metamorfose Dracônica, percepção às cegas, RD 10, imune fogo, vulnerável frio, resistência a magia +3.',
    ],
    treasureXp: 11000,
    bookPage: 311,
  },
  {
    id: 'hidra',
    name: 'Hidra',
    nd: 11,
    tipo: 'monstro',
    size: 'enorme',
    hp: 550,
    defesa: 35,
    forca: 10, destreza: 2, constituicao: 8,
    inteligencia: -4, sabedoria: 1, carisma: -2,
    fortitude: 24, reflexos: 18, vontade: 9,
    deslocamento: '9m, natação 9m',
    attacks: [{ name: 'Cinco mordidas', attackBonus: 34, damage: '3d6+16' }],
    specialAbilities: [
      'Cura acelerada 100.',
      'Cortar Cabeças: corte que cause dano à hidra (CD 24) nasce duas cabeças no lugar.',
      'Faro, visão no escuro.',
    ],
    treasureXp: 11000,
    bookPage: 306,
  },
  {
    id: 'vampiro',
    name: 'Vampiro',
    nd: 12,
    tipo: 'morto-vivo',
    size: 'medio',
    hp: 550,
    defesa: 45,
    forca: 6, destreza: 5, constituicao: 5,
    inteligencia: 3, sabedoria: 3, carisma: 6,
    fortitude: 12, reflexos: 26, vontade: 20,
    deslocamento: '18m, escalar 18m',
    attacks: [
      {
        name: 'Espada longa x2',
        attackBonus: 36,
        damage: '2d8+25 mais 2d10 trevas',
        special: 'crítico 17',
      },
      { name: 'Garra', attackBonus: 36, damage: '2d6+25 mais 2d10 trevas' },
    ],
    specialAbilities: [
      'Dominação Vampírica (padrão): humanoide a curto fica confuso/enfeitiçado/fascinado ou perde memórias (Von CD 29 evita); 1×/cena por alvo.',
      'Drenar Sangue: criatura agarrada perde 6d6 perfuração; vampiro cura igual.',
      'Forma de Morcego; Presença Majestosa (Von CD 29).',
      'Cura acelerada 10; RD 10/luz; sensibilidade ao sol (ofuscado, perde 6d6 PV/rod sob luz solar).',
    ],
    treasureXp: 12000,
    bookPage: 299,
  },
  {
    id: 'dragao-rei',
    name: 'Dragão-Rei',
    nd: 20,
    tipo: 'monstro',
    size: 'colossal',
    hp: 1400,
    defesa: 62,
    forca: 15, destreza: 1, constituicao: 12,
    inteligencia: 8, sabedoria: 8, carisma: 8,
    fortitude: 34, reflexos: 20, vontade: 28,
    deslocamento: '12m, voo 36m',
    attacks: [
      { name: 'Mordida', attackBonus: 55, damage: '6d20+50', special: 'crítico 16' },
      { name: 'Duas garras', attackBonus: 50, damage: '6d20+50', special: 'crítico 16' },
    ],
    specialAbilities: [
      'Sopro (padrão, recarga mov): cone 18m, 20d12 fogo + em chamas (Ref CD 50 reduz à metade e evita).',
      'Escamas Supremas: dano de fontes mundanas reduzido à metade.',
      'Aura Aterradora (Von CD 50).',
      'Magia arcano 20º (CD 50): Campo de Força, Controlar a Gravidade, Controlar o Tempo, Dissipar Magia, Enfeitiçar, Globo de Invulnerabilidade, Segunda Chance, Velocidade.',
      'Magia Acelerada, Fluxo de Mana, percepção às cegas, RD 20, imune fogo, vulnerável frio, resistência a magia +5.',
    ],
    treasureXp: 20000,
    bookPage: 312,
  },

  // Bestiário expansão #1 (livro p286-298) — grupos Masmorras / Ermos /
  // Bandidos-Guardas-Centauros-Gnolls / Puristas / Reino dos Mortos.

  // ── Masmorras ────────────────────────────────────────────────
  {
    id: 'glop',
    name: 'Glop',
    nd: 0.25,
    tipo: 'monstro',
    size: 'pequeno',
    hp: 10,
    defesa: 10,
    forca: 0, destreza: 0, constituicao: 0,
    inteligencia: -5, sabedoria: -5, carisma: -5,
    fortitude: 0, reflexos: 2, vontade: -5,
    deslocamento: '9m (6q)',
    attacks: [
      { name: 'Pancada', attackBonus: 7, damage: '1d4 mais 1d4 ácido' },
    ],
    specialAbilities: [
      'Percepção às cegas.',
      'Imunidade a ácido.',
    ],
    treasureXp: 250,
    bookPage: 286,
  },
  {
    id: 'rato-gigante',
    name: 'Rato Gigante',
    nd: 0.25,
    tipo: 'animal',
    size: 'pequeno',
    hp: 3,
    defesa: 12,
    forca: 0, destreza: 2, constituicao: 1,
    inteligencia: -4, sabedoria: 1, carisma: -3,
    fortitude: 0, reflexos: 3, vontade: -2,
    deslocamento: '12m (8q), escalar 6m (4q)',
    attacks: [
      { name: 'Mordida', attackBonus: 7, damage: '1d4+3 mais doença' },
    ],
    specialAbilities: [
      'Faro; visão na penumbra.',
      'Doença (mordida): infecção do esgoto — Fortitude para evitar (p318).',
    ],
    treasureXp: 250,
    bookPage: 286,
  },
  {
    id: 'orc-chefe',
    name: 'Orc Chefe',
    nd: 2,
    tipo: 'humanoide',
    size: 'medio',
    hp: 66,
    defesa: 19,
    forca: 5, destreza: 1, constituicao: 4,
    inteligencia: 0, sabedoria: 0, carisma: 0,
    fortitude: 13, reflexos: 7, vontade: 2,
    deslocamento: '9m (6q)',
    attacks: [
      { name: 'Machado de batalha', attackBonus: 11, damage: '1d8+12', special: 'crítico x3' },
    ],
    specialAbilities: [
      'Urro Selvagem (movimento): +2 em ataques e dano até o fim da cena; incompatível com concentração.',
      'Sensibilidade à luz: ofuscado sob luz solar.',
      'Perícias: Intimidação +4, Sobrevivência +5 (+7 em subterrâneos).',
    ],
    treasureXp: 2000,
    bookPage: 286,
  },
  {
    id: 'orc-mutante',
    name: 'Orc Mutante',
    nd: 5,
    tipo: 'humanoide',
    size: 'medio',
    hp: 55,
    defesa: 22,
    forca: 6, destreza: 2, constituicao: 4,
    inteligencia: -2, sabedoria: -2, carisma: -2,
    fortitude: 15, reflexos: 11, vontade: 7,
    deslocamento: '9m (6q)',
    attacks: [
      { name: 'Machado de guerra', attackBonus: 20, damage: '1d12+18', special: 'x3' },
      { name: 'Mordida', attackBonus: 20, damage: '1d6+18' },
    ],
    specialAbilities: [
      'Terceiro Braço (livre): se acertar machado + mordida no mesmo alvo em uma rodada, causa 1d6+9 corte extra.',
      'Sensibilidade à luz: ofuscado sob luz solar.',
    ],
    treasureXp: 5000,
    bookPage: 286,
  },
  {
    id: 'guerreiro-chifres',
    name: 'Guerreiro de Chifres',
    nd: 3,
    tipo: 'espirito',
    size: 'medio',
    hp: 100,
    defesa: 21,
    forca: 5, destreza: 3, constituicao: 4,
    inteligencia: -2, sabedoria: 1, carisma: -1,
    fortitude: 13, reflexos: 11, vontade: 9,
    deslocamento: '9m (6q)',
    attacks: [
      { name: 'Machado de guerra', attackBonus: 14, damage: '1d12+16', special: 'x3' },
      { name: 'Chifres', attackBonus: 14, damage: '2d6+10 impacto' },
    ],
    specialAbilities: [
      'Marrada (completa): investida com machado + chifres, ambos com +2 no mesmo alvo.',
      'Imunidade a ácido e veneno; redução de dano 5; redução de fogo e frio 10.',
      'Perícias: Atletismo +8, Intimidação +4.',
    ],
    treasureXp: 3000,
    bookPage: 287,
  },
  {
    id: 'centopeia-dragao',
    name: 'Centopeia-Dragão',
    nd: 7,
    tipo: 'monstro',
    size: 'enorme',
    hp: 275,
    defesa: 27,
    forca: 11, destreza: 3, constituicao: 9,
    inteligencia: -4, sabedoria: 1, carisma: 0,
    fortitude: 20, reflexos: 14, vontade: 9,
    deslocamento: '15m (10q), escavar 6m (4q)',
    attacks: [
      { name: 'Mordida', attackBonus: 24, damage: '2d8+18 mais 2d6 fogo' },
    ],
    specialAbilities: [
      'Agarrar Aprimorado (livre): após mordida, agarrar +29.',
      'Aura de Calor (enfurecida): 4d6+9 fogo em raio 9m no início do turno.',
      'Engolir (padrão): agarrada Média ou menor → 2d6+18 impacto + 4d6+9 fogo/rodada dentro.',
      'Imunidade a condição caído; redução de fogo 10.',
    ],
    treasureXp: 7000,
    bookPage: 287,
  },

  // ── Ermos ─────────────────────────────────────────────────────
  {
    id: 'bandido',
    name: 'Bandido',
    nd: 0.25,
    tipo: 'humanoide',
    size: 'medio',
    hp: 6,
    defesa: 13,
    forca: 1, destreza: 2, constituicao: 1,
    inteligencia: 0, sabedoria: -1, carisma: 0,
    fortitude: 1, reflexos: 3, vontade: -1,
    deslocamento: '9m (6q)',
    attacks: [
      { name: 'Clava', attackBonus: 7, damage: '1d6+3' },
    ],
    specialAbilities: [
      'Perícias: Furtividade +5.',
    ],
    treasureXp: 250,
    bookPage: 289,
  },
  {
    id: 'chefe-bandido',
    name: 'Chefe Bandido',
    nd: 1,
    tipo: 'humanoide',
    size: 'medio',
    hp: 30,
    defesa: 16,
    forca: 3, destreza: 2, constituicao: 3,
    inteligencia: 0, sabedoria: 0, carisma: 1,
    fortitude: 5, reflexos: 8, vontade: 3,
    deslocamento: '9m',
    attacks: [
      { name: 'Espada curta', attackBonus: 9, damage: '1d6+5', special: '19' },
      { name: 'Adaga (à distância)', attackBonus: 7, damage: '1d4+3', special: '19' },
    ],
    specialAbilities: [
      'Ataque Furtivo: +2d6 dano 1×/rodada contra desprevenidos ou flanqueados (curto ou corpo a corpo).',
      'Perícias: Furtividade +7, Intimidação +6.',
    ],
    treasureXp: 1000,
    bookPage: 289,
  },
  {
    id: 'guarda-cidade',
    name: 'Guarda de Cidade',
    nd: 0.5,
    tipo: 'humanoide',
    size: 'medio',
    hp: 8,
    defesa: 15,
    forca: 2, destreza: 1, constituicao: 2,
    inteligencia: 0, sabedoria: 0, carisma: 0,
    fortitude: 5, reflexos: 2, vontade: 1,
    deslocamento: '9m (6q)',
    attacks: [
      { name: 'Maça', attackBonus: 7, damage: '1d8+5' },
    ],
    specialAbilities: [
      'Perícias: Atletismo +5.',
    ],
    treasureXp: 500,
    bookPage: 289,
  },
  {
    id: 'sargento-guarda',
    name: 'Sargento da Guarda',
    nd: 1,
    tipo: 'humanoide',
    size: 'medio',
    hp: 28,
    defesa: 17,
    forca: 3, destreza: 1, constituicao: 2,
    inteligencia: 0, sabedoria: 0, carisma: 1,
    fortitude: 9, reflexos: 4, vontade: 3,
    deslocamento: '6m (4q)',
    attacks: [
      { name: 'Maça', attackBonus: 10, damage: '1d8+10' },
      { name: 'Besta leve (à distância)', attackBonus: 9, damage: '1d8+5', special: '19' },
    ],
    specialAbilities: [
      'Ordens (movimento): aliados em curto ganham +2 em perícias até o fim da cena.',
      'Perícias: Atletismo +7, Intuição +4.',
    ],
    treasureXp: 1000,
    bookPage: 289,
  },
  {
    id: 'centauro-combatente',
    name: 'Centauro Combatente',
    nd: 1,
    tipo: 'humanoide',
    size: 'grande',
    hp: 35,
    defesa: 16,
    forca: 5, destreza: 3, constituicao: 3,
    inteligencia: -2, sabedoria: 1, carisma: -2,
    fortitude: 9, reflexos: 2, vontade: 5,
    deslocamento: '12m (8q)',
    attacks: [
      { name: 'Tacape', attackBonus: 9, damage: '1d12+5' },
      { name: 'Cascos', attackBonus: 9, damage: '1d8+5' },
      { name: 'Arco longo (à distância)', attackBonus: 7, damage: '1d10+5', special: 'x3' },
    ],
    specialAbilities: [
      'Investida Poderosa: +1d12 dano na investida com tacape.',
      'Medo de Altura: abalado se adjacente a queda de 3m+.',
      'Perícias: Sobrevivência +5.',
    ],
    treasureXp: 1000,
    bookPage: 290,
  },
  {
    id: 'centauro-xama',
    name: 'Centauro Xamã',
    nd: 3,
    tipo: 'humanoide',
    size: 'grande',
    hp: 35,
    defesa: 21,
    forca: 4, destreza: 1, constituicao: 3,
    inteligencia: -1, sabedoria: 4, carisma: 0,
    fortitude: 9, reflexos: 4, vontade: 15,
    deslocamento: '12m (8q)',
    attacks: [
      { name: 'Bordão', attackBonus: 11, damage: '1d8+4' },
      { name: 'Cascos', attackBonus: 11, damage: '1d8+4' },
    ],
    specialAbilities: [
      'Magias (clérigo 3º de Allihanna, CD 17): Armamento da Natureza, Controlar Plantas, Curar Ferimentos.',
      'Voz Divina sempre ativa (falar com animais).',
      'PM 20; Medo de Altura.',
      'Perícias: Religião +8, Sobrevivência +10.',
    ],
    treasureXp: 3000,
    bookPage: 290,
  },
  {
    id: 'gnoll-saqueador',
    name: 'Gnoll Saqueador',
    nd: 1,
    tipo: 'humanoide',
    size: 'medio',
    hp: 15,
    defesa: 15,
    forca: 3, destreza: 2, constituicao: 3,
    inteligencia: -2, sabedoria: 1, carisma: -1,
    fortitude: 7, reflexos: 7, vontade: 1,
    deslocamento: '9m (6q)',
    attacks: [
      { name: 'Lança', attackBonus: 10, damage: '1d6+4' },
      { name: 'Mordida', attackBonus: 10, damage: '1d6+4' },
      { name: 'Arco curto (à distância)', attackBonus: 9, damage: '1d6+3', special: 'x3' },
    ],
    specialAbilities: [
      'Faro.',
    ],
    treasureXp: 1000,
    bookPage: 290,
  },
  {
    id: 'gnoll-filibusteiro',
    name: 'Gnoll Filibusteiro',
    nd: 2,
    tipo: 'humanoide',
    size: 'medio',
    hp: 60,
    defesa: 19,
    forca: 3, destreza: 4, constituicao: 3,
    inteligencia: -1, sabedoria: 2, carisma: -1,
    fortitude: 7, reflexos: 11, vontade: 4,
    deslocamento: '9m (6q)',
    attacks: [
      { name: 'Espada curta', attackBonus: 11, damage: '1d6+4', special: '19' },
      { name: 'Mordida', attackBonus: 11, damage: '1d6+4' },
      { name: 'Mosquete (à distância)', attackBonus: 12, damage: '2d8+9', special: '19/x3' },
    ],
    specialAbilities: [
      'Recarga Rápida: mosquete recarrega como movimento.',
      'Faro.',
    ],
    treasureXp: 2000,
    bookPage: 291,
  },
  {
    id: 'gorlogg',
    name: 'Gorlogg',
    nd: 1,
    tipo: 'animal',
    size: 'grande',
    hp: 36,
    defesa: 16,
    forca: 5, destreza: 2, constituicao: 5,
    inteligencia: -4, sabedoria: 2, carisma: -4,
    fortitude: 8, reflexos: 5, vontade: 3,
    deslocamento: '12m (8q)',
    attacks: [
      { name: 'Mordida', attackBonus: 9, damage: '2d6+8', special: 'x3' },
    ],
    specialAbilities: [
      'Agarrar Aprimorado (livre): após mordida, agarrar +13.',
      'Perícias: Atletismo +9.',
    ],
    treasureXp: 1000,
    bookPage: 291,
  },
  {
    id: 'trog',
    name: 'Trog',
    nd: 1,
    tipo: 'humanoide',
    size: 'medio',
    hp: 11,
    defesa: 16,
    forca: 3, destreza: 1, constituicao: 3,
    inteligencia: -2, sabedoria: 0, carisma: -1,
    fortitude: 10, reflexos: 5, vontade: 1,
    deslocamento: '9m (6q)',
    attacks: [
      { name: 'Lança', attackBonus: 11, damage: '1d6+5' },
      { name: 'Mordida', attackBonus: 11, damage: '1d6+5' },
      { name: 'Azagaia (à distância)', attackBonus: 9, damage: '1d6+5' },
    ],
    specialAbilities: [
      'Mau Cheiro (padrão): enjoados por 1d6 rodadas em curto (Fort CD 15). Veneno.',
      'Sangue Frio: +1 dano por dado de frio recebido.',
      'Perícias: Furtividade +7 (camaleônico).',
    ],
    treasureXp: 1000,
    bookPage: 292,
  },
  {
    id: 'lobo-das-cavernas',
    name: 'Lobo-das-Cavernas',
    nd: 2,
    tipo: 'animal',
    size: 'grande',
    hp: 73,
    defesa: 19,
    forca: 6, destreza: 2, constituicao: 5,
    inteligencia: -4, sabedoria: 2, carisma: -2,
    fortitude: 11, reflexos: 7, vontade: 6,
    deslocamento: '15m (10q)',
    attacks: [
      { name: 'Mordida', attackBonus: 13, damage: '2d6+10' },
    ],
    specialAbilities: [
      'Derrubar (livre) após mordida bem-sucedida (teste +15).',
      'Táticas de Alcateia: +2 no ataque e dano ao flanquear.',
      'Faro; visão na penumbra.',
      'Perícias: Sobrevivência +11.',
    ],
    treasureXp: 2000,
    bookPage: 292,
  },
  {
    id: 'cao-do-inferno',
    name: 'Cão do Inferno',
    nd: 3,
    tipo: 'espirito',
    size: 'grande',
    hp: 95,
    defesa: 21,
    forca: 5, destreza: 3, constituicao: 4,
    inteligencia: -2, sabedoria: 1, carisma: -2,
    fortitude: 11, reflexos: 9, vontade: 7,
    deslocamento: '12m (8q)',
    attacks: [
      { name: 'Mordida', attackBonus: 14, damage: '2d6+6 mais 2d6 fogo' },
    ],
    specialAbilities: [
      'Sopro (padrão): cone 6m, 4d6+4 fogo (Ref CD 17 metade). Recarga movimento.',
      'Imunidade a fogo; redução de dano 10/mágico; vulnerabilidade a frio.',
      'Perícias: Atletismo +9.',
    ],
    treasureXp: 3000,
    bookPage: 292,
  },
  {
    id: 'serpe',
    name: 'Serpe',
    nd: 5,
    tipo: 'monstro',
    size: 'grande',
    hp: 200,
    defesa: 24,
    forca: 6, destreza: 1, constituicao: 6,
    inteligencia: -2, sabedoria: 1, carisma: -1,
    fortitude: 16, reflexos: 10, vontade: 7,
    deslocamento: '9m (6q), voo 18m (12q)',
    attacks: [
      { name: 'Mordida', attackBonus: 17, damage: '2d6+12' },
      { name: 'Ferrão', attackBonus: 17, damage: '1d8+12 mais veneno' },
    ],
    specialAbilities: [
      'Agarrar Aprimorado (livre): após mordida, agarrar +19.',
      'Veneno (ferrão): 1d12 PV/rodada por 3 rodadas (Fort CD 20 reduz a 1 rodada).',
      'Imunidade a paralisia.',
    ],
    treasureXp: 5000,
    bookPage: 293,
  },

  // ── Puristas ─────────────────────────────────────────────────
  {
    id: 'recruta-purista',
    name: 'Recruta Purista',
    nd: 0.5,
    tipo: 'humanoide',
    size: 'medio',
    hp: 10,
    defesa: 16,
    forca: 2, destreza: 1, constituicao: 2,
    inteligencia: -1, sabedoria: -1, carisma: 0,
    fortitude: 6, reflexos: 2, vontade: 0,
    deslocamento: '6m (4q)',
    attacks: [
      { name: 'Alabarda', attackBonus: 8, damage: '1d10+5', special: 'x3' },
    ],
    specialAbilities: [
      'Lutar em Formação: +2 em ataque e Defesa se adjacente a aliado com o mesmo poder.',
      'Ódio Puro: +5 Vontade sob ordens de superior, +2 dano contra humanoides não humanos.',
    ],
    treasureXp: 500,
    bookPage: 294,
  },
  {
    id: 'soldado-purista',
    name: 'Soldado Purista',
    nd: 1,
    tipo: 'humanoide',
    size: 'medio',
    hp: 20,
    defesa: 20,
    forca: 3, destreza: 1, constituicao: 3,
    inteligencia: 0, sabedoria: -1, carisma: 0,
    fortitude: 10, reflexos: 4, vontade: 1,
    deslocamento: '6m (4q)',
    attacks: [
      { name: 'Espada bastarda', attackBonus: 9, damage: '1d10+9', special: '19' },
      { name: 'Besta pesada (à distância)', attackBonus: 7, damage: '1d12+4', special: '19' },
    ],
    specialAbilities: [
      'Lutar em Formação: +2 em ataque e Defesa se adjacente a aliado com o mesmo poder.',
      'Ódio Puro: +5 Vontade sob ordens de superior, +2 dano contra humanoides não humanos.',
    ],
    treasureXp: 1000,
    bookPage: 294,
  },
  {
    id: 'sargento-mor',
    name: 'Sargento-Mor',
    nd: 3,
    tipo: 'humanoide',
    size: 'medio',
    hp: 105,
    defesa: 24,
    forca: 4, destreza: 1, constituicao: 4,
    inteligencia: 0, sabedoria: 0, carisma: 0,
    fortitude: 14, reflexos: 9, vontade: 5,
    deslocamento: '6m (4q)',
    attacks: [
      { name: 'Espada bastarda', attackBonus: 14, damage: '1d12+15', special: '19' },
      { name: 'Besta pesada (à distância)', attackBonus: 12, damage: '1d12+10', special: '19' },
    ],
    specialAbilities: [
      'Lutar em Formação: +2 em ataque e Defesa se adjacente a aliado com o mesmo poder.',
      'Varrer (livre): ao reduzir alvo corpo a corpo a 0 PV, ataque adicional em outra criatura adjacente.',
      'Ódio Puro: +5 Vontade sob ordens de superior.',
    ],
    treasureXp: 3000,
    bookPage: 294,
  },
  {
    id: 'capelao-guerra',
    name: 'Capelão de Guerra',
    nd: 4,
    tipo: 'humanoide',
    size: 'medio',
    hp: 105,
    defesa: 21,
    forca: 4, destreza: 1, constituicao: 4,
    inteligencia: 0, sabedoria: 3, carisma: -1,
    fortitude: 10, reflexos: 4, vontade: 16,
    deslocamento: '6m (4q)',
    attacks: [
      { name: 'Martelo de guerra', attackBonus: 14, damage: '1d8+15', special: 'x3' },
    ],
    specialAbilities: [
      'PM 25.',
      'Magias (clérigo 5º, CD 18): Arma Mágica, Bênção, Curar Ferimentos, Soco de Arsenal.',
      'Imunidade a medo (via cânticos); Ódio Puro.',
      'Perícias: Misticismo +5, Religião +7.',
    ],
    treasureXp: 4000,
    bookPage: 295,
  },
  {
    id: 'capitao-baluarte',
    name: 'Capitão-Baluarte',
    nd: 5,
    tipo: 'humanoide',
    size: 'medio',
    hp: 115,
    defesa: 33,
    forca: 5, destreza: 0, constituicao: 4,
    inteligencia: 1, sabedoria: 3, carisma: 4,
    fortitude: 15, reflexos: 4, vontade: 13,
    deslocamento: '6m (4q)',
    attacks: [
      { name: 'Espada longa', attackBonus: 17, damage: '1d8+8', special: '19' },
    ],
    specialAbilities: [
      'Comandar (padrão): aliados em curto +4 em ataque e dano por 1 rodada.',
      'Formação Invencível: aliados em curto +2 Defesa.',
      'Ódio Puro.',
      'Perícias: Cavalgar +4, Guerra +7, Nobreza +7.',
    ],
    treasureXp: 5000,
    bookPage: 295,
  },
  {
    id: 'cavaleiro-leopardo-sangrento',
    name: 'Cavaleiro do Leopardo Sangrento',
    nd: 9,
    tipo: 'humanoide',
    size: 'medio',
    hp: 270,
    defesa: 36,
    forca: 5, destreza: 2, constituicao: 5,
    inteligencia: 3, sabedoria: 0, carisma: 2,
    fortitude: 21, reflexos: 11, vontade: 17,
    deslocamento: '9m (6q)',
    attacks: [
      { name: 'Espada bastarda', attackBonus: 28, damage: '3d6+15', special: '19' },
    ],
    specialAbilities: [
      'PM 58; Imunidade a medo.',
      'Cavaleiro Místico (mago 9º, CD 28): pode conjurar de armadura sem teste; 1×/rodada, magia livre após ataque corpo a corpo.',
      'Magias: Concentração de Combate, Dissipar Magia, Pele de Pedra, Toque Chocante, Velocidade.',
      'Ódio Puro.',
      'Perícias: Furtividade +8, Intimidação +17, Misticismo +19.',
    ],
    treasureXp: 9000,
    bookPage: 295,
  },
  {
    id: 'colosso-supremo',
    name: 'Colosso Supremo',
    nd: 14,
    tipo: 'construto',
    size: 'colossal',
    hp: 675,
    defesa: 46,
    forca: 15, destreza: -1, constituicao: 10,
    inteligencia: -5, sabedoria: -5, carisma: -5,
    fortitude: 31, reflexos: 19, vontade: 20,
    deslocamento: '12m (8q)',
    attacks: [
      { name: 'Espada titânica', attackBonus: 39, damage: '4d12+30', special: '19' },
    ],
    specialAbilities: [
      'Balistas (livre): dois canhões (+39, 6d8 perfuração, crítico 19, alcance médio).',
      'Fumos Tóxicos: 4d6 PV + enjoado em curto (Fort CD 38). Veneno.',
      'Jato de Chamas (movimento): cone 12m, 8d8+10 fogo (Ref CD 38 metade).',
      'Passar por Cima (completa): atropela criaturas Grandes ou menores por 6d8+15 impacto (Ref CD 38 metade).',
      'Varrer (livre); Cura acelerada 20; RD 10; resistência a magia +5.',
      'Goblins Consertadores: fonte da cura acelerada; imunes a dano, afetáveis por efeitos mentais (Von +3).',
    ],
    treasureXp: 14000,
    bookPage: 296,
  },

  // ── Reino dos Mortos ─────────────────────────────────────────
  {
    id: 'turba-zumbi',
    name: 'Turba Zumbi',
    nd: 2,
    tipo: 'morto-vivo',
    size: 'grande',
    hp: 100,
    defesa: 11,
    forca: 3, destreza: -1, constituicao: 3,
    inteligencia: -5, sabedoria: -1, carisma: 0,
    fortitude: 5, reflexos: 1, vontade: 1,
    deslocamento: '6m (4q)',
    attacks: [
      { name: 'Mordida (bando)', attackBonus: 17, damage: '2d6+12' },
    ],
    specialAbilities: [
      'Bando: dano dobrado ao superar Defesa em 10+; metade em erro. Imune a manobras e efeitos monoalvo; sofre 50% a mais de área.',
      'Fraqueza Zumbi: dobro em críticos ou ataques ao cérebro (Defesa 21).',
      'Visão no escuro; traços de morto-vivo.',
    ],
    treasureXp: 2000,
    bookPage: 297,
  },
  {
    id: 'esqueleto-elite',
    name: 'Esqueleto de Elite',
    nd: 4,
    tipo: 'morto-vivo',
    size: 'medio',
    hp: 60,
    defesa: 25,
    forca: 6, destreza: 4, constituicao: 2,
    inteligencia: 0, sabedoria: 0, carisma: -5,
    fortitude: 4, reflexos: 10, vontade: 16,
    deslocamento: '6m (4q)',
    attacks: [
      { name: 'Espada longa', attackBonus: 18, damage: '2d8+15 mais 2d8 trevas', special: '19' },
    ],
    specialAbilities: [
      'Redução de corte, frio e perfuração 5.',
      'Traços de morto-vivo (imunidade a cansaço/metabólicos/veneno).',
    ],
    treasureXp: 4000,
    bookPage: 297,
  },
  {
    id: 'aparicao',
    name: 'Aparição',
    nd: 5,
    tipo: 'morto-vivo',
    size: 'medio',
    hp: 110,
    defesa: 23,
    forca: 0, destreza: 6, constituicao: 0,
    inteligencia: 0, sabedoria: 5, carisma: 2,
    fortitude: 5, reflexos: 17, vontade: 11,
    deslocamento: 'voo 18m (12q)',
    attacks: [
      { name: 'Toque drenante', attackBonus: 18, damage: '3d8+6 trevas' },
    ],
    specialAbilities: [
      'Incorpórea.',
      'Toque Drenante: alvo vivo faz Fort CD 21 ou fica fraca (cumulativo) e aparição ganha 20 PV temporários.',
      'Vulnerabilidade à Luz do Dia: enfraquecida sob luz solar.',
      'Perícias: Furtividade +15.',
    ],
    treasureXp: 5000,
    bookPage: 298,
  },
  {
    id: 'necromante',
    name: 'Necromante',
    nd: 7,
    tipo: 'humanoide',
    size: 'medio',
    hp: 180,
    defesa: 23,
    forca: 0, destreza: 2, constituicao: 1,
    inteligencia: 5, sabedoria: 0, carisma: 0,
    fortitude: 7, reflexos: 14, vontade: 20,
    deslocamento: '12m (8q)',
    attacks: [
      { name: 'Adaga', attackBonus: 22, damage: '1d4 mais 1d8 trevas', special: '19' },
    ],
    specialAbilities: [
      'PM 55.',
      'Erguer-se! (completa, 5 PM): 6 mortos-vivos servos com deslocamento 9m; padrão para 2d8 trevas em criatura adjacente.',
      'Sacrificar Servo (reação): 1×/rodada, redirecionar dano para servo.',
      'Magias (mago 7º, CD 26; 28 necromancia): Amedrontar, Armadura Arcana, Crânio Voador, Toque Vampírico.',
      'Perícias: Conhecimento +14, Misticismo +16.',
    ],
    treasureXp: 7000,
    bookPage: 298,
  },
  {
    id: 'falange',
    name: 'Falange',
    nd: 8,
    tipo: 'morto-vivo',
    size: 'grande',
    hp: 300,
    defesa: 25,
    forca: 6, destreza: 4, constituicao: 2,
    inteligencia: -5, sabedoria: 0, carisma: -5,
    fortitude: 6, reflexos: 12, vontade: 18,
    deslocamento: '6m',
    attacks: [
      { name: 'Espada longa (bando)', attackBonus: 28, damage: '4d8+30 mais 4d8 trevas', special: '19' },
    ],
    specialAbilities: [
      'Bando: dano dobrado ao superar Defesa em 10+; metade em erro. Imune a manobras e efeitos monoalvo; sofre 50% a mais de área.',
      'Redução de corte, frio e perfuração 5.',
      'Traços de morto-vivo.',
    ],
    treasureXp: 8000,
    bookPage: 298,
  },
])

const byId = new Map(BESTIARY.map((m) => [m.id, m]))

export function monsterById(id: string): Monster | undefined {
  return byId.get(id)
}

export function monstersByTipo(tipo: MonsterTipo): readonly Monster[] {
  return BESTIARY.filter((m) => m.tipo === tipo)
}

export function monstersByNdRange(min: number, max: number): readonly Monster[] {
  return BESTIARY.filter((m) => m.nd >= min && m.nd <= max)
}

export function monstersBySize(size: MonsterSize): readonly Monster[] {
  return BESTIARY.filter((m) => m.size === size)
}
