import { attr, autoPower, electivePower, power, trained } from './_helpers'
import type { ClassPower } from '../types'

const C = 'Bardo'

/**
 * PDF Cap 1 (Bardo, p43-45, Tabela 1-7). Auto: Inspiração L1 + scaling
 * (+1/+2/+3/+4/+5 em L1/5/9/13/17). Magias scaling. Eclético L2.
 * Artista Completo L20. 19 power slots L2-L20.
 *
 * Inspiração: ação padrão + 2 PM. Aliados (e o bardo) em alcance curto ganham
 * +1 em testes de perícia até fim da cena. A cada 4 níveis (L5/9/13/17) o
 * bardo pode gastar +2 PM para aumentar bônus em +1.
 */
export const BARDO_POWERS: ClassPower[] = [
  autoPower(C, 1, 'Inspiração +1',
    'Ação padrão + 2 PM: aliados (incluindo bardo) em alcance curto recebem +1 em testes de perícia até fim da cena. A cada 4 níveis pode gastar +2 PM para aumentar bônus em +1.',
  ),
  autoPower(C, 1, 'Magias (1° círculo)',
    'Pode lançar magias arcanas de 3 escolas escolhidas. Atributo-chave: Carisma. Pode lançar com armaduras leves sem teste de Misticismo.',
  ),
  autoPower(C, 2, 'Eclético',
    'Ao fazer teste de perícia, gasta 1 PM para receber benefícios de ser treinado nessa perícia para este teste. Não consome slot de poder.',
  ),
  autoPower(C, 5, 'Inspiração +2',
    'Bônus base de Inspiração sobe para +2.',
  ),
  autoPower(C, 6, 'Magias (2° círculo)',
    'Pode lançar magias arcanas de 2° círculo.',
  ),
  autoPower(C, 9, 'Inspiração +3',
    'Bônus base de Inspiração sobe para +3.',
  ),
  autoPower(C, 10, 'Magias (3° círculo)',
    'Pode lançar magias arcanas de 3° círculo.',
  ),
  autoPower(C, 13, 'Inspiração +4',
    'Bônus base de Inspiração sobe para +4.',
  ),
  autoPower(C, 14, 'Magias (4° círculo)',
    'Pode lançar magias arcanas de 4° círculo.',
  ),
  autoPower(C, 17, 'Inspiração +5',
    'Bônus base de Inspiração sobe para +5.',
  ),
  autoPower(C, 20, 'Artista Completo',
    'Capstone: pode usar Inspiração como ação livre. Sob Inspiração, custo em PM de habilidades de bardo (incluindo magias) reduzido à metade.',
  ),

  // Poderes de Bardo (p44-45)
  electivePower(C, 'Arte Mágica',
    'Sob Inspiração, CD para resistir a suas habilidades de bardo +2.'),
  electivePower(C, 'Aumentar Repertório',
    'Aprende magia de qualquer círculo que possa lançar — pertencente às escolas que sabe usar, arcanas ou divinas. Pode escolher várias vezes.'),
  electivePower(C, 'Aumento de Atributo',
    '+1 em um atributo. Apenas uma vez por patamar para um mesmo atributo.'),
  electivePower(C, 'Dança das Lâminas',
    'Quando lança magia de ação padrão, pode gastar 1 PM para fazer ataque corpo-a-corpo como ação livre.',
    { prerequisites: [power('class.bardo.esgrima-magica')], minLevel: 10 }),
  electivePower(C, 'Esgrima Mágica',
    'Sob Inspiração, pode substituir testes de Luta por testes de Atuação (ataques corpo-a-corpo com armas leves ou de uma mão).'),
  electivePower(C, 'Estrelato',
    '+5 em perícias baseadas em Carisma para impressionar plateia. Pode ser difícil passar despercebido em cidades grandes.',
    { minLevel: 6 }),
  electivePower(C, 'Fascinar em Massa',
    'Música: Balada Fascinante afeta todas criaturas em alcance da música por +2 PM.',
    { prerequisites: [power('class.bardo.musica-balada-fascinante')] }),
  electivePower(C, 'Golpe Elemental',
    'Sob Inspiração, ao acertar ataque corpo-a-corpo, gasta 1 PM para causar 1d6 dano elemental extra. Cada 4 níveis, +1d6.',
    { prerequisites: [power('class.bardo.golpe-magico')] }),
  electivePower(C, 'Golpe Mágico',
    'Sob Inspiração, ao acertar ataque corpo-a-corpo, recebe 2 PM temporários cumulativos (máx = nível por cena). Desaparecem fim cena.',
    { prerequisites: [power('class.bardo.esgrima-magica')] }),
  electivePower(C, 'Inspiração Marcial',
    'Bônus da sua Inspiração também se aplica a rolagens de dano.'),
  electivePower(C, 'Lendas e Histórias',
    'Em teste de Conhecimento/Misticismo/Nobreza/Religião para identificar criaturas ou itens mágicos, gasta 1 PM para rolar novamente.',
    { prerequisites: [attr('intelligence', 1)] }),
  electivePower(C, 'Manipular',
    'Gasta 1 PM para fazer criatura fascinada por você ficar enfeitiçada até fim da cena. Vontade CD Car anula.',
    { prerequisites: [power('class.bardo.musica-balada-fascinante')] }),
  electivePower(C, 'Manipular em Massa',
    'Manipular afeta todas criaturas fascinadas em alcance curto por +2 PM.',
    { prerequisites: [power('class.bardo.fascinar-em-massa'), power('class.bardo.manipular')], minLevel: 10 }),
  electivePower(C, 'Mestre dos Sussurros',
    'Dissimulado e atento: em teste Investigação para interrogar ou Enganação para intriga, rola 2x e usa melhor. Pode fazer em 1 min em ambientes sociais.',
    { prerequisites: [attr('charisma', 1), trained('Enganação'), trained('Investigação')] }),
  electivePower(C, 'Música: Balada Fascinante',
    'Teste de Atuação oposto pelo teste de Vontade de criatura no alcance. Se passar, fica fascinada enquanto bardo se concentrar. Música.'),
  electivePower(C, 'Música: Canção Assustadora',
    'Teste Atuação oposto Vontade. Alvos que falharem ficam abalados até fim da cena. Alvos que passarem ficam imunes por 1 dia. Música.'),
  electivePower(C, 'Música: Melodia Curativa',
    'Criaturas à sua escolha em alcance da música recuperam 1d6 PV. Pode gastar mais PM: cada PM extra aumenta cura em +1d6 PV. Música.'),
  electivePower(C, 'Música: Melodia Restauradora',
    'Quando usa Música Melodia Curativa, gasta +2 PM para remover 1 condição escolhida (abalado, alquebrado, apavorado, atordoado, cego, confuso, exausto, fatigado etc.).',
    { prerequisites: [power('class.bardo.musica-melodia-curativa')] }),
  electivePower(C, 'Paródia',
    'Uma vez por rodada, ao ver criatura lançar magia em alcance médio, paga 1 PM e teste Atuação (CD 15 + custo em PM da magia). Se passar, pode lançar a magia até fim do próximo turno.'),
  electivePower(C, 'Prestidigitação',
    'Ação padrão para lançar magia com execução completa ou menor. Teste Atuação CD 15 + custo PM. Se passar, lança como ação livre. Se falhar, gasta PM mas magia falha.',
    { minLevel: 6 }),
]
