import { attr, autoPower, electivePower, power, trained } from './_helpers'
import type { ClassPower } from '../types'

const C = 'Bucaneiro'

/**
 * PDF Cap 1 (Bucaneiro, p46-48, Tabela 1-8). Auto: Audácia + Insolência L1.
 * Evasão L2 + Aprimorada L10. Esquiva Sagaz +1/+2/+3/+4/+5 em L3/7/11/15/19.
 * Panache L5. Sorte de Nimb L20. 19 power slots L2-L20.
 */
export const BUCANEIRO_POWERS: ClassPower[] = [
  autoPower(C, 1, 'Audácia',
    'Em teste de perícia, gasta 2 PM para somar Carisma no teste. Não vale para testes de ataque.',
  ),
  autoPower(C, 1, 'Insolência',
    'Soma Carisma na Defesa, limitado pelo nível. Exige liberdade de movimentos (não funciona em armadura pesada ou imóvel).',
  ),
  autoPower(C, 2, 'Evasão',
    'Em teste de Reflexos que reduziria dano à metade, sucesso = 0 dano. Falha = dano normal. Exige liberdade de movimentos.',
  ),
  autoPower(C, 3, 'Esquiva Sagaz +1',
    '+1 Defesa e Reflexos. Sobe a cada 4 níveis (+2 em L7, +3 em L11, +4 em L15, +5 em L19). Exige liberdade de movimentos.',
  ),
  autoPower(C, 5, 'Panache',
    'Quando faz crítico em combate ou reduz inimigo a 0 PV, recupera 1 PM.',
  ),
  autoPower(C, 7, 'Esquiva Sagaz +2',
    'Bônus de Esquiva Sagaz sobe para +2.',
  ),
  autoPower(C, 10, 'Evasão Aprimorada',
    'Em teste de Reflexos que reduziria dano à metade: sucesso = 0 dano, falha = metade. Exige liberdade de movimentos.',
  ),
  autoPower(C, 11, 'Esquiva Sagaz +3',
    'Bônus de Esquiva Sagaz sobe para +3.',
  ),
  autoPower(C, 15, 'Esquiva Sagaz +4',
    'Bônus de Esquiva Sagaz sobe para +4.',
  ),
  autoPower(C, 19, 'Esquiva Sagaz +5',
    'Bônus de Esquiva Sagaz sobe para +5.',
  ),
  autoPower(C, 20, 'Sorte de Nimb',
    'Capstone: gasta 5 PM para refazer um teste. Qualquer 11+ no segundo dado conta como 20 natural.',
  ),

  // Poderes de Bucaneiro (p47-48)
  electivePower(C, 'Abusar dos Fracos',
    'Ao atacar criatura sob condição de medo, dano aumenta em um passo.',
    { prerequisites: [power('class.bucaneiro.flagelo-dos-mares')] }),
  electivePower(C, 'Amigos no Porto',
    'Em comunidade portuária, teste Carisma CD 10. Se passar, encontra amigo para favor ou parceiro veterano por 1 dia.',
    { prerequisites: [attr('charisma', 1)], minLevel: 6 }),
  electivePower(C, 'Aparar',
    'Quando atacado, gasta 1 PM para teste de ataque com bônus = nível. Se resultado maior que do oponente, evita ataque. Exige arma leve ou ágil.',
    { prerequisites: [power('class.bucaneiro.esgrimista')] }),
  electivePower(C, 'Apostador',
    'Gasta 1 dia em mesa de wyrt/jogo. Teste Jogatina vs CD T$ 100 (CD 15) até T$ 1.600 (CD 35). Sucesso = ganha valor. Falha = perde valor.',
    { prerequisites: [trained('Jogatina')] }),
  electivePower(C, 'Ataque Acrobático',
    'Ao se aproximar com salto/pirueta (Atletismo/Acrobacia para mover) e atacar no mesmo turno, recebe +2 nesse teste e na rolagem de dano.'),
  electivePower(C, 'Aumento de Atributo',
    '+1 em um atributo. Apenas uma vez por patamar para um mesmo atributo.'),
  electivePower(C, 'Aventureiro Ávido',
    'Uma vez por rodada, gasta 5 PM para ação padrão ou movimento adicional. Se possuir Surto Heroico, custo cai para -2 PM.'),
  electivePower(C, 'Bravata Audaz',
    'Jura façanha específica (roubar tesouro de Sckhar, beijo do príncipe etc.) até fim da aventura. Se cumprir, PM aumentam +2 por nível até fim da aventura.'),
  electivePower(C, 'Bravata Imprudente',
    'Na primeira rodada de combate, jura derrotar inimigos com restrição (mão nas costas, vendado, cego). Se vencer com restrição, +2 ataque e +2 margem de ameaça até fim da aventura.'),
  electivePower(C, 'En Garde',
    'Ação de movimento + 1 PM: até fim da cena, em arma corpo-a-corpo leve ou ágil, recebe +2 margem de ameaça com essas armas e +2 Defesa.',
    { prerequisites: [power('class.bucaneiro.esgrimista')] }),
  electivePower(C, 'Esgrimista',
    'Quando usa arma corpo-a-corpo leve ou ágil, soma Inteligência nas rolagens de dano (limitado pelo seu nível).',
    { prerequisites: [attr('intelligence', 1)] }),
  electivePower(C, 'Flagelo dos Mares',
    'Aprende e pode lançar Amedrontar (atributo-chave Carisma). Não é magia.',
    { prerequisites: [trained('Intimidação')] }),
  electivePower(C, 'Folião',
    'Em festas/tavernas/bailes, +2 em testes de perícias baseadas em Carisma. Atitude das pessoas em relação a você melhora 1 categoria.',
    { prerequisites: [attr('charisma', 1)] }),
  electivePower(C, 'Grudar o Cano',
    'Em ataque a distância com arma de fogo contra oponente adjacente, sem penalidade de -5 e dano aumenta em um passo.',
    { prerequisites: [trained('Luta'), power('class.bucaneiro.pistoleiro')] }),
  electivePower(C, 'Pernas do Mar',
    '+2 Acrobacia e Atletismo. Não fica desprevenido quando se equilibrando ou escalando. Deslocamento não reduzido à metade.'),
  electivePower(C, 'Pistoleiro',
    'Proficiência com armas de fogo. +2 nas rolagens de dano com armas de fogo.'),
  electivePower(C, 'Presença Paralisante',
    'Soma Carisma em Iniciativa. Se for primeiro a agir, ganha ação padrão extra na primeira rodada.',
    { prerequisites: [attr('charisma', 1)], minLevel: 4 }),
  electivePower(C, 'Ripostar',
    'Quando aparar evita ataque, gasta 1 PM para fazer ataque corpo-a-corpo imediato contra atacante (se em alcance).',
    { prerequisites: [power('class.bucaneiro.aparar')], minLevel: 12 }),
  electivePower(C, 'Touché',
    'Ao se aproximar de inimigo e atacar com arma corpo-a-corpo no mesmo turno, gasta 2 PM para aumentar dano em um passo e +5 margem de ameaça.',
    { prerequisites: [power('class.bucaneiro.esgrimista')], minLevel: 10 }),
]
