import { anyPower, attr, autoPower, electivePower, power, trained } from './_helpers'
import type { ClassPower } from '../types'

const C = 'Caçador'

/**
 * PDF Cap 1 (Caçador, p49-51, Tabela 1-9). Auto: Marca da Presa scaling
 * (+1d4 L1, +1d8 L5, +1d12 L9, +2d8 L13, +2d10 L17). Rastreador L1.
 * Explorador L3 (+1 terreno em L7/11/15/19). Caminho do Explorador L5.
 * Mestre Caçador L20. 19 power slots L2-L20.
 */
export const CACADOR_POWERS: ClassPower[] = [
  autoPower(C, 1, 'Marca da Presa +1d4',
    'Ação de movimento + 1 PM: analisa criatura em alcance curto. Até fim da cena, recebe +1d4 nas rolagens de dano contra ela. A cada 4 níveis pode gastar +1 PM para aumentar bônus (vide tabela).',
  ),
  autoPower(C, 1, 'Rastreador',
    '+2 em Sobrevivência. Move-se em deslocamento normal enquanto rastreia sem penalidade no teste.',
  ),
  autoPower(C, 3, 'Explorador',
    'Escolha um tipo de terreno (aquático, ártico, colina, deserto, floresta, montanha, pântano, planície, subterrâneo, urbano). Quando nele, soma Sabedoria (mín +1) na Defesa e em testes de Acrobacia, Atletismo, Furtividade, Percepção e Sobrevivência. L11 inclui Tormenta. A cada 4 níveis (L7/11/15/19), escolhe outro terreno ou aumenta bônus em terreno já escolhido em +2.',
  ),
  autoPower(C, 5, 'Marca da Presa +1d8',
    'Bônus de dano da Marca da Presa sobe para +1d8.',
  ),
  autoPower(C, 5, 'Caminho do Explorador',
    'Pode atravessar terrenos difíceis sem redução em seu deslocamento e CD para rastreá-lo aumenta em +10. Só funciona em terrenos com Explorador.',
  ),
  autoPower(C, 9, 'Marca da Presa +1d12',
    'Bônus de dano da Marca da Presa sobe para +1d12.',
  ),
  autoPower(C, 13, 'Marca da Presa +2d8',
    'Bônus de dano da Marca da Presa sobe para +2d8.',
  ),
  autoPower(C, 17, 'Marca da Presa +2d10',
    'Bônus de dano da Marca da Presa sobe para +2d10.',
  ),
  autoPower(C, 20, 'Mestre Caçador',
    'Capstone: pode usar Marca da Presa como ação livre. Quando usa, +2 margem de ameaça contra criatura. Se reduzir alvo marcado a 0 PV, recupera 5 PM.',
  ),

  // Poderes de Caçador (p50-51)
  electivePower(C, 'Ambidestria',
    'Ao usar duas armas (uma leve) na ação agredir, ataca com cada arma. Sofre -2 em todos testes de ataque até próximo turno.',
    { prerequisites: [attr('dexterity', 2)] }),
  electivePower(C, 'Armadilha: Arataca',
    'Vítima sofre 2d6 perfuração e fica agarrada. Escapa com ação padrão e teste de Força ou Acrobacia (CD Sab).'),
  electivePower(C, 'Armadilha: Espinhos',
    'Vítima sofre 6d6 perfuração. Reflexos (CD Sab) reduz à metade.'),
  electivePower(C, 'Armadilha: Laço',
    'Vítima testa Reflexos (CD Sab). Passa = fica caída. Falha = agarrada.'),
  electivePower(C, 'Armadilha: Rede',
    'Criaturas na área ficam enredadas. Vítima escapa com ação padrão + Força/Acrobacia (CD 25). Área = terreno difícil.'),
  electivePower(C, 'Armadilheiro',
    'Soma Sabedoria nas rolagens de dano e CD de suas armadilhas (cumulativo).',
    { prerequisites: [anyPower(['class.cacador.armadilha-arataca', 'class.cacador.armadilha-espinhos', 'class.cacador.armadilha-laco', 'class.cacador.armadilha-rede'])], minLevel: 5 }),
  electivePower(C, 'Arqueiro',
    'Em arma de ataque à distância, soma Sabedoria nas rolagens de dano (limitado pelo seu nível).',
    { prerequisites: [attr('wisdom', 1)] }),
  electivePower(C, 'Aumento de Atributo',
    '+1 em um atributo. Apenas uma vez por patamar para um mesmo atributo.'),
  electivePower(C, 'Bote',
    'Quando faz investida com duas armas, gasta 1 PM para ataque adicional com arma secundária.',
    { prerequisites: [power('class.cacador.ambidestria')], minLevel: 6 }),
  electivePower(C, 'Camuflagem',
    'Gasta 2 PM para se esconder sem camuflagem/cobertura.',
    { minLevel: 6 }),
  electivePower(C, 'Chuva de Lâminas',
    'Uma vez por rodada, ao usar Ambidestria, paga 2 PM para fazer ataque adicional com arma primária.',
    { prerequisites: [attr('dexterity', 4), power('class.cacador.ambidestria')], minLevel: 12 }),
  electivePower(C, 'Companheiro Animal',
    'Recebe animal companheiro inicial. Evolui para veterano L7 e mestre L15. Tipos: ajudante, assassino, atirador, combatente, fortão, guardião, perseguidor ou montaria.',
    { prerequisites: [attr('charisma', 1), trained('Adestramento')] }),
  electivePower(C, 'Elo com a Natureza',
    'Soma Sabedoria no PM total. Aprende e pode lançar Caminhos da Natureza (atributo-chave Sab).',
    { prerequisites: [attr('wisdom', 1)], minLevel: 3 }),
  electivePower(C, 'Emboscar',
    'Gasta 2 PM para realizar ação padrão adicional em seu turno. Só pode na primeira rodada de combate.',
    { prerequisites: [trained('Furtividade')] }),
  electivePower(C, 'Empatia Selvagem',
    'Comunica-se com animais. Pode usar Adestramento com animais para mudar atitude e persuasão (como Diplomacia).'),
  electivePower(C, 'Escaramuça',
    'Quando se move 6m ou mais, +2 Defesa e Reflexos e +1d8 nas rolagens de dano em alcance curto até início do próximo turno. Não funciona em armadura pesada.',
    { prerequisites: [attr('dexterity', 2)], minLevel: 6 }),
  electivePower(C, 'Escaramuça Superior',
    'Bônus de Escaramuça sobe para +5 Defesa/Reflexos e +1d12 dano.',
    { prerequisites: [power('class.cacador.escaramuca')], minLevel: 12 }),
  electivePower(C, 'Espreitar',
    'Quando usa Marca da Presa, +1 em testes de perícia contra criatura marcada. Bônus +1 para cada PM gasto. Dobra com Inimigo.'),
  electivePower(C, 'Ervas Curativas',
    'Ação completa + PM (limitado por Sab) para aplicar ervas: cada PM cura 2d6 PV ou remove condição envenenada de criatura adjacente.'),
  electivePower(C, 'Ímpeto',
    'Gasta 1 PM para aumentar deslocamento em +6m por uma rodada.'),
  electivePower(C, 'Inimigo de (Criatura)',
    'Escolha tipo de criatura (animal/construto/espírito/monstro/morto-vivo, ou duas raças humanoides). Marca da Presa contra criatura desse tipo dobra dados de bônus de dano. Pode escolher várias vezes.'),
  electivePower(C, 'Olho do Falcão',
    'Pode usar Marca da Presa em criaturas em alcance longo.'),
  electivePower(C, 'Ponto Fraco',
    'Quando usa Marca da Presa, +2 margem de ameaça contra criatura marcada. Dobra com Inimigo.'),
]
