import { autoPower, classChoice, electivePower, power } from './_helpers'
import type { ClassPower } from '../types'

const C = 'Cavaleiro'

/**
 * PDF Cap 1 (Cavaleiro, p52-55, Tabela 1-10). Auto: Código de Honra +
 * Baluarte +2 L1. Duelo +2 L2. Baluarte +4 + Caminho do Cavaleiro L5.
 * Baluarte (aliados adjacentes) + Duelo +3 L7. Baluarte +6 L9. Resoluto L11.
 * Duelo +4 L12. Baluarte +8 L13. Baluarte (aliados em alcance curto) L15.
 * Baluarte +10 + Duelo +5 L17. Bravura Final L20. 19 power slots L2-L20.
 */
export const CAVALEIRO_POWERS: ClassPower[] = [
  autoPower(C, 1, 'Código de Honra',
    'Não pode atacar oponente pelas costas (sem flanqueamento), caído, desprevenido ou incapaz de lutar. Se violar, perde todos os PM e só recupera no próximo dia.',
  ),
  autoPower(C, 1, 'Baluarte +2',
    'Quando sofre ataque ou faz teste de resistência, gasta 1 PM para +2 Defesa e testes de resistência até início do próximo turno. A cada 4 níveis pode gastar +1 PM para aumentar bônus em +2.',
  ),
  autoPower(C, 2, 'Duelo +2',
    'Gasta 2 PM para escolher oponente em alcance curto. +2 nos testes de ataque e rolagens de dano contra ele até fim da cena. Se atacar outro oponente, bônus termina.',
  ),
  autoPower(C, 5, 'Baluarte +4',
    'Bônus de Baluarte sobe para +4.',
  ),
  autoPower(C, 5, 'Caminho do Cavaleiro',
    'Escolha entre Bastião ou Montaria.',
  ),
  autoPower(C, 7, 'Baluarte (aliados adjacentes)',
    'Pode gastar 2 PM adicionais para fornecer mesmo bônus de Baluarte a todos aliados adjacentes.',
  ),
  autoPower(C, 7, 'Duelo +3',
    'Bônus de Duelo sobe para +3.',
  ),
  autoPower(C, 9, 'Baluarte +6',
    'Bônus de Baluarte sobe para +6.',
  ),
  autoPower(C, 11, 'Resoluto',
    'Gasta 1 PM para refazer teste de resistência contra condição. Segundo teste recebe +5. Apenas uma vez por efeito.',
  ),
  autoPower(C, 12, 'Duelo +4',
    'Bônus de Duelo sobe para +4.',
  ),
  autoPower(C, 13, 'Baluarte +8',
    'Bônus de Baluarte sobe para +8.',
  ),
  autoPower(C, 15, 'Baluarte (aliados em alcance curto)',
    'Pode gastar 5 PM adicionais para fornecer Baluarte a todos aliados em alcance curto.',
  ),
  autoPower(C, 17, 'Baluarte +10',
    'Bônus de Baluarte sobe para +10.',
  ),
  autoPower(C, 17, 'Duelo +5',
    'Bônus de Duelo sobe para +5.',
  ),
  autoPower(C, 20, 'Bravura Final',
    'Capstone: se reduzido a 0 PV ou menos, paga 3 PM para continuar consciente e em pé. Sustentada. Ao encerrar, sofre PV atuais (cai/morre se for caso).',
  ),

  // Poderes de Cavaleiro (p53-55)
  electivePower(C, 'Armadura da Honra',
    'No início de cada cena, recebe PV temporários = nível + Carisma. Duram até fim da cena.'),
  electivePower(C, 'Aumento de Atributo',
    '+1 em um atributo. Apenas uma vez por patamar para um mesmo atributo.'),
  electivePower(C, 'Autoridade Feudal',
    'Em locais com influência (mestre decide), gasta 1 hora + 2 PM para conclamar parceiro iniciante até fim da aventura.',
    { minLevel: 6 }),
  electivePower(C, 'Desprezar os Covardes',
    'Redução de dano 5 contra ataques de oponentes caídos, desprevenidos ou flanqueados.'),
  electivePower(C, 'Escudeiro',
    'Recebe parceiro escudeiro que cuida do equipamento. Suas armas recebem +1 nas rolagens de dano e armadura concede +1 Defesa. Pode gastar 1 PM para ação de movimento extra (levantar/sacar/etc).'),
  electivePower(C, 'Especialização em Armadura',
    'Em armadura pesada, RD 5 (cumulativa com RD por Bastião).',
    { minLevel: 12 }),
  electivePower(C, 'Estandarte',
    'Início de cena, você e aliados que possam ver estandarte recebem PV temporários = Carisma (mín 1). Duram até fim da cena.',
    { prerequisites: [power('class.cavaleiro.titulo')], minLevel: 14 }),
  electivePower(C, 'Etiqueta',
    '+2 Diplomacia e Nobreza. Em teste dessas perícias, gasta 1 PM para rolá-lo novamente.'),
  electivePower(C, 'Investida Destruidora',
    'Em ação investida, gasta 2 PM para causar +2d8 dano. Decisão antes de rolar ataque.'),
  electivePower(C, 'Montaria Corajosa',
    'Montaria concede +1d6 nas rolagens de dano corpo-a-corpo (cumulativo com bônus de parceiro).',
    { prerequisites: [power('class.cavaleiro.caminho-montaria')] }),
  electivePower(C, 'Pajem',
    'Recebe parceiro pajem. +2 Diplomacia (sempre aprumado). Condição de descanso 1 categoria acima.'),
  electivePower(C, 'Postura: Ariete Implacável',
    'Aumenta bônus de ataque em investidas em +2 (ou mais por 2 PM). Investida contra construto/objeto = +2d8. Postura de Combate.'),
  electivePower(C, 'Postura: Castigo de Ferro',
    'Sempre que aliado adjacente sofre ataque corpo-a-corpo, gasta 1 PM para ataque contra criatura que o atacou. Postura de Combate.'),
  electivePower(C, 'Postura: Foco de Batalha',
    'Sempre que inimigo atacar você, recebe 1 PM temporário cumulativo. Máximo = nível por cena. Postura de Combate.'),
  electivePower(C, 'Postura: Muralha Intransponível',
    'Precisa empunhar escudo. +1 Defesa e Reflexos. Quando sofre efeito que permite Reflexos para reduzir dano à metade, não sofre dano algum se passar. Postura de Combate.'),
  electivePower(C, 'Postura: Provocação Petulante',
    'Inimigos em alcance curto fazem Vontade CD Car ou só podem atacar você. Mental. Postura de Combate.'),
  electivePower(C, 'Postura: Torre Inabalável',
    'Imune a qualquer tentativa de tirá-lo do lugar. Soma Constituição na Defesa e pode substituir testes de Reflexos e Vontade por Fortitude. Não pode se deslocar. Postura de Combate.'),
  electivePower(C, 'Solidez',
    'Se está usando escudo, soma bônus na Defesa concedido pelo escudo em testes de resistência.'),
  electivePower(C, 'Título',
    'Adquire título de nobreza. Define benefícios com mestre. Recebe 20 TO/nível ou parceiro veterano.',
    { prerequisites: [power('class.cavaleiro.autoridade-feudal')], minLevel: 10 }),
  electivePower(C, 'Torre Armada',
    'Quando inimigo te ataca, gasta 1 PM para +5 nas rolagens de dano contra esse inimigo no próximo turno.'),

  // Caminhos do Cavaleiro (escolhidos no L5) — gated by caminho choice.
  electivePower(C, 'Caminho: Bastião',
    'Em armadura pesada, recebe Redução de Dano 5 (cumulativa com Especialização em Armadura).',
    {
      minLevel: 5,
      prerequisites: [
        classChoice(C, 'caminho', 'Caminho do Bastião escolhido', {
          allowed: ['bastiao'],
        }),
      ],
    }),
  electivePower(C, 'Caminho: Montaria',
    'Recebe cavalo de guerra. +5 em testes de Adestramento e Cavalgar com ela. L11 vira parceiro mestre. Se morrer, pode comprar/treinar outra (1 semana).',
    {
      minLevel: 5,
      prerequisites: [
        classChoice(C, 'caminho', 'Caminho da Montaria escolhido', {
          allowed: ['montaria'],
        }),
      ],
    }),
]
