import { attr, autoPower, electivePower, power, trained } from './_helpers'
import type { ClassPower } from '../types'

const C = 'Druida'

/**
 * PDF Cap 1 (Druida, p60-63, Tabela 1-12). Auto: Devoto Fiel + Empatia
 * Selvagem + Magias L1. Caminho dos Ermos L2. Magias 2°/3°/4° em L6/10/14.
 * Força da Natureza L20. 19 power slots L2-L20.
 *
 * Druidas escolhem 3 escolas de magia (permanente). Apenas magias dessas
 * escolas podem ser lançadas. Não usam armaduras de metal.
 */
export const DRUIDA_POWERS: ClassPower[] = [
  autoPower(C, 1, 'Devoto Fiel',
    'Torna-se devoto de deus disponível para druidas (Allihanna, Megalokk ou Oceano). Recebe DOIS poderes concedidos.',
  ),
  autoPower(C, 1, 'Empatia Selvagem',
    'Pode se comunicar com animais via linguagem corporal e vocalizações. Pode usar Adestramento com animais para mudar atitude e persuasão (como Diplomacia).',
  ),
  autoPower(C, 1, 'Magias (1° círculo)',
    'Escolha 3 escolas de magia (permanente). Pode lançar magias divinas de 1° círculo pertencentes a essas escolas. Atributo-chave: Sabedoria.',
  ),
  autoPower(C, 2, 'Caminho dos Ermos',
    'Pode atravessar terrenos difíceis sem redução em seu deslocamento. CD para rastreá-lo aumenta em +10. Só em terrenos naturais.',
  ),
  autoPower(C, 6, 'Magias (2° círculo)',
    'Pode lançar magias divinas de 2° círculo das escolas escolhidas.',
  ),
  autoPower(C, 10, 'Magias (3° círculo)',
    'Pode lançar magias divinas de 3° círculo das escolas escolhidas.',
  ),
  autoPower(C, 14, 'Magias (4° círculo)',
    'Pode lançar magias divinas de 4° círculo das escolas escolhidas.',
  ),
  autoPower(C, 20, 'Força da Natureza',
    'Capstone: custo em PM de suas magias diminui em -2 PM e CD delas aumenta em +2. Bônus dobram (-4 PM e +4 CD) se em terreno natural.',
  ),

  // Poderes de Druida (p61-63)
  electivePower(C, 'Aspecto da Primavera',
    'Aprende magia de encantamento ou ilusão (arcana ou divina) de qualquer círculo que possa lançar. Custo dessas magias -1 PM, mais reduzido em +1 por cada PM ate Cha (mín 1).'),
  electivePower(C, 'Aspecto do Verão',
    'Aprende magia de transmutação (arcana ou divina) de qualquer círculo que possa lançar. Pode gastar 1 PM para cobrir arma com chamas até fim da cena. Arma causa +1d6 dano de fogo. Acerto = recebe 1 PM temp (máx = nível).'),
  electivePower(C, 'Aspecto do Outono',
    'Aprende magia de necromancia (arcana ou divina) de qualquer círculo que possa lançar. Pode gastar 1 PM para -2 em testes de resistência de todos inimigos em alcance curto.'),
  electivePower(C, 'Aspecto do Inverno',
    'Aprende magia de evocação (arcana ou divina) de qualquer círculo que possa lançar. Recebe RD 5 contra frio. Suas magias de frio causam +1 dano por dado.'),
  electivePower(C, 'Aumento de Atributo',
    '+1 em um atributo. Apenas uma vez por patamar para um mesmo atributo.'),
  electivePower(C, 'Companheiro Animal',
    'Recebe animal companheiro. Tipos: ajudante, assassino, atirador, combatente, fortão, guardião, perseguidor, montaria.',
    { prerequisites: [attr('charisma', 1), trained('Adestramento')] }),
  electivePower(C, 'Companheiro Animal Aprimorado',
    'Escolha um companheiro animal. Recebe segundo tipo diferente, ganhando bônus do seu nível.',
    { prerequisites: [power('class.druida.companheiro-animal')], minLevel: 6 }),
  electivePower(C, 'Companheiro Animal Lendário',
    'Escolha um companheiro animal. Dobra os bônus concedidos por seu tipo original.',
    { prerequisites: [power('class.druida.companheiro-animal')], minLevel: 18 }),
  electivePower(C, 'Companheiro Animal Mágico',
    'Escolha um companheiro animal. Recebe segundo tipo (adepto/destruidor/magivocador/médico).',
    { prerequisites: [power('class.druida.companheiro-animal')], minLevel: 8 }),
  electivePower(C, 'Coração da Selva',
    'CD para resistir a efeitos de veneno +2 e seus efeitos causam +1 perda de vida por dado.'),
  electivePower(C, 'Espírito dos Equinócios',
    'Gasta 4 PM para ficar em equilíbrio com o mundo. Até fim da cena, ao rolar um dado, pode rolar novamente qualquer resultado 1.',
    { prerequisites: [power('class.druida.aspecto-da-primavera'), power('class.druida.aspecto-do-outono')], minLevel: 10 }),
  electivePower(C, 'Espírito dos Solstícios',
    'Transita entre extremos do mundo natural. Em magia com efeitos variáveis, paga +4 PM para maximizar valores (ex: Curar Ferimentos aprimorada 5d8+5 vira 45 PV).',
    { prerequisites: [power('class.druida.aspecto-do-inverno'), power('class.druida.aspecto-do-verao')], minLevel: 10 }),
  electivePower(C, 'Força dos Penhascos',
    '+2 em Fortitude. Quando sofre dano em contato com solo/superfície de pedra, paga PM (limitado por Sab) para reduzir dano em 10 por PM gasto.',
    { minLevel: 4 }),
  electivePower(C, 'Forma Primal',
    'Em Forma Selvagem, transforma-se em fera primal: recebe benefícios de DOIS tipos de animais (bônus iguais não acumulam).',
    { prerequisites: [power('class.druida.forma-selvagem')], minLevel: 18 }),
  electivePower(C, 'Forma Selvagem',
    'Ação completa + 3 PM: transforma-se em animal. Adquire características da forma escolhida. Equipamento desaparece. Pode reverter ao normal quando quiser. Formas: Ágil, Feroz, Resistente, Sorrateira, Veloz.'),
  electivePower(C, 'Forma Selvagem Aprimorada',
    'Em Forma Selvagem, gasta 6 PM total para forma aprimorada (mais poderosa).',
    { prerequisites: [power('class.druida.forma-selvagem')], minLevel: 6 }),
  electivePower(C, 'Forma Selvagem Superior',
    'Em Forma Selvagem, gasta 10 PM total para forma superior (mais poderosa ainda).',
    { prerequisites: [power('class.druida.forma-selvagem-aprimorada')], minLevel: 12 }),
  electivePower(C, 'Liberdade da Pradaria',
    '+2 Reflexos. Se for ar livre, ao lançar magia paga 1 PM para aumentar alcance um passo.'),
  electivePower(C, 'Magia Natural',
    'Em forma selvagem pode lançar magias e empunhar catalisadores/esotéricos.',
    { prerequisites: [power('class.druida.forma-selvagem')] }),
  electivePower(C, 'Presas Afiadas',
    'Margem de ameaça de suas armas naturais +2.'),
  electivePower(C, 'Segredos da Natureza',
    'Aprende 2 magias de qualquer círculo que possa lançar — devem pertencer às escolas que sabe usar (arcanas ou divinas). Pode escolher várias vezes.'),
  electivePower(C, 'Tranquilidade dos Lagos',
    '+2 Vontade. Se portando recipiente com água, uma vez por rodada, em teste de resistência paga 1 PM para refazer rolagem.'),
]
