import { attr, autoPower, electivePower, power, trained } from './_helpers'
import type { ClassPower } from '../types'

const C = 'Guerreiro'

/**
 * PDF Cap 1 (Guerreiro, p64-66, Tabela 1-13). Auto: Ataque Especial +4 L1.
 * Durão L3. Ataque Especial +8 L5. Ataque Extra L6. Ataque Especial +12 L9,
 * +16 L13, +20 L17. Campeão L20. 19 power slots L2-L20.
 */
export const GUERREIRO_POWERS: ClassPower[] = [
  autoPower(C, 1, 'Ataque Especial +4',
    'Em ataque, gasta 1 PM para +4 no teste de ataque ou rolagem de dano. A cada 4 níveis pode gastar +1 PM para aumentar bônus em +4. Pode dividir bônus.',
  ),
  autoPower(C, 3, 'Durão',
    'Quando sofre dano, gasta 3 PM para reduzir esse dano à metade.',
  ),
  autoPower(C, 5, 'Ataque Especial +8',
    'Bônus base do Ataque Especial sobe para +8.',
  ),
  autoPower(C, 6, 'Ataque Extra',
    'Quando usa ação agredir, gasta 2 PM para realizar ataque adicional uma vez por rodada.',
  ),
  autoPower(C, 9, 'Ataque Especial +12',
    'Bônus base do Ataque Especial sobe para +12.',
  ),
  autoPower(C, 13, 'Ataque Especial +16',
    'Bônus base do Ataque Especial sobe para +16.',
  ),
  autoPower(C, 17, 'Ataque Especial +20',
    'Bônus base do Ataque Especial sobe para +20.',
  ),
  autoPower(C, 20, 'Campeão',
    'Capstone: dano de todos seus ataques aumenta em um passo. Quando faz Ataque Especial ou Golpe Pessoal e acerta o ataque, recupera PM iguais aos gastos nele.',
  ),

  // Poderes de Guerreiro (p65-66)
  electivePower(C, 'Ambidestria',
    'Quando empunha duas armas (uma leve) e faz ação agredir, faz dois ataques (um com cada). Sofre -2 em todos testes de ataque até próximo turno.',
    { prerequisites: [attr('dexterity', 2)] }),
  electivePower(C, 'Arqueiro',
    'Em arma de ataque à distância, soma Sabedoria nas rolagens de dano (limitado pelo nível).',
    { prerequisites: [attr('wisdom', 1)] }),
  electivePower(C, 'Ataque Reflexo',
    'Quando alvo de ataques fica desprevenido ou se move voluntariamente fora do seu alcance, gasta 1 PM para ataque corpo-a-corpo (1x/alvo/rodada).',
    { prerequisites: [attr('dexterity', 1)] }),
  electivePower(C, 'Aumento de Atributo',
    '+1 em um atributo. Apenas uma vez por patamar para um mesmo atributo.'),
  electivePower(C, 'Bater e Correr',
    'Quando faz investida, pode continuar se movendo após ataque até limite de deslocamento. 2 PM = investida sobre terreno difícil sem penalidade.'),
  electivePower(C, 'Destruidor',
    'Quando causa dano corpo-a-corpo com arma de duas mãos, pode rolar novamente qualquer 1 ou 2 da rolagem de dano.',
    { prerequisites: [attr('strength', 1)] }),
  electivePower(C, 'Esgrimista',
    'Quando usa arma corpo-a-corpo leve ou ágil, soma Inteligência nas rolagens de dano (limitado pelo nível).',
    { prerequisites: [attr('intelligence', 1)] }),
  electivePower(C, 'Especialização em Arma',
    'Escolha uma arma. +2 nas rolagens de dano com essa arma. Pode escolher várias vezes para armas diferentes.'),
  electivePower(C, 'Especialização em Armadura',
    'Redução de Dano 5 se usando armadura pesada.',
    { minLevel: 12 }),
  electivePower(C, 'Golpe de Raspão',
    'Uma vez por rodada, quando erra ataque, gasta 2 PM para causar metade do dano (ignorando efeitos que se aplicariam caso acertasse).'),
  electivePower(C, 'Golpe Demolidor',
    'Quando usa manobra quebrar ou ataca objeto, gasta 2 PM para ignorar redução de dano dele.'),
  electivePower(C, 'Golpe Pessoal',
    'Pode desferir Golpe Pessoal — técnica única construída combinando efeitos (Amplo, Atordoante, Brutal, Conjurador, Destruidor, Distante, Elemental, Impactante, Letal, Penetrante, Preciso, Qualquer Arma, Ricocheteante, Teleguiado, Lento, Perto da Morte, Sacrifício). Soma custos. Só com arma específica.',
    { minLevel: 5 }),
  electivePower(C, 'Ímpeto',
    'Gasta 1 PM para aumentar deslocamento em +6m por uma rodada.'),
  electivePower(C, 'Mestre em Arma',
    'Com arma escolhida, dano aumenta em um passo. Quando faz teste de ataque, gasta 2 PM para rolá-lo novamente.',
    { prerequisites: [power('class.guerreiro.especializacao-em-arma')], minLevel: 12 }),
  electivePower(C, 'Planejamento Marcial',
    'Uma vez por dia, gasta 1 hora + 3 PM para escolher um poder de guerreiro ou poder de combate (cujos pré-requisitos cumpra). Recebe benefícios até próximo dia.',
    { prerequisites: [trained('Guerra')], minLevel: 10 }),
  electivePower(C, 'Romper Resistências',
    'Quando faz Ataque Especial, paga 1 PM adicional para ignorar 10 pontos de redução de dano.'),
  electivePower(C, 'Solidez',
    'Se usando escudo, soma bônus na Defesa concedido pelo escudo em testes de resistência.'),
  electivePower(C, 'Tornado de Dor',
    'Ação padrão + 2 PM: golpes giratórios. Ataque corpo-a-corpo contra Defesa de cada inimigo adjacente. Rolagem de dano com +2 cumulativo por acerto.',
    { minLevel: 6 }),
  electivePower(C, 'Valentão',
    '+2 em testes de ataque e rolagens de dano contra oponentes caídos, desprevenidos, flanqueados ou indefesos.'),
]
