import { attr, autoPower, electivePower, note, power, trained } from './_helpers'
import type { ClassPower } from '../types'

const C = 'Inventor'

/**
 * PDF Cap 1 (Inventor, p67-71, Tabela 1-14). Auto: Engenhosidade + Protótipo
 * L1. Fabricar Item Superior (1/2/3/4 melhorias em L2/5/8/11). Comerciante
 * L3. Encontrar Fraqueza L7. Fabricar Item Mágico menor/médio/maior em
 * L9/13/17. Olho do Dragão L10. Obra-Prima L20. 19 power slots L2-L20.
 */
export const INVENTOR_POWERS: ClassPower[] = [
  autoPower(C, 1, 'Engenhosidade',
    'Em teste de perícia, gasta 2 PM para somar Inteligência no teste. Não vale para testes de ataque.',
  ),
  autoPower(C, 1, 'Protótipo',
    'Começa com item superior OU 10 itens alquímicos (preço total até T$ 500).',
  ),
  autoPower(C, 2, 'Fabricar Item Superior (1 melhoria)',
    'Recebe item superior com preço até T$ 2.000. Passa a poder fabricar itens superiores com uma melhoria.',
  ),
  autoPower(C, 3, 'Comerciante',
    'Pode vender itens 10% mais caro (não cumulativo com barganha).',
  ),
  autoPower(C, 5, 'Fabricar Item Superior (2 melhorias)',
    'Pode substituir item por superior com duas melhorias. Passa a fabricar itens superiores com até 2 melhorias.',
  ),
  autoPower(C, 7, 'Encontrar Fraqueza',
    'Ação de movimento + 2 PM: analisa objeto em alcance curto. Ignora redução de dano dele. Em armadura/construto: +2 ataques contra ele.',
  ),
  autoPower(C, 8, 'Fabricar Item Superior (3 melhorias)',
    'Pode substituir item por superior com três melhorias. Passa a fabricar itens superiores com até 3 melhorias.',
  ),
  autoPower(C, 9, 'Fabricar Item Mágico (menor)',
    'Recebe item mágico menor. Passa a fabricar itens mágicos menores.',
  ),
  autoPower(C, 10, 'Olho do Dragão',
    'Ação completa: analisa item. Descobre se é mágico, propriedades e como usá-lo.',
  ),
  autoPower(C, 11, 'Fabricar Item Superior (4 melhorias)',
    'Pode substituir item por superior com quatro melhorias. Passa a fabricar itens superiores com até 4 melhorias.',
  ),
  autoPower(C, 13, 'Fabricar Item Mágico (médio)',
    'Pode substituir item mágico menor por médio. Passa a fabricar itens mágicos médios.',
  ),
  autoPower(C, 17, 'Fabricar Item Mágico (maior)',
    'Pode substituir item mágico médio por maior. Passa a fabricar itens mágicos maiores.',
  ),
  autoPower(C, 20, 'Obra-Prima',
    'Capstone: fabrica obra-prima (benefícios equivalentes a item com 5 melhorias e 4 encantos). Não gasta dinheiro, tempo ou PM.',
  ),

  // Poderes de Inventor (p68-71)
  electivePower(C, 'Agite Antes de Usar',
    'Quando usa preparado alquímico que cause dano, gasta PM (limitado por Int) para cada PM adicionar 1 dado de dano do mesmo tipo.',
    { prerequisites: [note('Treinado em Ofício (alquimista)')] }),
  electivePower(C, 'Ajuste de Mira',
    'Ação padrão + PM (limitado por Int): aprimora arma de ataque à distância. Cada PM gasto: +1 rolagens de dano com arma até fim da cena.',
    { prerequisites: [power('class.inventor.balistica')] }),
  electivePower(C, 'Alquimista de Batalha',
    'Quando usa preparado alquímico ou poção que cause dano, soma Inteligência na rolagem de dano.',
    { prerequisites: [power('class.inventor.alquimista-iniciado')] }),
  electivePower(C, 'Alquimista Iniciado',
    'Recebe livro de fórmulas. Pode fabricar poções com fórmulas que conheça (1° e 2° círculos).',
    { prerequisites: [attr('intelligence', 1), attr('wisdom', 1), note('Treinado em Ofício (alquimista)')] }),
  electivePower(C, 'Armeiro',
    'Proficiência com armas marciais corpo a corpo. Quando empunha arma corpo a corpo, usa Inteligência em vez de Força nos ataques e rolagens de dano.',
    { prerequisites: [trained('Luta'), note('Treinado em Ofício (armeiro)')] }),
  electivePower(C, 'Ativação Rápida',
    'Ao ativar engenhoca com ação padrão, paga 2 PM para ativá-la com ação de movimento (em vez disto), uma vez por rodada.',
    { prerequisites: [power('class.inventor.engenhoqueiro')], minLevel: 7 }),
  electivePower(C, 'Aumento de Atributo',
    '+1 em um atributo. Apenas uma vez por patamar para um mesmo atributo.'),
  electivePower(C, 'Autômato',
    'Fabrica autômato (construto). Parceiro iniciante de um tipo (ajudante/assassino/atirador/combatente/guardião/montaria/vigilante). L7 vira veterano, L15 mestre. Se destruído, novo com semana de trabalho e T$ 100.',
    { prerequisites: [power('class.inventor.engenhoqueiro')] }),
  electivePower(C, 'Autômato Prototipado',
    'Ação padrão + 2 PM: ativa melhoria experimental no autômato. Rola 1d6 (2-6 melhora ou ganha habilidade; 1 emperra).',
    { prerequisites: [power('class.inventor.automato')] }),
  electivePower(C, 'Balística',
    'Proficiência com armas marciais de ataque à distância e armas de fogo. Quando usa arma de ataque à distância, soma Inteligência em vez de Destreza nos testes de ataque.',
    { prerequisites: [trained('Pontaria'), note('Treinado em Ofício (armeiro)')] }),
  electivePower(C, 'Blindagem',
    'Pode usar Inteligência na Defesa quando usa armadura pesada. Se fizer, não pode somar Destreza.',
    { prerequisites: [power('class.inventor.couraceiro')], minLevel: 8 }),
  electivePower(C, 'Cano Raiado',
    'Em arma de disparo feita por você mesmo, recebe +1 na margem de ameaça.',
    { prerequisites: [power('class.inventor.balistica')], minLevel: 5 }),
  electivePower(C, 'Catalisador Instável',
    'Ação completa + 3 PM: fabrica preparado alquímico ou poção (fórmula que conhece) instantaneamente. Custo metade. Dura até fim da cena.',
    { prerequisites: [power('class.inventor.alquimista-iniciado')] }),
  electivePower(C, 'Chutes e Palavrões',
    'Uma vez por rodada, em teste de Ofício (engenhoqueiro) para ativar engenhoca, paga 1 PM para rolá-lo novamente.',
    { prerequisites: [power('class.inventor.engenhoqueiro')] }),
  electivePower(C, 'Conhecimento de Fórmulas',
    'Aprende 3 fórmulas de quaisquer círculos que possa aprender. Pode escolher várias vezes.',
    { prerequisites: [power('class.inventor.alquimista-iniciado')] }),
  electivePower(C, 'Couraceiro',
    'Proficiência com armaduras pesadas e escudos. Quando usa armadura, soma Inteligência em vez de Destreza na Defesa (limitado por pesada).',
    { prerequisites: [note('Treinado em Ofício (armeiro)')] }),
  electivePower(C, 'Engenhoqueiro',
    'Pode fabricar engenhocas. Ver regras p70.',
    { prerequisites: [attr('intelligence', 3), note('Treinado em Ofício (engenhoqueiro)')] }),
  electivePower(C, 'Farmacêutico',
    'Quando usa item alquímico que cure PV, gasta PM (limitado por Int) para cada PM curar dado adicional.',
    { prerequisites: [attr('wisdom', 1), note('Treinado em Ofício (alquimista)')] }),
  electivePower(C, 'Ferreiro',
    'Quando usa arma corpo-a-corpo feita por você mesmo, dano dela aumenta um passo.',
    { prerequisites: [power('class.inventor.armeiro')], minLevel: 5 }),
  electivePower(C, 'Granadeiro',
    'Pode arremessar itens alquímicos e poções em alcance médio. Soma Int para calcular CD desses itens.',
    { prerequisites: [power('class.inventor.alquimista-de-batalha')] }),
  electivePower(C, 'Homúnculo',
    'Possui homúnculo (Minúsculo, alquímico). Telepatia em alcance longo. Obedece ordens. Parceiro iniciante. Pode perder 1d6 PV para homúnculo virar guardião iniciante até fim cena.',
    { prerequisites: [power('class.inventor.alquimista-iniciado')] }),
  electivePower(C, 'Invenção Potente',
    'Quando usa item ou engenhoca fabricado por você mesmo, paga 1 PM para aumentar em +2 a CD para resistir a ele.'),
  electivePower(C, 'Maestria em Perícia',
    'Escolha n° de perícias treinadas = Inteligência (sem bônus temporários). Em teste dessas perícias, gasta 1 PM para escolher 10 em qualquer situação (exceto ataque).'),
  electivePower(C, 'Manutenção Eficiente',
    'Engenhocas que pode manter aumenta em +3. Cada engenhoca ocupa metade do espaço.',
    { prerequisites: [power('class.inventor.engenhoqueiro')], minLevel: 5 }),
  electivePower(C, 'Mestre Alquimista',
    'Pode fabricar poções com fórmulas que conheça de qualquer círculo.',
    { prerequisites: [attr('intelligence', 3), attr('wisdom', 3), power('class.inventor.alquimista-iniciado')], minLevel: 10 }),
  electivePower(C, 'Mestre Cuca',
    'Todas comidas que cozinha têm bônus numérico aumentado em +1.',
    { prerequisites: [note('Treinado em Ofício (cozinheiro)')] }),
  electivePower(C, 'Mistura Fervilhante',
    'Quando usa item alquímico ou poção, gasta 2 PM para dobrar área de efeito.',
    { prerequisites: [power('class.inventor.alquimista-iniciado')], minLevel: 5 }),
  electivePower(C, 'Oficina de Campo',
    'Gasta 1 hora + 2 PM: manutenção do equipamento do grupo. Cada membro escolhe arma/armadura/escudo. Armas +1 ataque, armaduras/escudos +1 Defesa. Duram 1 dia.',
    { prerequisites: [note('Treinado em Ofício (armeiro)')] }),
  electivePower(C, 'Pedra de Amolar',
    'Ação de movimento + PM (limitado por Int): aprimora arma corpo-a-corpo empunhada. Cada PM: +1 rolagens de dano até fim da cena.',
    { prerequisites: [power('class.inventor.armeiro')] }),
  electivePower(C, 'Síntese Rápida',
    'Ao fabricar item alquímico ou poção, pode fabricar dobro de doses (pagando custo de matéria-prima de cada).',
    { prerequisites: [power('class.inventor.alquimista-iniciado')] }),
]
