import { attr, autoPower, electivePower, note, power, trained } from './_helpers'
import type { ClassPower } from '../types'

const C = 'Ladino'

/**
 * PDF Cap 1 (Ladino, p72-74, Tabela 1-15). Auto: Ataque Furtivo +1d6 +
 * Especialista L1. AF scaling cada nível par e algumas vezes ímpar. Evasão
 * L2. Esquiva Sobrenatural L4. Olhos nas Costas L8. Evasão Aprimorada L10.
 * "A Pessoa Certa para o Trabalho" L20. 19 power slots L2-L20.
 *
 * Ataque Furtivo scaling: +1d6 L1, +2d6 L3, +3d6 L5, +4d6 L7, +5d6 L9,
 * +6d6 L11, +7d6 L13, +8d6 L15, +9d6 L17, +10d6 L19.
 */
export const LADINO_POWERS: ClassPower[] = [
  autoPower(C, 1, 'Ataque Furtivo +1d6',
    'Uma vez por rodada, ao atingir criatura desprevenida (corpo-a-corpo ou alcance curto) ou flanqueando, causa +1d6 dano extra. Cada 2 níveis: +1d6 adicional. Criaturas imunes a crítico imunes a furtivo.',
  ),
  autoPower(C, 1, 'Especialista',
    'Escolha n° de perícias treinadas = Inteligência (sem bônus temp, mín 1). Em teste de uma dessas perícias, gasta 1 PM para dobrar bônus de treinamento. Não em ataque.',
  ),
  autoPower(C, 2, 'Evasão',
    'Em teste de Reflexos que reduziria dano à metade, sucesso = 0 dano. Falha = dano normal. Exige liberdade de movimentos.',
  ),
  autoPower(C, 3, 'Ataque Furtivo +2d6',
    'Bônus do Ataque Furtivo sobe para +2d6.',
  ),
  autoPower(C, 4, 'Esquiva Sobrenatural',
    'Instintos apurados — nunca fica surpreendido.',
  ),
  autoPower(C, 5, 'Ataque Furtivo +3d6',
    'Bônus do Ataque Furtivo sobe para +3d6.',
  ),
  autoPower(C, 7, 'Ataque Furtivo +4d6',
    'Bônus do Ataque Furtivo sobe para +4d6.',
  ),
  autoPower(C, 8, 'Olhos nas Costas',
    'Pode lutar contra diversos inimigos como se fossem apenas um. Não pode ser flanqueado.',
  ),
  autoPower(C, 9, 'Ataque Furtivo +5d6',
    'Bônus do Ataque Furtivo sobe para +5d6.',
  ),
  autoPower(C, 10, 'Evasão Aprimorada',
    'Em teste Reflexos que reduziria dano à metade: sucesso = 0, falha = metade. Exige liberdade de movimentos.',
  ),
  autoPower(C, 11, 'Ataque Furtivo +6d6',
    'Bônus do Ataque Furtivo sobe para +6d6.',
  ),
  autoPower(C, 13, 'Ataque Furtivo +7d6',
    'Bônus do Ataque Furtivo sobe para +7d6.',
  ),
  autoPower(C, 15, 'Ataque Furtivo +8d6',
    'Bônus do Ataque Furtivo sobe para +8d6.',
  ),
  autoPower(C, 17, 'Ataque Furtivo +9d6',
    'Bônus do Ataque Furtivo sobe para +9d6.',
  ),
  autoPower(C, 19, 'Ataque Furtivo +10d6',
    'Bônus do Ataque Furtivo sobe para +10d6.',
  ),
  autoPower(C, 20, 'A Pessoa Certa para o Trabalho',
    'Capstone: mestre da ladinagem. Em ataque furtivo ou perícia da lista de ladino, gasta 5 PM para +10 no teste.',
  ),

  // Poderes de Ladino (p73-74)
  electivePower(C, 'Assassinar',
    'Ação de movimento + 3 PM: analisa criatura em alcance curto. Até fim do próximo turno, primeiro AF que causar dano a ela tem dados de furtivo dobrados.',
    { minLevel: 5 }),
  electivePower(C, 'Aumento de Atributo',
    '+1 em um atributo. Apenas uma vez por patamar para um mesmo atributo.'),
  electivePower(C, 'Contatos no Submundo',
    'Em vila ou maior, gasta 2 PM e teste Carisma CD 10. Se passar e estiver na comunidade: +5 Investigação para interrogar, compra itens mundanos/poções/pergaminhos com 20% desconto, acesso a itens proibidos.'),
  electivePower(C, 'Emboscar',
    'Na primeira rodada de cada combate, gasta 2 PM para ação padrão adicional em seu turno.',
    { prerequisites: [trained('Furtividade')] }),
  electivePower(C, 'Escapista',
    '+5 Acrobacia para escapar/passar por espaço apertado/passar por inimigo, e testes para resistir a efeitos de movimento.'),
  electivePower(C, 'Fuga Formidável',
    'Ação completa + 1 PM: analisa local. Até fim da cena: +3m deslocamento, +5 Acrobacia/Atletismo, ignora penalidades por terreno difícil.',
    { prerequisites: [attr('intelligence', 1)] }),
  electivePower(C, 'Gatuno',
    '+2 Atletismo. Quando escala, não fica desprevenido e avança deslocamento normal em vez de metade.'),
  electivePower(C, 'Ladrão Arcano',
    'Quando causa dano com AF a criatura capaz de lançar magias, pode "roubar" uma magia que ela tenha visto lançar. Paga 1 PM por círculo da magia. Pode roubar magias até 4° círculo. Lança até fim cena.',
    { prerequisites: [power('class.ladino.roubo-de-mana')], minLevel: 13 }),
  electivePower(C, 'Mão na Boca',
    '+2 em testes de agarrar. Quando acerta AF em criatura desprevenida, faz teste de agarrar como ação livre. Criatura agarrada não pode falar.',
    { prerequisites: [trained('Luta')] }),
  electivePower(C, 'Mãos Rápidas',
    'Uma vez por rodada, ao fazer teste de Ladinagem para abrir fechaduras/ocultar item/punga/sabotar, paga 1 PM para fazê-lo como ação livre.',
    { prerequisites: [attr('dexterity', 2), trained('Ladinagem')] }),
  electivePower(C, 'Mente Criminosa',
    'Soma Inteligência em Ladinagem e Furtividade.',
    { prerequisites: [attr('intelligence', 1)] }),
  electivePower(C, 'Oportunismo',
    'Uma vez por rodada, quando inimigo adjacente sofre dano de aliado, gasta 2 PM para ataque corpo-a-corpo contra esse inimigo.',
    { minLevel: 6 }),
  electivePower(C, 'Rolamento Defensivo',
    'Quando sofre dano, gasta 2 PM para reduzir dano à metade. Depois fica caído.',
    { prerequisites: [trained('Reflexos')] }),
  electivePower(C, 'Roubo de Mana',
    'Quando causa dano com AF, para cada 1d6 de dano do AF, recebe 1 PM temp e criatura perde 1 PM (se tiver). Uma vez por cena contra uma mesma criatura.',
    { prerequisites: [attr('intelligence', 1)] }),
  electivePower(C, 'Saqueador de Tumbas',
    '+5 Investigação para encontrar armadilhas + testes de resistência contra elas. Gasta ação padrão para desabilitar mecanismos em 1d4 rodadas (em vez do tempo normal).',
    { prerequisites: [power('class.ladino.truque-magico')], minLevel: 7 }),
  electivePower(C, 'Sombra',
    '+2 Furtividade. Não sofre penalidade em testes para se mover em deslocamento normal. Reduz penalidade para atacar/ações chamativas para -10.',
    { prerequisites: [trained('Furtividade')] }),
  electivePower(C, 'Truque Mágico',
    'Aprende e pode lançar uma magia arcana de 1° círculo à sua escolha. Custo normal em PM. Atributo-chave: Inteligência. Pode escolher várias vezes.',
    { prerequisites: [attr('intelligence', 1)] }),
  electivePower(C, 'Velocidade Ladina',
    'Uma vez por rodada, gasta 2 PM para ação de movimento adicional em seu turno.',
    { prerequisites: [attr('dexterity', 2), trained('Iniciativa')] }),
  electivePower(C, 'Veneno Persistente',
    'Quando aplica dose de veneno em uma arma, veneno dura por três ataques (em vez de apenas um).',
    { prerequisites: [power('class.ladino.veneno-potente')], minLevel: 8 }),
  electivePower(C, 'Veneno Potente',
    'CD para resistir aos venenos que você usa aumenta em +5.',
    { prerequisites: [note('Treinado em Ofício (alquimista)')] }),
]
