import { attr, autoPower, electivePower, power, trained } from './_helpers'
import type { ClassPower } from '../types'

const C = 'Nobre'

/**
 * PDF Cap 1 (Nobre, p78-80, Tabela 1-17). Auto: Autoconfiança + Espólio +
 * Orgulho L1. Palavras Afiadas (2d6) L2. Riqueza L3. Gritar Ordens L4.
 * Presença Aristocrática L5. Palavras Afiadas scaling (4d6/6d6/8d6/10d6 em
 * L6/10/14/18). Realeza L20. 19 power slots L2-L20.
 */
export const NOBRE_POWERS: ClassPower[] = [
  autoPower(C, 1, 'Autoconfiança',
    'Pode usar Carisma em vez de Destreza na Defesa (não soma atributo na Defesa quando usa armadura pesada).',
  ),
  autoPower(C, 1, 'Espólio',
    'Recebe item a sua escolha com preço de até T$ 2.000.',
  ),
  autoPower(C, 1, 'Orgulho',
    'Em teste de perícia, gasta PM (limitado por Car). Para cada PM, recebe +2 no teste.',
  ),
  autoPower(C, 2, 'Palavras Afiadas (2d6)',
    'Ação padrão + 1 PM: teste Diplomacia ou Intimidação oposto Vontade de criatura inteligente em alcance curto. Vencer = 2d6 dano psíquico não letal. Perder = metade. A cada 4 níveis pode gastar +1 PM para aumentar dano.',
  ),
  autoPower(C, 3, 'Riqueza',
    'Uma vez por aventura, teste Carisma com bônus = nível de nobre. Recebe TO igual ao resultado. Condicionado à família/patrono.',
  ),
  autoPower(C, 4, 'Gritar Ordens',
    'Gasta PM (limitado por Car). Até início do próximo turno, aliados em alcance curto recebem bônus em perícias = PM gasto.',
  ),
  autoPower(C, 5, 'Presença Aristocrática',
    'Sempre que criatura inteligente tentar machucá-lo, gasta 2 PM. Vontade CD Car ou não consegue machucá-lo e perde ação. 1x/cena contra mesma criatura.',
  ),
  autoPower(C, 6, 'Palavras Afiadas (4d6)',
    'Dano base de Palavras Afiadas sobe para 4d6.',
  ),
  autoPower(C, 10, 'Palavras Afiadas (6d6)',
    'Dano base de Palavras Afiadas sobe para 6d6.',
  ),
  autoPower(C, 14, 'Palavras Afiadas (8d6)',
    'Dano base de Palavras Afiadas sobe para 8d6.',
  ),
  autoPower(C, 18, 'Palavras Afiadas (10d6)',
    'Dano base de Palavras Afiadas sobe para 10d6.',
  ),
  autoPower(C, 20, 'Realeza',
    'Capstone: CD para resistir à Presença Aristocrática +5. Criatura que falhe Vontade por 10+ pontos se arrepende, passa a lutar ao seu lado pelo resto cena. Criatura reduzida a 0 PV por Palavras Afiadas não sofre dano, passa a lutar ao seu lado.',
  ),

  // Poderes de Nobre (p79-80)
  electivePower(C, 'Armadura Brilhante',
    'Pode usar Carisma na Defesa quando usa armadura pesada. Se fizer, não pode somar Destreza.',
    { minLevel: 8 }),
  electivePower(C, 'Aumento de Atributo',
    '+1 em um atributo. Apenas uma vez por patamar para um mesmo atributo.'),
  electivePower(C, 'Autoridade Feudal',
    'Em locais com influência (mestre decide), gasta 1 hora + 2 PM para conclamar parceiro iniciante até fim da aventura.',
    { minLevel: 6 }),
  electivePower(C, 'Educação Privilegiada',
    'Torna-se treinado em duas perícias de nobre a sua escolha.'),
  electivePower(C, 'Estrategista',
    'Pode direcionar aliados em alcance curto. Ação padrão + 1 PM por aliado (limitado por Car). No próximo turno do aliado, ele ganha ação de movimento adicional.',
    { prerequisites: [attr('intelligence', 1), trained('Guerra')], minLevel: 6 }),
  electivePower(C, 'Favor',
    'Pode pedir favor (5 PM + 1 hora de conversa). Funciona como persuasão (Diplomacia p118). Mais caros disponíveis (convite festa, carona, acesso militar). Mesmo favor não pode ser pedido por 1 semana.'),
  electivePower(C, 'General',
    'Quando usa Estrategista, aliados direcionados recebem 1d4 PM temp. Duram fim turno aliado. Não usados em conceder PM.',
    { prerequisites: [power('class.nobre.estrategista')], minLevel: 12 }),
  electivePower(C, 'Grito Tirânico',
    'Pode usar Palavras Afiadas como ação completa em vez de padrão. Se fizer, dados aumentam para d8 e atinge todos inimigos em alcance curto.',
    { minLevel: 8 }),
  electivePower(C, 'Inspirar Confiança',
    'Quando aliado em alcance curto faz teste, gasta 2 PM para ele rolar novamente esse teste.'),
  electivePower(C, 'Inspirar Glória',
    'Uma vez por rodada, gasta 5 PM para aliado em alcance curto ganhar ação padrão adicional no próximo turno. 1x/cena por aliado.',
    { prerequisites: [power('class.nobre.inspirar-confianca')], minLevel: 8 }),
  electivePower(C, 'Jogo da Corte',
    'Quando faz teste Diplomacia/Intuição/Nobreza, gasta 1 PM para rolá-lo novamente.'),
  electivePower(C, 'Liderar pelo Exemplo',
    'Gasta 2 PM para servir de inspiração. Até início próximo turno, sempre que passar em teste de perícia, aliados em alcance curto podem usar seu resultado em vez do próprio.',
    { minLevel: 6 }),
  electivePower(C, 'Língua de Ouro',
    'Ação padrão + 4 PM: gera efeito da magia Enfeitiçar com aprimoramento sugerir ação. Afeta todas criaturas em alcance (CD Car). Não é mágica.',
    { prerequisites: [power('class.nobre.lingua-de-prata')], minLevel: 8 }),
  electivePower(C, 'Língua de Prata',
    'Em teste de perícia baseada em Carisma, gasta 2 PM para receber bônus no teste igual à metade do seu nível.'),
  electivePower(C, 'Língua Rápida',
    'Em teste de Diplomacia para mudar atitude como ação completa, sofre penalidade de -5 em vez de -10.'),
  electivePower(C, 'Presença Majestosa',
    'Presença Aristocrática passa a funcionar contra qualquer criatura com valor de Inteligência (passa a afetar até animais, embora continue não funcionando contra criaturas sem Int). Pode usá-la mais de uma vez contra mesma criatura na mesma cena.',
    { minLevel: 16 }),
  electivePower(C, 'Título',
    'Adquire título de nobreza. Define benefícios com mestre. Em geral: 20 TO/nível por aventura ou ajuda de parceiro veterano.',
    { prerequisites: [power('class.nobre.autoridade-feudal')], minLevel: 10 }),
  electivePower(C, 'Voz Poderosa',
    '+2 Diplomacia e Intimidação. Habilidades de nobre com alcance curto passam a alcance médio.'),
]
