import type { CatalogItem } from '../types'

export const APPAREL: CatalogItem[] = [
  {
    id: 'andrajos-aldeao',
    name: 'Andrajos de aldeão',
    category: 'apparel',
    price: 1,
    slots: 1,
    equip: 'vested',
    modifiers: [
      {
        target: { k: 'expertise', name: 'Investigação' },
        amount: 2,
        bonusType: 'item',
        condition: { c: 'context', note: 'interrogar populares' },
      },
    ],
  },
  {
    id: 'bandana',
    name: 'Bandana',
    category: 'apparel',
    price: 5,
    slots: 1,
    equip: 'vested',
    modifiers: [
      {
        target: { k: 'expertise', name: 'Intimidação' },
        amount: 1,
        bonusType: 'item',
        condition: { c: 'vested' },
      },
    ],
  },
  {
    id: 'botas-reforcadas',
    name: 'Botas reforçadas',
    category: 'apparel',
    price: 20,
    slots: 1,
    equip: 'vested',
    modifiers: [
      {
        target: { k: 'displacement' },
        amount: 1.5,
        bonusType: 'item',
        condition: { c: 'vested' },
      },
    ],
  },
  {
    id: 'camisa-bufante',
    name: 'Camisa bufante',
    category: 'apparel',
    price: 25,
    slots: 1,
    equip: 'vested',
    modifiers: [
      {
        target: { k: 'expertise', name: 'Atuação' },
        amount: 1,
        bonusType: 'item',
        condition: { c: 'vested' },
      },
    ],
  },
  {
    id: 'capa-esvoacante',
    name: 'Capa esvoaçante',
    category: 'apparel',
    price: 25,
    slots: 1,
    equip: 'vested',
    modifiers: [
      {
        target: { k: 'expertise', name: 'Enganação' },
        amount: 1,
        bonusType: 'item',
        condition: { c: 'vested' },
      },
    ],
  },
  {
    id: 'capa-pesada',
    name: 'Capa pesada',
    category: 'apparel',
    price: 15,
    slots: 1,
    equip: 'vested',
    modifiers: [
      {
        target: { k: 'expertise', name: 'Fortitude' },
        amount: 1,
        bonusType: 'item',
        condition: { c: 'vested' },
      },
    ],
  },
  {
    id: 'casaco-longo',
    name: 'Casaco longo',
    category: 'apparel',
    price: 20,
    slots: 1,
    equip: 'vested',
    modifiers: [
      {
        target: { k: 'expertise', name: 'Fortitude' },
        amount: 5,
        bonusType: 'item',
        condition: { c: 'context', note: 'resistir ao frio' },
      },
      {
        target: { k: 'armorPenalty' },
        amount: -2,
        bonusType: 'untyped',
        condition: { c: 'vested' },
      },
    ],
  },
  {
    id: 'chapeu-arcano',
    name: 'Chapéu arcano',
    category: 'apparel',
    price: 50,
    slots: 1,
    equip: 'vested',
    modifiers: [
      {
        target: { k: 'pmLimit' },
        amount: 1,
        bonusType: 'item',
        condition: { c: 'context', note: 'apenas com habilidade Caminho do Arcanista' },
      },
    ],
  },
  {
    id: 'enfeite-elmo',
    name: 'Enfeite de elmo',
    category: 'apparel',
    price: 15,
    slots: 1,
    equip: 'vested',
    modifiers: [
      {
        target: { k: 'fearResistance' },
        amount: 2,
        bonusType: 'item',
        condition: { c: 'vested' },
      },
    ],
  },
  {
    id: 'farrapos-ermitao',
    name: 'Farrapos de ermitão',
    category: 'apparel',
    price: 1,
    slots: 1,
    equip: 'vested',
    modifiers: [
      {
        target: { k: 'expertise', name: 'Adestramento' },
        amount: 2,
        bonusType: 'item',
        condition: { c: 'vested' },
      },
    ],
  },
  {
    id: 'gorro-ervas',
    name: 'Gorro de ervas',
    category: 'apparel',
    price: 75,
    slots: 1,
    equip: 'vested',
    modifiers: [
      {
        target: { k: 'expertise', name: 'Vontade' },
        amount: 1,
        bonusType: 'item',
        condition: { c: 'vested' },
      },
    ],
  },
  {
    id: 'luva-pelica',
    name: 'Luva de pelica',
    category: 'apparel',
    price: 5,
    slots: 1,
    equip: 'vested',
    modifiers: [
      {
        target: { k: 'expertise', name: 'Ladinagem' },
        amount: 1,
        bonusType: 'item',
        condition: { c: 'vested' },
      },
    ],
  },
  {
    id: 'manopla',
    name: 'Manopla',
    category: 'apparel',
    price: 10,
    slots: 1,
    equip: 'vested',
    modifiers: [
      {
        target: { k: 'flag', name: 'lethal-unarmed' },
        amount: 1,
        bonusType: 'untyped',
        condition: { c: 'vested' },
      },
    ],
  },
  {
    id: 'manto-camuflado',
    name: 'Manto camuflado',
    category: 'apparel',
    price: 12,
    slots: 1,
    equip: 'vested',
    modifiers: [
      {
        target: { k: 'expertise', name: 'Furtividade' },
        amount: 2,
        bonusType: 'item',
        condition: { c: 'terrain', type: 'compatível com o manto' },
      },
    ],
  },
  {
    id: 'manto-eclesiastico',
    name: 'Manto eclesiástico',
    category: 'apparel',
    price: 20,
    slots: 1,
    equip: 'vested',
    modifiers: [
      {
        target: { k: 'expertise', name: 'Religião' },
        amount: 1,
        bonusType: 'item',
        condition: { c: 'vested' },
      },
    ],
  },
  {
    id: 'robe-mistico',
    name: 'Robe místico',
    category: 'apparel',
    price: 50,
    slots: 1,
    equip: 'vested',
    modifiers: [
      {
        target: { k: 'expertise', name: 'Misticismo' },
        amount: 1,
        bonusType: 'item',
        condition: { c: 'vested' },
      },
    ],
  },
  {
    id: 'sapatos-camurca',
    name: 'Sapatos de camurça',
    category: 'apparel',
    price: 8,
    slots: 1,
    equip: 'vested',
    modifiers: [
      {
        target: { k: 'expertise', name: 'Acrobacia' },
        amount: 1,
        bonusType: 'item',
        condition: { c: 'vested' },
      },
    ],
  },
  {
    id: 'tabardo',
    name: 'Tabardo',
    category: 'apparel',
    price: 10,
    slots: 1,
    equip: 'vested',
    modifiers: [
      {
        target: { k: 'expertise', name: 'Diplomacia' },
        amount: 1,
        bonusType: 'item',
        condition: { c: 'vested' },
      },
    ],
  },
  {
    id: 'traje-corte',
    name: 'Traje da corte',
    category: 'apparel',
    price: 100,
    slots: 1,
    equip: 'vested',
    modifiers: [],
  },
  {
    id: 'traje-viajante',
    name: 'Traje de viajante',
    category: 'apparel',
    price: 10,
    slots: 0,
    equip: 'vested',
    modifiers: [],
  },
  {
    id: 'veste-seda',
    name: 'Veste de seda',
    category: 'apparel',
    price: 25,
    slots: 1,
    equip: 'vested',
    modifiers: [
      {
        target: { k: 'expertise', name: 'Reflexos' },
        amount: 1,
        bonusType: 'item',
        condition: { c: 'vested' },
      },
    ],
  },

  // ── Esotéricos (PDF p159–160) ──
  // Esotéricos must be empunhados (held) to grant their bonuses.
  {
    id: 'bolsa-de-po',
    name: 'Bolsa de pó',
    category: 'apparel',
    price: 300,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    modifiers: [],
  },
  {
    id: 'cajado-arcano',
    name: 'Cajado arcano',
    category: 'apparel',
    price: 1000,
    slots: 2,
    equip: 'wielded',
    hands: 2,
    modifiers: [
      {
        target: { k: 'pmLimit' },
        amount: 1,
        bonusType: 'enhancement',
        condition: { c: 'wielded' },
        note: '+1 limite de PM em magias arcanas',
      },
      {
        target: { k: 'spellDC' },
        amount: 1,
        bonusType: 'enhancement',
        condition: { c: 'wielded' },
        note: '+1 CD para resistir (arcanas)',
      },
    ],
  },
  {
    id: 'cetro-elemental',
    name: 'Cetro elemental',
    category: 'apparel',
    price: 750,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    modifiers: [],
  },
  {
    id: 'costela-de-lich',
    name: 'Costela de lich',
    category: 'apparel',
    price: 300,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    modifiers: [],
  },
  {
    id: 'dedo-de-ente',
    name: 'Dedo de ente',
    category: 'apparel',
    price: 200,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    modifiers: [],
  },
  {
    id: 'luva-de-ferro',
    name: 'Luva de ferro',
    category: 'apparel',
    price: 150,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    modifiers: [],
  },
  {
    id: 'medalhao-de-prata',
    name: 'Medalhão de prata',
    category: 'apparel',
    price: 750,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    modifiers: [
      {
        target: { k: 'pmLimit' },
        amount: 1,
        bonusType: 'enhancement',
        condition: { c: 'wielded' },
        note: '+1 limite de PM em magias de alcance pessoal',
      },
    ],
  },
  {
    id: 'orbe-cristalino',
    name: 'Orbe cristalino',
    category: 'apparel',
    price: 750,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    modifiers: [
      {
        target: { k: 'pmLimit' },
        amount: 1,
        bonusType: 'enhancement',
        condition: { c: 'wielded' },
        note: '+1 limite de PM em magias arcanas pessoais',
      },
    ],
  },
  {
    id: 'tomo-hermetico',
    name: 'Tomo hermético',
    category: 'apparel',
    price: 1500,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    modifiers: [
      {
        target: { k: 'spellDC' },
        amount: 2,
        bonusType: 'enhancement',
        condition: { c: 'wielded' },
        note: '+2 CD em uma escola de magia escolhida',
      },
    ],
  },
  {
    id: 'varinha-arcana',
    name: 'Varinha arcana',
    category: 'apparel',
    price: 100,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    modifiers: [
      {
        target: { k: 'spellDC' },
        amount: 1,
        bonusType: 'enhancement',
        condition: { c: 'wielded' },
        note: '+1 CD para resistir (arcanas)',
      },
    ],
  },

  // ── Equipamento de Aventura — bens mecanicamente relevantes (PDF p155–157) ──
  {
    id: 'mochila-aventureiro',
    name: 'Mochila de aventureiro',
    category: 'apparel',
    price: 50,
    slots: 0,
    equip: 'vested',
    modifiers: [
      {
        target: { k: 'inventorySlots' },
        amount: 2,
        bonusType: 'untyped',
        condition: { c: 'vested' },
        note: '+2 espaços de carga',
      },
    ],
  },
  {
    id: 'simbolo-sagrado',
    name: 'Símbolo sagrado',
    category: 'apparel',
    price: 5,
    slots: 1,
    equip: 'vested',
    modifiers: [
      {
        target: { k: 'resistance' },
        amount: 1,
        bonusType: 'item',
        condition: { c: 'context', note: 'devoto do deus correspondente' },
        note: '+1 testes de resistência (se devoto)',
      },
    ],
  },
  {
    id: 'bandoleira-pocoes',
    name: 'Bandoleira de poções',
    category: 'apparel',
    price: 20,
    slots: 1,
    equip: 'vested',
    modifiers: [],
  },

  // ── Ferramentas — mecanicamente relevantes (PDF p158) ──
  {
    id: 'maleta-medicamentos',
    name: 'Maleta de medicamentos',
    category: 'apparel',
    price: 50,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    modifiers: [],
  },
  {
    id: 'luneta',
    name: 'Luneta',
    category: 'apparel',
    price: 100,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    modifiers: [
      {
        target: { k: 'expertise', name: 'Percepção' },
        amount: 5,
        bonusType: 'item',
        condition: { c: 'context', note: 'observar alcance longo+' },
        note: '+5 Percepção em alcance longo',
      },
    ],
  },
  {
    id: 'coleccao-de-livros',
    name: 'Coleção de livros',
    category: 'apparel',
    price: 75,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    modifiers: [
      {
        target: { k: 'expertise', name: 'Conhecimento' },
        amount: 1,
        bonusType: 'item',
        condition: { c: 'context', note: 'assunto específico' },
        note: '+1 em uma perícia de conhecimento',
      },
    ],
  },
]
