import type { CatalogItem } from '../types'

export const ARMORS: CatalogItem[] = [
  {
    id: 'armadura-acolchoada',
    name: 'Armadura acolchoada',
    category: 'armor-light',
    price: 5,
    slots: 2,
    equip: 'vested',
    armor: { defense: 1, penalty: 0, heavy: false },
    modifiers: [
      { target: { k: 'defense' }, amount: 1, bonusType: 'armor', condition: { c: 'vested' } },
      { target: { k: 'expertise', name: 'Fortitude' }, amount: 2, bonusType: 'item', condition: { c: 'vested' } },
    ],
  },
  {
    id: 'armadura-couro',
    name: 'Armadura de couro',
    category: 'armor-light',
    price: 20,
    slots: 2,
    equip: 'vested',
    armor: { defense: 2, penalty: 0, heavy: false },
    modifiers: [
      { target: { k: 'defense' }, amount: 2, bonusType: 'armor', condition: { c: 'vested' } },
    ],
  },
  {
    id: 'couro-batido',
    name: 'Couro batido',
    category: 'armor-light',
    price: 35,
    slots: 2,
    equip: 'vested',
    armor: { defense: 3, penalty: -1, heavy: false },
    modifiers: [
      { target: { k: 'defense' }, amount: 3, bonusType: 'armor', condition: { c: 'vested' } },
      { target: { k: 'armorPenalty' }, amount: -1, bonusType: 'untyped', condition: { c: 'vested' } },
    ],
  },
  {
    id: 'gibao-peles',
    name: 'Gibão de peles',
    category: 'armor-light',
    price: 25,
    slots: 2,
    equip: 'vested',
    armor: { defense: 4, penalty: -3, heavy: false },
    modifiers: [
      { target: { k: 'defense' }, amount: 4, bonusType: 'armor', condition: { c: 'vested' } },
      { target: { k: 'armorPenalty' }, amount: -3, bonusType: 'untyped', condition: { c: 'vested' } },
    ],
  },
  {
    id: 'couraca',
    name: 'Couraça',
    category: 'armor-light',
    price: 500,
    slots: 2,
    equip: 'vested',
    armor: { defense: 5, penalty: -4, heavy: false },
    modifiers: [
      { target: { k: 'defense' }, amount: 5, bonusType: 'armor', condition: { c: 'vested' } },
      { target: { k: 'armorPenalty' }, amount: -4, bonusType: 'untyped', condition: { c: 'vested' } },
    ],
  },
  {
    id: 'brunea',
    name: 'Brunea',
    category: 'armor-heavy',
    price: 50,
    slots: 5,
    equip: 'vested',
    armor: { defense: 5, penalty: -2, heavy: true },
    modifiers: [
      { target: { k: 'defense' }, amount: 5, bonusType: 'armor', condition: { c: 'vested' } },
      { target: { k: 'armorPenalty' }, amount: -2, bonusType: 'untyped', condition: { c: 'vested' } },
      { target: { k: 'displacement' }, amount: -3, bonusType: 'untyped', condition: { c: 'vested' } },
      { target: { k: 'flag', name: 'cannot-apply-dex-to-defense' }, amount: 1, bonusType: 'untyped', condition: { c: 'vested' } },
      { target: { k: 'flag', name: 'fatigue-on-sleep' }, amount: 1, bonusType: 'untyped', condition: { c: 'vested' } },
    ],
  },
  {
    id: 'cota-malha',
    name: 'Cota de malha',
    category: 'armor-heavy',
    price: 150,
    slots: 5,
    equip: 'vested',
    armor: { defense: 6, penalty: -2, heavy: true },
    modifiers: [
      { target: { k: 'defense' }, amount: 6, bonusType: 'armor', condition: { c: 'vested' } },
      { target: { k: 'armorPenalty' }, amount: -2, bonusType: 'untyped', condition: { c: 'vested' } },
      { target: { k: 'displacement' }, amount: -3, bonusType: 'untyped', condition: { c: 'vested' } },
      { target: { k: 'flag', name: 'cannot-apply-dex-to-defense' }, amount: 1, bonusType: 'untyped', condition: { c: 'vested' } },
      { target: { k: 'flag', name: 'fatigue-on-sleep' }, amount: 1, bonusType: 'untyped', condition: { c: 'vested' } },
    ],
  },
  {
    id: 'loriga-segmentada',
    name: 'Loriga segmentada',
    category: 'armor-heavy',
    price: 250,
    slots: 5,
    equip: 'vested',
    armor: { defense: 7, penalty: -3, heavy: true },
    modifiers: [
      { target: { k: 'defense' }, amount: 7, bonusType: 'armor', condition: { c: 'vested' } },
      { target: { k: 'armorPenalty' }, amount: -3, bonusType: 'untyped', condition: { c: 'vested' } },
      { target: { k: 'displacement' }, amount: -3, bonusType: 'untyped', condition: { c: 'vested' } },
      { target: { k: 'flag', name: 'cannot-apply-dex-to-defense' }, amount: 1, bonusType: 'untyped', condition: { c: 'vested' } },
      { target: { k: 'flag', name: 'fatigue-on-sleep' }, amount: 1, bonusType: 'untyped', condition: { c: 'vested' } },
    ],
  },
  {
    id: 'meia-armadura',
    name: 'Meia armadura',
    category: 'armor-heavy',
    price: 600,
    slots: 5,
    equip: 'vested',
    armor: { defense: 8, penalty: -4, heavy: true },
    modifiers: [
      { target: { k: 'defense' }, amount: 8, bonusType: 'armor', condition: { c: 'vested' } },
      { target: { k: 'armorPenalty' }, amount: -4, bonusType: 'untyped', condition: { c: 'vested' } },
      { target: { k: 'displacement' }, amount: -3, bonusType: 'untyped', condition: { c: 'vested' } },
      { target: { k: 'flag', name: 'cannot-apply-dex-to-defense' }, amount: 1, bonusType: 'untyped', condition: { c: 'vested' } },
      { target: { k: 'flag', name: 'fatigue-on-sleep' }, amount: 1, bonusType: 'untyped', condition: { c: 'vested' } },
    ],
  },
  {
    id: 'armadura-completa',
    name: 'Armadura completa',
    category: 'armor-heavy',
    price: 3000,
    slots: 5,
    equip: 'vested',
    armor: { defense: 10, penalty: -5, heavy: true },
    modifiers: [
      { target: { k: 'defense' }, amount: 10, bonusType: 'armor', condition: { c: 'vested' } },
      { target: { k: 'armorPenalty' }, amount: -5, bonusType: 'untyped', condition: { c: 'vested' } },
      { target: { k: 'displacement' }, amount: -3, bonusType: 'untyped', condition: { c: 'vested' } },
      { target: { k: 'flag', name: 'cannot-apply-dex-to-defense' }, amount: 1, bonusType: 'untyped', condition: { c: 'vested' } },
      { target: { k: 'flag', name: 'fatigue-on-sleep' }, amount: 1, bonusType: 'untyped', condition: { c: 'vested' } },
    ],
  },
]
