import type { CatalogItem } from '../types'

export const CONSUMABLES: CatalogItem[] = [
  {
    id: 'balsamo-restaurador',
    name: 'Bálsamo restaurador',
    category: 'consumable',
    price: 25,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: {
      scope: 'instant',
      instant: { hp: { dice: '2d4' } },
    },
  },
  {
    id: 'essencia-de-mana',
    name: 'Essência de mana',
    category: 'consumable',
    price: 50,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: {
      scope: 'instant',
      instant: { mp: { dice: '1d4' } },
    },
  },
  {
    id: 'cosmetico',
    name: 'Cosmético',
    category: 'consumable',
    price: 5,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: {
      scope: 'scene',
      modifiers: [
        {
          target: { k: 'attribute', name: 'charisma' },
          amount: 2,
          bonusType: 'untyped',
        },
      ],
    },
  },
  {
    id: 'gorad-quente',
    name: 'Gorad quente',
    category: 'meal',
    price: 5,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: {
      scope: 'day',
      oncePerDay: true,
      instant: { mp: { dice: '0', bonus: 2 } },
    },
  },
  {
    id: 'macarrao-de-yuvalin',
    name: 'Macarrão de Yuvalin',
    category: 'meal',
    price: 5,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: {
      scope: 'day',
      oncePerDay: true,
      instant: { hp: { dice: '0', bonus: 5 } },
    },
  },
  {
    id: 'baga-de-fogo',
    name: 'Baga-de-fogo',
    category: 'catalyst',
    price: 30,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: {
      scope: 'scene',
      modifiers: [],
    },
  },

  // ── Alquímicos preparados (PDF p160) ──
  // Targets external creatures; "Usar" decrements stock without auto-applying
  // damage. GM resolves the throw / save manually.
  {
    id: 'acido',
    name: 'Ácido',
    category: 'consumable',
    price: 10,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: { scope: 'instant' },
  },
  {
    id: 'bomba',
    name: 'Bomba',
    category: 'consumable',
    price: 50,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: { scope: 'instant' },
  },
  {
    id: 'elixir-amor',
    name: 'Elixir do amor',
    category: 'consumable',
    price: 100,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: { scope: 'instant' },
  },
  {
    id: 'fogo-alquimico',
    name: 'Fogo alquímico',
    category: 'consumable',
    price: 10,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: { scope: 'instant' },
  },
  {
    id: 'po-desaparecimento',
    name: 'Pó do desaparecimento',
    category: 'consumable',
    price: 100,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: { scope: 'instant' },
  },

  // ── Alquímicos catalisadores (PDF p160–161) ──
  // Consumed when casting a specific magia. No automatic spell integration —
  // "Usar" just decrements stock so the player can track expenditure.
  {
    id: 'dente-dragao',
    name: 'Dente-de-dragão',
    category: 'catalyst',
    price: 45,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: { scope: 'instant' },
  },
  {
    id: 'essencia-abissal',
    name: 'Essência abissal',
    category: 'catalyst',
    price: 150,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: { scope: 'instant' },
  },
  {
    id: 'liquen-lilas',
    name: 'Líquen lilás',
    category: 'catalyst',
    price: 30,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: { scope: 'instant' },
  },
  {
    id: 'musgo-purpura',
    name: 'Musgo púrpura',
    category: 'catalyst',
    price: 45,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: { scope: 'instant' },
  },
  {
    id: 'ossos-monstro',
    name: 'Ossos de monstro',
    category: 'catalyst',
    price: 45,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: { scope: 'instant' },
  },
  {
    id: 'po-cristal',
    name: 'Pó de cristal',
    category: 'catalyst',
    price: 30,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: { scope: 'instant' },
  },
  {
    id: 'po-giz',
    name: 'Pó de giz',
    category: 'catalyst',
    price: 30,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: { scope: 'instant' },
  },
  {
    id: 'ramo-verdejante',
    name: 'Ramo verdejante',
    category: 'catalyst',
    price: 45,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: { scope: 'instant' },
  },
  {
    id: 'saco-sal',
    name: 'Saco de sal',
    category: 'catalyst',
    price: 45,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: { scope: 'instant' },
  },
  {
    id: 'seixo-ambar',
    name: 'Seixo de âmbar',
    category: 'catalyst',
    price: 30,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: { scope: 'instant' },
  },
  {
    id: 'terra-cemiterio',
    name: 'Terra de cemitério',
    category: 'catalyst',
    price: 30,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: { scope: 'instant' },
  },

  // ── Alquímicos venenos (PDF p161) ──
  // Applied to weapons or food; "Usar" decrements stock when applied.
  {
    id: 'beladona',
    name: 'Beladona',
    category: 'consumable',
    price: 1500,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: { scope: 'instant' },
  },
  {
    id: 'bruma-sonolenta',
    name: 'Bruma sonolenta',
    category: 'consumable',
    price: 150,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: { scope: 'instant' },
  },
  {
    id: 'cicuta',
    name: 'Cicuta',
    category: 'consumable',
    price: 60,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: { scope: 'instant' },
  },
  {
    id: 'essencia-sombra',
    name: 'Essência de sombra',
    category: 'consumable',
    price: 100,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: { scope: 'instant' },
  },
  {
    id: 'nevoa-toxica',
    name: 'Névoa tóxica',
    category: 'consumable',
    price: 30,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: { scope: 'instant' },
  },
  {
    id: 'peconha-comum',
    name: 'Peçonha comum',
    category: 'consumable',
    price: 15,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: { scope: 'instant' },
  },
  {
    id: 'peconha-concentrada',
    name: 'Peçonha concentrada',
    category: 'consumable',
    price: 90,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: { scope: 'instant' },
  },
  {
    id: 'peconha-potente',
    name: 'Peçonha potente',
    category: 'consumable',
    price: 600,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: { scope: 'instant' },
  },
  {
    id: 'po-lich',
    name: 'Pó de lich',
    category: 'consumable',
    price: 3000,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: { scope: 'instant' },
  },
  {
    id: 'riso-nimb',
    name: 'Riso de Nimb',
    category: 'consumable',
    price: 150,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: { scope: 'instant' },
  },

  // ── Pratos especiais (PDF p168) ──
  {
    id: 'batata-valkariana',
    name: 'Batata valkariana',
    category: 'meal',
    price: 2,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: { scope: 'day', oncePerDay: true },
  },
  {
    id: 'prato-aventureiro',
    name: 'Prato do aventureiro',
    category: 'meal',
    price: 1,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: { scope: 'day', oncePerDay: true },
  },
  {
    id: 'sopa-peixe',
    name: 'Sopa de peixe',
    category: 'meal',
    price: 1,
    slots: 0.5,
    equip: 'either',
    modifiers: [],
    consumable: { scope: 'day', oncePerDay: true },
  },
]
