import type { CatalogItem } from '../types'

export const WEAPONS: CatalogItem[] = [
  // Simples — Corpo a Corpo Leves
  {
    id: 'adaga',
    name: 'Adaga',
    category: 'weapon-simple',
    price: 2,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    weapon: {
      damage: '1d4',
      critRange: 19,
      critMult: 2,
      type: 'perfuracao',
      hand: 'light',
      purpose: 'melee',
      range: 'curto',
      traits: [],
    },
    modifiers: [],
  },
  {
    id: 'espada-curta',
    name: 'Espada curta',
    category: 'weapon-simple',
    price: 10,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    weapon: {
      damage: '1d6',
      critRange: 19,
      critMult: 2,
      type: 'perfuracao',
      hand: 'light',
      purpose: 'melee',
      traits: [],
    },
    modifiers: [],
  },
  {
    id: 'foice',
    name: 'Foice',
    category: 'weapon-simple',
    price: 4,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    weapon: {
      damage: '1d6',
      critRange: 20,
      critMult: 3,
      type: 'corte',
      hand: 'light',
      purpose: 'melee',
      traits: [],
    },
    modifiers: [],
  },
  // Simples — Corpo a Corpo Uma Mão
  {
    id: 'clava',
    name: 'Clava',
    category: 'weapon-simple',
    price: 0,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    weapon: {
      damage: '1d6',
      critRange: 20,
      critMult: 2,
      type: 'impacto',
      hand: 'one',
      purpose: 'melee',
      traits: [],
    },
    modifiers: [],
  },
  {
    id: 'lanca',
    name: 'Lança',
    category: 'weapon-simple',
    price: 2,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    weapon: {
      damage: '1d6',
      critRange: 20,
      critMult: 2,
      type: 'perfuracao',
      hand: 'one',
      purpose: 'thrown',
      range: 'curto',
      traits: [],
    },
    modifiers: [],
  },
  {
    id: 'maca',
    name: 'Maça',
    category: 'weapon-simple',
    price: 12,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    weapon: {
      damage: '1d8',
      critRange: 20,
      critMult: 2,
      type: 'impacto',
      hand: 'one',
      purpose: 'melee',
      traits: [],
    },
    modifiers: [],
  },
  // Simples — Corpo a Corpo Duas Mãos
  {
    id: 'bordao',
    name: 'Bordão',
    category: 'weapon-simple',
    price: 0,
    slots: 2,
    equip: 'wielded',
    hands: 2,
    weapon: {
      damage: '1d6/1d6',
      critRange: 20,
      critMult: 2,
      type: 'impacto',
      hand: 'two',
      purpose: 'melee',
      traits: ['dupla'],
    },
    modifiers: [],
  },
  {
    id: 'pique',
    name: 'Pique',
    category: 'weapon-simple',
    price: 2,
    slots: 2,
    equip: 'wielded',
    hands: 2,
    weapon: {
      damage: '1d8',
      critRange: 20,
      critMult: 2,
      type: 'perfuracao',
      hand: 'two',
      purpose: 'melee',
      traits: ['alongada'],
    },
    modifiers: [],
  },
  {
    id: 'tacape',
    name: 'Tacape',
    category: 'weapon-simple',
    price: 0,
    slots: 2,
    equip: 'wielded',
    hands: 2,
    weapon: {
      damage: '1d10',
      critRange: 20,
      critMult: 2,
      type: 'impacto',
      hand: 'two',
      purpose: 'melee',
      traits: [],
    },
    modifiers: [],
  },
  // Simples — Distância Uma Mão
  {
    id: 'azagaia',
    name: 'Azagaia',
    category: 'weapon-simple',
    price: 1,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    weapon: {
      damage: '1d6',
      critRange: 20,
      critMult: 2,
      type: 'perfuracao',
      hand: 'one',
      purpose: 'thrown',
      range: 'medio',
      traits: [],
    },
    modifiers: [],
  },
  {
    id: 'besta-leve',
    name: 'Besta leve',
    category: 'weapon-simple',
    price: 35,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    weapon: {
      damage: '1d8',
      critRange: 19,
      critMult: 2,
      type: 'perfuracao',
      hand: 'one',
      purpose: 'ranged',
      range: 'medio',
      traits: [],
    },
    modifiers: [],
  },
  {
    id: 'funda',
    name: 'Funda',
    category: 'weapon-simple',
    price: 0,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    weapon: {
      damage: '1d4',
      critRange: 20,
      critMult: 2,
      type: 'impacto',
      hand: 'one',
      purpose: 'ranged',
      range: 'medio',
      traits: [],
    },
    modifiers: [],
  },
  // Simples — Distância Duas Mãos
  {
    id: 'arco-curto',
    name: 'Arco curto',
    category: 'weapon-simple',
    price: 30,
    slots: 2,
    equip: 'wielded',
    hands: 2,
    weapon: {
      damage: '1d6',
      critRange: 20,
      critMult: 3,
      type: 'perfuracao',
      hand: 'two',
      purpose: 'ranged',
      range: 'medio',
      traits: [],
    },
    modifiers: [],
  },
  // Marciais — Leves
  {
    id: 'machadinha',
    name: 'Machadinha',
    category: 'weapon-martial',
    price: 6,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    weapon: {
      damage: '1d6',
      critRange: 20,
      critMult: 3,
      type: 'corte',
      hand: 'light',
      purpose: 'thrown',
      range: 'curto',
      traits: [],
    },
    modifiers: [],
  },
  // Marciais — Uma Mão
  {
    id: 'cimitarra',
    name: 'Cimitarra',
    category: 'weapon-martial',
    price: 15,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    weapon: {
      damage: '1d6',
      critRange: 18,
      critMult: 2,
      type: 'corte',
      hand: 'one',
      purpose: 'melee',
      traits: ['agil'],
    },
    modifiers: [],
  },
  {
    id: 'espada-longa',
    name: 'Espada longa',
    category: 'weapon-martial',
    price: 15,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    weapon: {
      damage: '1d8',
      critRange: 19,
      critMult: 2,
      type: 'corte',
      hand: 'one',
      purpose: 'melee',
      traits: [],
    },
    modifiers: [],
  },
  {
    id: 'florete',
    name: 'Florete',
    category: 'weapon-martial',
    price: 20,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    weapon: {
      damage: '1d8',
      critRange: 18,
      critMult: 2,
      type: 'perfuracao',
      hand: 'one',
      purpose: 'melee',
      traits: ['agil'],
    },
    modifiers: [],
  },
  {
    id: 'machado-batalha',
    name: 'Machado de batalha',
    category: 'weapon-martial',
    price: 10,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    weapon: {
      damage: '1d8',
      critRange: 20,
      critMult: 3,
      type: 'corte',
      hand: 'one',
      purpose: 'melee',
      traits: [],
    },
    modifiers: [],
  },
  {
    id: 'mangual',
    name: 'Mangual',
    category: 'weapon-martial',
    price: 8,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    weapon: {
      damage: '1d8',
      critRange: 20,
      critMult: 2,
      type: 'impacto',
      hand: 'one',
      purpose: 'melee',
      traits: ['versatil'],
    },
    modifiers: [
      {
        target: { k: 'maneuver', name: 'desarmar' },
        amount: 2,
        bonusType: 'item',
        condition: { c: 'wielded' },
      },
    ],
  },
  {
    id: 'martelo-guerra',
    name: 'Martelo de guerra',
    category: 'weapon-martial',
    price: 12,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    weapon: {
      damage: '1d8',
      critRange: 20,
      critMult: 3,
      type: 'impacto',
      hand: 'one',
      purpose: 'melee',
      traits: [],
    },
    modifiers: [],
  },
  {
    id: 'picareta',
    name: 'Picareta',
    category: 'weapon-martial',
    price: 8,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    weapon: {
      damage: '1d6',
      critRange: 20,
      critMult: 4,
      type: 'perfuracao',
      hand: 'one',
      purpose: 'melee',
      traits: [],
    },
    modifiers: [],
  },
  {
    id: 'tridente',
    name: 'Tridente',
    category: 'weapon-martial',
    price: 15,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    weapon: {
      damage: '1d8',
      critRange: 20,
      critMult: 2,
      type: 'perfuracao',
      hand: 'one',
      purpose: 'thrown',
      range: 'curto',
      traits: ['versatil'],
    },
    modifiers: [
      {
        target: { k: 'maneuver', name: 'derrubar' },
        amount: 2,
        bonusType: 'item',
        condition: { c: 'wielded' },
      },
    ],
  },
  // Marciais — Duas Mãos
  {
    id: 'alabarda',
    name: 'Alabarda',
    category: 'weapon-martial',
    price: 10,
    slots: 2,
    equip: 'wielded',
    hands: 2,
    weapon: {
      damage: '1d10',
      critRange: 20,
      critMult: 3,
      type: 'corte-perfuracao',
      hand: 'two',
      purpose: 'melee',
      traits: ['alongada'],
    },
    modifiers: [],
  },
  {
    id: 'alfange',
    name: 'Alfange',
    category: 'weapon-martial',
    price: 75,
    slots: 2,
    equip: 'wielded',
    hands: 2,
    weapon: {
      damage: '2d4',
      critRange: 18,
      critMult: 2,
      type: 'corte',
      hand: 'two',
      purpose: 'melee',
      traits: [],
    },
    modifiers: [],
  },
  {
    id: 'gadanho',
    name: 'Gadanho',
    category: 'weapon-martial',
    price: 18,
    slots: 2,
    equip: 'wielded',
    hands: 2,
    weapon: {
      damage: '2d4',
      critRange: 20,
      critMult: 4,
      type: 'corte',
      hand: 'two',
      purpose: 'melee',
      traits: [],
    },
    modifiers: [],
  },
  {
    id: 'lanca-montada',
    name: 'Lança montada',
    category: 'weapon-martial',
    price: 10,
    slots: 2,
    equip: 'wielded',
    hands: 2,
    weapon: {
      damage: '1d8',
      critRange: 20,
      critMult: 3,
      type: 'perfuracao',
      hand: 'two',
      purpose: 'melee',
      traits: ['alongada'],
    },
    modifiers: [],
  },
  {
    id: 'machado-guerra',
    name: 'Machado de guerra',
    category: 'weapon-martial',
    price: 20,
    slots: 2,
    equip: 'wielded',
    hands: 2,
    weapon: {
      damage: '1d12',
      critRange: 20,
      critMult: 3,
      type: 'corte',
      hand: 'two',
      purpose: 'melee',
      traits: [],
    },
    modifiers: [],
  },
  {
    id: 'marreta',
    name: 'Marreta',
    category: 'weapon-martial',
    price: 20,
    slots: 2,
    equip: 'wielded',
    hands: 2,
    weapon: {
      damage: '3d4',
      critRange: 20,
      critMult: 2,
      type: 'impacto',
      hand: 'two',
      purpose: 'melee',
      traits: [],
    },
    modifiers: [],
  },
  {
    id: 'montante',
    name: 'Montante',
    category: 'weapon-martial',
    price: 50,
    slots: 2,
    equip: 'wielded',
    hands: 2,
    weapon: {
      damage: '2d6',
      critRange: 19,
      critMult: 2,
      type: 'corte',
      hand: 'two',
      purpose: 'melee',
      traits: [],
    },
    modifiers: [],
  },
  // Marciais — Distância Duas Mãos
  {
    id: 'arco-longo',
    name: 'Arco longo',
    category: 'weapon-martial',
    price: 100,
    slots: 2,
    equip: 'wielded',
    hands: 2,
    weapon: {
      damage: '1d8',
      critRange: 20,
      critMult: 3,
      type: 'perfuracao',
      hand: 'two',
      purpose: 'ranged',
      range: 'medio',
      traits: [],
    },
    modifiers: [],
  },
  {
    id: 'besta-pesada',
    name: 'Besta pesada',
    category: 'weapon-martial',
    price: 50,
    slots: 2,
    equip: 'wielded',
    hands: 2,
    weapon: {
      damage: '1d12',
      critRange: 19,
      critMult: 2,
      type: 'perfuracao',
      hand: 'two',
      purpose: 'ranged',
      range: 'medio',
      traits: [],
    },
    modifiers: [],
  },
  // Exóticas — Uma Mão
  {
    id: 'chicote',
    name: 'Chicote',
    category: 'weapon-exotic',
    price: 2,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    weapon: {
      damage: '1d3',
      critRange: 20,
      critMult: 2,
      type: 'corte',
      hand: 'one',
      purpose: 'melee',
      traits: ['agil', 'versatil'],
    },
    modifiers: [
      {
        target: { k: 'maneuver', name: 'desarmar' },
        amount: 2,
        bonusType: 'item',
        condition: { c: 'wielded' },
      },
      {
        target: { k: 'maneuver', name: 'derrubar' },
        amount: 2,
        bonusType: 'item',
        condition: { c: 'wielded' },
      },
      {
        target: { k: 'flag', name: 'reach-extends' },
        amount: 1,
        bonusType: 'untyped',
        condition: { c: 'wielded' },
      },
    ],
  },
  {
    id: 'espada-bastarda',
    name: 'Espada bastarda',
    category: 'weapon-exotic',
    price: 35,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    weapon: {
      damage: '1d10/1d12',
      critRange: 19,
      critMult: 2,
      type: 'corte',
      hand: 'one',
      purpose: 'melee',
      traits: ['adaptavel'],
    },
    modifiers: [],
  },
  {
    id: 'katana',
    name: 'Katana',
    category: 'weapon-exotic',
    price: 100,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    weapon: {
      damage: '1d8/1d10',
      critRange: 19,
      critMult: 2,
      type: 'corte',
      hand: 'one',
      purpose: 'melee',
      traits: ['adaptavel', 'agil'],
    },
    modifiers: [],
  },
  {
    id: 'machado-anao',
    name: 'Machado anão',
    category: 'weapon-exotic',
    price: 30,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    weapon: {
      damage: '1d10',
      critRange: 20,
      critMult: 3,
      type: 'corte',
      hand: 'one',
      purpose: 'melee',
      traits: [],
    },
    modifiers: [],
  },
  // Exóticas — Duas Mãos
  {
    id: 'corrente-espinhos',
    name: 'Corrente de espinhos',
    category: 'weapon-exotic',
    price: 25,
    slots: 2,
    equip: 'wielded',
    hands: 2,
    weapon: {
      damage: '2d4/2d4',
      critRange: 19,
      critMult: 2,
      type: 'corte',
      hand: 'two',
      purpose: 'melee',
      traits: ['agil', 'dupla', 'versatil'],
    },
    modifiers: [
      {
        target: { k: 'maneuver', name: 'derrubar' },
        amount: 2,
        bonusType: 'item',
        condition: { c: 'wielded' },
      },
      {
        target: { k: 'maneuver', name: 'desarmar' },
        amount: 2,
        bonusType: 'item',
        condition: { c: 'wielded' },
      },
      {
        target: { k: 'flag', name: 'reach-extends' },
        amount: 1,
        bonusType: 'untyped',
        condition: { c: 'wielded' },
      },
    ],
  },
  {
    id: 'machado-taurico',
    name: 'Machado táurico',
    category: 'weapon-exotic',
    price: 50,
    slots: 2,
    equip: 'wielded',
    hands: 2,
    weapon: {
      damage: '2d8',
      critRange: 20,
      critMult: 3,
      type: 'corte',
      hand: 'two',
      purpose: 'melee',
      traits: ['desbalanceada'],
    },
    modifiers: [],
  },
  {
    id: 'rede',
    name: 'Rede',
    category: 'weapon-exotic',
    price: 20,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    weapon: {
      damage: '0',
      critRange: 20,
      critMult: 2,
      type: 'impacto',
      hand: 'one',
      purpose: 'thrown',
      range: 'curto',
      traits: [],
    },
    modifiers: [],
  },
  // Armas de Fogo
  {
    id: 'pistola',
    name: 'Pistola',
    category: 'weapon-firearm',
    price: 250,
    slots: 1,
    equip: 'wielded',
    hands: 1,
    weapon: {
      damage: '2d6',
      critRange: 19,
      critMult: 3,
      type: 'perfuracao',
      hand: 'light',
      purpose: 'ranged',
      range: 'curto',
      traits: [],
    },
    modifiers: [],
  },
  {
    id: 'mosquete',
    name: 'Mosquete',
    category: 'weapon-firearm',
    price: 500,
    slots: 2,
    equip: 'wielded',
    hands: 2,
    weapon: {
      damage: '2d8',
      critRange: 19,
      critMult: 3,
      type: 'perfuracao',
      hand: 'two',
      purpose: 'ranged',
      range: 'medio',
      traits: [],
    },
    modifiers: [],
  },
]
